services:
  - type: web
    name: gestionstagiaires
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: QONTO_LOGIN
        sync: false
      - key: QONTO_SECRET_KEY
        sync: false
      - key: QONTO_IBAN
        sync: false
      - key: QONTO_BENEFICIARY_NAME
        value: INTEGRALE ACADEMY
      - key: QONTO_API_BASE_URL
        value: https://thirdparty.qonto.com
      - key: PUBLIC_STUDENT_PORTAL_BASE
        value: https://gestionstagiaires-r5no.onrender.com

