"""Primary references checked 10 October 2026; original scenarios are not official papers."""
REFERENCES = {
    'transport': ('Code des transports — Transport public particulier de personnes', 'https://www.legifrance.gouv.fr/codes/id/LEGISCTA000030048385'),
    'access2026': ('Service Public Entreprendre — Accès VTC, disposition du 12 août 2026', 'https://entreprendre.service-public.gouv.fr/vosdroits/F31027'),
    'vehicle': ('Service Public Entreprendre — Conditions d’exploitation et véhicule VTC', 'https://entreprendre.service-public.gouv.fr/vosdroits/F31027'),
    'register': ('Registre VTC — Informations générales et capacité financière', 'https://registre-vtc.developpement-durable.gouv.fr/public/aide/informations-generales'),
    'signage': ('Code des transports — Article R3122-8, signalétique', 'https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000034389549/2026-05-03'),
    'return': ('Code des transports — Article L3122-9, fin de prestation', 'https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000029529985/2026-01-27'),
    'exam': ('Référentiel de l’examen VTC — compétences professionnelles', 'https://www.legifrance.gouv.fr/loda/id/JORFTEXT000034379046'),
    'french': ('Référentiel de l’examen VTC — compréhension du français ; textes des exercices originaux', 'https://www.legifrance.gouv.fr/loda/id/JORFTEXT000034379046'),
    'english': ('British Council — Repères de langue A1–A2 ; échanges professionnels originaux', 'https://learnenglish.britishcouncil.org/free-resources/grammar/a1-a2'),
    'english_questions': ('British Council — Question words ; échanges professionnels originaux', 'https://learnenglishteens.britishcouncil.org/grammar/a1-a2-grammar/question-words'),
    'english_time': ('British Council — Prepositions of time ; exemples professionnels originaux', 'https://learnenglishteens.britishcouncil.org/grammar/a1-a2-grammar/prepositions-time'),
    'discrimination': ('Service Public — Discrimination : critères et traitement', 'https://www.service-public.gouv.fr/particuliers/vosdroits/F19448'),
    'violence': ('Service Public — Alerter et obtenir de l’aide face aux violences sexuelles', 'https://www.service-public.gouv.fr/particuliers/vosdroits/F1526'),
    'data': ('CNIL — Minimiser les données collectées', 'https://www.cnil.fr/fr/minimiser-les-donnees-collectees'),
    'prospecting': ('CNIL — Prospection électronique et droit d’opposition', 'https://www.cnil.fr/fr/la-prospection-commerciale-par-courrier-electronique-sms-mms-et-automate-dappel'),
    'liability': ('Service Public — Indemnisation d’un préjudice causé par une autre personne', 'https://www.service-public.gouv.fr/particuliers/vosdroits/F1422'),
    'price': ('DGCCRF — Information sur les prix et frais supplémentaires', 'https://www.economie.gouv.fr/dgccrf/les-fiches-pratiques/linformation-sur-les-prix'),
    'complaint': ('DGCCRF — Comment régler un litige de consommation', 'https://www.economie.gouv.fr/dgccrf/les-fiches-pratiques/comment-regler-un-litige-de-la-consommation'),
    'business': ('Guichet des formalités — Types d’entreprises et formes juridiques', 'https://formalites.entreprises.gouv.fr/types_entreprises.php'),
    'balance': ('Bpifrance Création — Bilan, actif et passif', 'https://bpifrance-creation.fr/bilan'),
    'cash': ('Bpifrance Création — Plan de trésorerie', 'https://bpifrance-creation.fr/plan-tresorerie'),
    'margin': ('Bpifrance Création — Marge sur coûts variables et seuil de rentabilité', 'https://bpifrance-creation.fr/encyclopedie/previsions-financieres-business-plan/previsions-financieres/seuil-rentabilite'),
    'vat': ('Bpifrance Création — Comparer HT, TTC et prévisions financières', 'https://bpifrance-creation.fr/encyclopedie/previsions-financieres-business-plan/previsions-financieres/seuil-rentabilite'),
    'invoice': ('Service Public Entreprendre — Facturation et correction des pièces', 'https://entreprendre.service-public.gouv.fr/vosdroits/F23208'),
    'employment': ('Service Public Entreprendre — Estimer le coût d’une embauche', 'https://entreprendre.service-public.gouv.fr/vosdroits/F39132'),
    'market': ('Bpifrance Création — Construire une offre, vérifier son marché et son modèle économique', 'https://bpifrance-creation.fr/moments-de-vie/comment-faire-business-plan-efficace'),
    'road': ('ONISR — Code de la route et partage de la voie publique', 'https://www.onisr.securite-routiere.gouv.fr/politique-de-securite-routiere/code-de-la-route'),
    'roadguide': ('Sécurité routière — Guide du bon conducteur', 'https://www.securite-routiere.gouv.fr/sites/default/files/2024-09/dsr_guide_bon_conducteur.pdf'),
    'seatbelt': ('Service Public — Ceinture et installation des occupants', 'https://www.service-public.gouv.fr/particuliers/vosdroits/F628'),
    'fatigue': ('Sécurité routière — Fatigue et conduite', 'https://modules.securite-routiere.gouv.fr/jsrt/Fatigue/Fatigue.html'),
    'phone': ('Sécurité routière — Distraction au volant', 'https://www.securite-routiere.gouv.fr/quand-vous-regardez-votre-telephone-qui-regarde-la-route'),
    'emergency': ('Ministère de l’Intérieur — Que faire en cas de panne ou d’accident', 'https://www.interieur.gouv.fr/archive/que-faire-en-cas-de-panne-ou-d-accident'),
}
