"""Preparation and decision training; no replacement for supervised driving."""
from .common import question as q, numbers, sorting, order, topic

DATA={
'C.01':('Préparer le véhicule et le départ',
 'La préparation commence avant l’arrivée du client. Vérifiez l’état extérieur, les pneumatiques, la visibilité, les équipements utiles, le niveau d’énergie et les documents nécessaires. Une anomalie importante doit être traitée avant le départ. Le contrôle quotidien ne remplace ni l’entretien ni les vérifications périodiques ; il permet de repérer ce qui a changé depuis la dernière utilisation.',
 'Organisez une vérification toujours dans le même ordre pour réduire les oublis : tour extérieur, habitacle, poste de conduite, documents et mission. La propreté participe au service, mais ne doit pas masquer un défaut de sécurité. Un voyant, un bruit inhabituel ou une perte de pression justifie une analyse adaptée ; l’horaire du client ne rend pas le défaut acceptable.',
 [('Un pneu semble fortement dégonflé avant la première course.','Traiter l’anomalie avant de partir','Partir pour vérifier à grande vitesse','Le défaut peut affecter la tenue de route ; il doit être vérifié avant la mission.'),('Le pare-brise est sale à l’intérieur et crée des reflets.','Nettoyer pour rétablir une visibilité correcte','Attendre que le client se plaigne','La visibilité fait partie de la préparation de sécurité.'),('Un bagage gêne le passage vers une sortie.','Le déplacer vers un emplacement sûr','Le laisser parce que le trajet est court','L’installation ne doit pas gêner la sécurité des occupants.'),('La voiture est propre mais un voyant inhabituel reste allumé.','Identifier le défaut et décider selon sa gravité','Considérer la propreté comme une preuve de bon état','Le niveau de service et l’état mécanique sont deux vérifications différentes.')]),
'C.02':('Choisir une allure adaptée aux conditions',
 'Une limitation est une valeur maximale autorisée, pas une vitesse à atteindre dans toute situation. La visibilité, l’adhérence, la densité, les usagers vulnérables et la capacité à s’arrêter dans l’espace visible peuvent imposer une allure plus faible. Le client ne peut pas transformer une contrainte horaire en autorisation de dépasser les règles.',
 'L’adaptation doit être anticipée et progressive quand la situation le permet. Réduisez avant la zone difficile, gardez une marge et évitez les corrections brusques. La vitesse augmente la distance parcourue pendant le temps de réaction et l’énergie à dissiper au freinage. Les exercices isolent certaines grandeurs pour comprendre le phénomène ; ils ne prédisent pas une distance d’arrêt universelle.',
 [('Le brouillard réduit fortement la visibilité alors que la route était fluide.','Réduire l’allure et augmenter les marges','Conserver systématiquement la vitesse maximale affichée','L’allure doit rester compatible avec la visibilité et la possibilité de s’arrêter.'),('Un client demande d’accélérer pour rattraper un retard.','Expliquer la limite et chercher une solution sûre','Accepter une infraction contre un pourboire','La sécurité et les règles de circulation ne se négocient pas.'),('Des piétons se rapprochent d’une traversée.','Anticiper et se préparer à ralentir ou s’arrêter','Accélérer pour passer avant eux','L’anticipation laisse le temps de traiter le risque.'),('Une voie paraît dégagée mais un virage masque la suite.','Adapter l’allure à l’espace visible','Se fier uniquement à la ligne droite précédente','Ce que l’on ne voit pas doit être intégré dans la marge de décision.')]),
'C.03':('Comprendre les distances sans formule magique',
 'Pendant le temps de réaction, le véhicule continue d’avancer. La distance correspondante dépend de la vitesse et du temps nécessaire avant l’action. La distance de freinage vient ensuite et dépend notamment de l’adhérence, de l’état du véhicule et du freinage. La distance d’arrêt réunit ces deux parties. Les repères de calcul ne remplacent jamais une marge adaptée aux conditions.',
 'La conversion utile est vitesse en km/h divisée par 3,6 pour obtenir des mètres par seconde. À 90 km/h, on parcourt 25 mètres en une seconde. Un intervalle de deux secondes correspond alors à 50 mètres parcourus, sans signifier que la distance d’arrêt sera toujours de 50 mètres. Cette différence est essentielle pour interpréter les exercices.',
 [('Vous parcourez 25 mètres par seconde.','En deux secondes, le véhicule parcourt 50 mètres','Le véhicule parcourt forcément seulement 25 mètres','La distance parcourue se calcule vitesse × durée.'),('La route devient glissante.','Augmenter les marges et adapter la conduite','Conserver la même marge parce que la limitation est identique','L’adhérence modifie la capacité à freiner et à maîtriser la trajectoire.'),('Le conducteur est distrait une seconde de plus.','Le véhicule avance davantage avant sa réaction','La distance de réaction reste toujours identique','Le véhicule continue d’avancer pendant le délai supplémentaire.'),('Une application donne une distance de freinage théorique.','Garder une marge et tenir compte des conditions réelles','Utiliser ce chiffre comme une garantie exacte','Une valeur théorique ne couvre pas toutes les situations.')]),
'C.04':('Observer loin, près et sur les côtés',
 'L’attention se répartit entre la trajectoire, les intersections, les rétroviseurs et les zones où un usager peut apparaître. Regarder loin aide à anticiper ; regarder près permet de contrôler l’environnement immédiat. Avant un déplacement latéral, les rétroviseurs ne dispensent pas du contrôle approprié des angles morts.',
 'Un usager vulnérable peut être masqué par un véhicule ou un obstacle. N’interprétez pas une absence de visibilité comme une absence de personne. La communication par clignotant annonce une intention ; elle ne donne pas priorité à la manœuvre. Une action se décide après observation et vérification de l’espace disponible.',
 [('Un cycliste peut se trouver dans l’angle mort avant un changement de direction.','Effectuer les contrôles adaptés avant la manœuvre','Se fier uniquement au clignotant','Le clignotant informe mais ne remplace pas l’observation.'),('Un fourgon masque une partie du passage piéton.','Anticiper la présence possible d’un piéton','Considérer que personne ne traverse','L’obstacle limite l’information disponible.'),('Le client parle avec animation à l’arrière.','Conserver le regard et l’attention nécessaires à la conduite','Se retourner longuement pour maintenir le contact visuel','La relation client doit rester compatible avec la sécurité.'),('Un conducteur voisin fait un geste pour vous laisser passer.','Vérifier vous-même les autres risques','Partir sans regarder les autres voies','Le geste d’un usager ne garantit pas tout l’environnement.')]),
'C.05':('Lire la signalisation avant de décider',
 'La décision dépend de la signalisation, des règles applicables et des mouvements des autres usagers. Un itinéraire GPS n’autorise jamais à ignorer un sens interdit ou une restriction. La signalisation temporaire et les instructions d’un agent peuvent modifier l’organisation habituelle. Il faut lire la situation actuelle, pas seulement appliquer le souvenir du lieu.',
 'À une intersection, observez suffisamment tôt pour éviter une décision brusque. Si vous manquez une direction, poursuivez vers une solution autorisée au lieu d’improviser un demi-tour dangereux. Un passager qui connaît les lieux peut aider à confirmer la destination, mais ne remplace pas votre responsabilité de conducteur.',
 [('Le GPS propose une rue signalée en sens interdit.','Suivre la signalisation et rechercher un autre itinéraire','Entrer parce que l’application le demande','La navigation ne prévaut pas sur la signalisation.'),('Un agent règle la circulation à un carrefour.','Respecter ses indications dans le cadre applicable','Ignorer l’agent parce que le trajet habituel est différent','Les indications de régulation doivent être prises en compte.'),('Une restriction temporaire apparaît sur le trajet habituel.','Adapter le parcours','La contourner en retirant la barrière','Une fermeture doit être respectée.'),('Vous manquez la sortie prévue.','Continuer jusqu’à une possibilité autorisée de réorientation','Reculer sur la voie pour récupérer la sortie','Une erreur de navigation ne justifie pas une manœuvre dangereuse.')]),
'C.06':('Installer les occupants et leurs effets',
 'La capacité autorisée du véhicule comprend le conducteur. Ne créez pas une place supplémentaire en partageant une ceinture ou en installant une personne sur des bagages. Le choix des dispositifs adaptés aux enfants doit être préparé avec les informations utiles à la réservation et les règles applicables. Une demande tardive exige une solution sûre avant le départ.',
 'Les bagages doivent être rangés de façon à ne pas devenir des projectiles, gêner la visibilité ou entraver l’accès. Demandez l’accord avant d’aider une personne ou de manipuler son matériel. La vérification de l’installation se fait avant de mettre le véhicule en mouvement et peut nécessiter une interruption dans un lieu sûr si un problème apparaît.',
 [('Cinq passagers se présentent dans une voiture de cinq places conducteur compris.','Prévoir une solution conforme à la capacité','Partager une ceinture entre deux personnes','La voiture n’offre ici que quatre places passagers.'),('Une valise lourde est posée sans maintien sur un siège.','La ranger de manière sûre avant le départ','La laisser puisque le passager la surveille','Un objet libre peut être projeté.'),('Un dispositif enfant nécessaire n’est pas disponible.','Résoudre le besoin avant le départ','Prendre le trajet court comme exemption automatique','Le besoin doit être traité conformément aux règles applicables au service.'),('Un passager veut se détacher pour chercher un objet.','S’arrêter dans un lieu sûr si nécessaire','L’encourager à se déplacer pendant la marche','Une intervention dans l’habitacle ne doit pas créer un risque supplémentaire.')]),
'C.07':('Reconnaître la baisse de vigilance',
 'La fatigue et la somnolence altèrent l’attention et les réactions. Des bâillements, des paupières lourdes ou des difficultés à maintenir la concentration doivent être pris au sérieux. L’ouverture d’une fenêtre ou une musique forte ne rétablit pas durablement une capacité de conduite sûre. L’organisation des horaires et des pauses prépare la prévention, mais il faut aussi réagir aux signes présents.',
 'Prévoir une pause signifie choisir une possibilité d’arrêt autorisée et une marge dans le planning. Si l’état du conducteur ne permet pas de poursuivre en sécurité, il faut interrompre la conduite et organiser la suite avec l’exploitant. Les exercices de planning n’établissent pas les durées réglementaires d’un statut : ils entraînent à repérer un enchaînement irréaliste et une décision de sécurité.',
 [('Les paupières deviennent lourdes et le conducteur lutte pour rester attentif.','S’arrêter en sécurité et traiter l’état de vigilance','Augmenter le volume de la musique et continuer coûte que coûte','Un signe de somnolence appelle une interruption sûre, pas une astuce de confort.'),('Deux missions ne laissent aucune marge pour une pause nécessaire.','Réorganiser avant de confirmer','Promettre les deux sans solution','Le planning doit être compatible avec la sécurité.'),('Le trajet est très familier.','Maintenir l’attention et surveiller la vigilance','Considérer que l’habitude supprime le risque','La familiarité ne protège pas de la baisse de vigilance.'),('La course suivante est réservée mais le conducteur n’est plus en état de conduire sûrement.','Prévenir et organiser une solution conforme','Continuer parce que la réservation est payée','Une obligation commerciale ne rend pas la conduite sûre.')]),
'C.08':('Alcool, substances et médicaments : décider avant de conduire',
 'Une consommation ou un traitement peut modifier l’attention, la vision et les réactions. Les pictogrammes et notices de médicaments donnent des indications à lire, mais une situation incertaine doit être éclaircie avec un professionnel de santé. Ne modifiez pas votre traitement de votre propre initiative pour pouvoir assurer une mission. La priorité est de ne pas prendre le volant lorsque la conduite n’est pas sûre.',
 'Les impressions personnelles ne mesurent pas de façon fiable l’aptitude à conduire ou le respect d’un seuil légal. Les règles relatives à l’alcool et aux stupéfiants s’appliquent indépendamment du souhait du client. Une boisson, un café ou une douche ne doit pas être présenté comme une méthode permettant de neutraliser rapidement un risque ou de garantir un contrôle négatif.',
 [('La notice d’un nouveau médicament signale un risque pour la conduite.','Demander conseil au professionnel de santé et respecter les précautions','Ignorer la notice si le trajet semble facile','Une vérification adaptée est nécessaire ; ne changez pas le traitement sans avis.'),('Le conducteur dit se sentir normal après avoir bu.','Ne pas utiliser ce ressenti comme preuve d’aptitude ou de conformité','Considérer le ressenti comme une mesure fiable','Le sentiment personnel ne garantit ni la sécurité ni le respect des règles.'),('Un client propose un verre avant de reprendre le service.','Préserver une conduite conforme et sûre','Accepter pour améliorer la relation commerciale','Le service client ne justifie pas de compromettre la conduite.'),('Un collègue conseille de supprimer une dose prescrite pour conduire.','Consulter le prescripteur ou le pharmacien','Modifier le traitement sur ce seul conseil','Le traitement relève d’un conseil médical adapté.')]),
'C.09':('Réduire les distractions avant le mouvement',
 'La distraction peut être visuelle, manuelle ou cognitive. Lire une notification, manipuler une application ou chercher un objet détourne des ressources nécessaires à la conduite. Préparez la destination et les réglages avant de partir. Si une correction demande de la manipulation, organisez un arrêt dans un endroit autorisé et sûr.',
 'La relation client doit rester compatible avec l’attention disponible. Une réponse courte peut reporter une recherche touristique ou une question administrative à l’arrêt. Un dispositif technique ne garantit pas que l’attention reste suffisante. La responsabilité consiste à éviter une tâche secondaire lorsque la circulation demande toute votre vigilance.',
 [('L’adresse change pendant une intersection complexe.','Rejoindre un arrêt sûr avant de manipuler la navigation','Saisir immédiatement l’adresse en conduisant','L’information peut attendre une phase sûre pour être traitée.'),('Le passager demande de chercher un restaurant sur le téléphone.','Proposer de vérifier une fois stationné','Parcourir les résultats en roulant','La recherche exige une attention incompatible avec certaines phases de conduite.'),('Un objet tombe au sol sous le siège.','Ne pas se pencher pour le récupérer en roulant','Le chercher immédiatement à une main','Le contrôle du véhicule doit être préservé.'),('Une notification de course arrive.','La traiter selon une procédure compatible avec la conduite','La lire systématiquement quelle que soit la situation','Le rythme de l’application ne doit pas imposer un comportement dangereux.')]),
'C.10':('Conduire avec anticipation et souplesse',
 'La souplesse vient d’abord de l’anticipation : lire les ralentissements, garder une marge, doser l’accélération et préparer les changements de direction. Elle améliore le confort et évite les corrections inutiles. Une conduite souple n’est pas une conduite passive ; le conducteur doit pouvoir réagir nettement lorsqu’un danger l’exige.',
 'L’écoconduite recherche une utilisation adaptée des moyens du véhicule, sans compromettre la sécurité. Le gonflage, la charge, la préparation de l’itinéraire et l’anticipation influencent la consommation. Les aides à la conduite sont des appuis dont les limites doivent être connues. Le conducteur reste responsable de l’observation et du contrôle.',
 [('Un ralentissement est visible loin devant.','Anticiper et ralentir progressivement selon la situation','Accélérer puis freiner brutalement au dernier moment','L’anticipation améliore les marges et le confort.'),('Un danger immédiat exige un freinage important.','Prioriser la sécurité même si le confort est affecté','Éviter de freiner pour rester souple','Le confort ne prime pas sur la prévention de la collision.'),('Une aide à la conduite est activée.','Surveiller la route et connaître ses limites','Cesser d’observer','L’assistance ne remplace pas la vigilance du conducteur.'),('Le véhicule transporte une charge inhabituelle.','Adapter la préparation et la conduite','Supposer qu’elle n’a aucun effet','La charge peut influencer le comportement et la consommation.')]),
'C.11':('Adapter les marges à la météo et à la nuit',
 'La pluie, le vent, le brouillard et l’obscurité peuvent réduire la visibilité ou l’adhérence. L’éclairage et les équipements doivent être adaptés dans le respect des règles, sans éblouir. La prudence concerne aussi les transitions : une zone d’ombre, une chaussée humide après une partie sèche ou une rafale à la sortie d’un abri.',
 'Une estimation GPS ne reflète pas toujours l’effet immédiat des conditions. Adaptez l’allure, les distances et l’organisation de la mission ; informez le client si l’horaire change. Si une route est fermée ou une situation n’est plus praticable en sécurité, choisissez une alternative autorisée ou interrompez la progression dans un lieu sûr.',
 [('Une forte pluie commence et la visibilité baisse.','Adapter l’allure et les marges','Conserver les mêmes paramètres pour respecter l’horaire','Les conditions réelles doivent guider la conduite.'),('Une route est fermée en raison d’un événement météo.','Respecter la fermeture et rechercher une alternative autorisée','Passer si un autre véhicule l’a fait','La présence d’un autre véhicule ne garantit pas la sécurité ni l’autorisation.'),('Les feux gênent les autres usagers.','Utiliser l’éclairage adapté sans éblouir','Maintenir systématiquement le plus puissant','La visibilité propre ne doit pas se faire au détriment de celle des autres.'),('Un aléa météo rend l’arrivée plus tardive.','Informer le client et préserver les marges','Compter rattraper le retard par la vitesse','Le traitement commercial accompagne la décision de sécurité.')]),
'C.12':('Gérer une panne ou un accident sans aggraver le risque',
 'La première séquence est protéger, alerter et suivre les consignes adaptées. Cherchez une position sûre et préservez les occupants des dangers de circulation. Les gestes et équipements se choisissent selon la situation et les règles applicables. N’exposez pas une personne à un danger supplémentaire pour installer un matériel ou prendre une photo.',
 'Une fois l’urgence traitée, organisez l’assistance, le remplacement éventuel et l’information du client. Conservez les faits nécessaires au constat, à l’entreprise et à l’assurance. Le retour à une prestation normale suppose une solution réellement sûre et conforme ; le simple fait que le moteur redémarre ne règle pas tout défaut.',
 [('Une panne immobilise le véhicule près de la circulation.','Prioriser la protection et l’alerte appropriée','Commencer par négocier la facture avec le client','Le danger immédiat passe avant le traitement commercial.'),('Un passager propose de traverser les voies pour chercher de l’aide.','L’en dissuader et utiliser un moyen d’alerte sûr','Le laisser traverser sans réflexion','Il faut éviter de créer un suraccident.'),('Un véhicule de remplacement est proposé.','Vérifier qu’il permet un transport sûr et conforme','Accepter n’importe quelle voiture disponible','Le remplacement reste soumis aux conditions du service.'),('Le client demande une explication après la mise en sécurité.','Donner une information factuelle et la solution prévue','Inventer un délai garanti sans confirmation','Une information fiable préserve la relation et évite une nouvelle promesse irréaliste.')]),
'H.01':('Lire la mission comme un ensemble de contraintes',
 'Une mission ne se résume pas à deux adresses. Vérifiez la date, l’heure, la personne à accueillir, le nombre de voyageurs, les bagages, les besoins d’assistance, les conditions de prix et les coordonnées utiles. Repérez ce qui manque et ce qui se contredit avant le départ. Le réservant et le passager peuvent être différents.',
 'Reformulez les éléments qui changent l’organisation : terminal, sortie, heure réelle de prise en charge ou contrainte d’arrivée. Vérifiez le véhicule et le temps nécessaire pour rejoindre le point. Un bon lu trop tard peut créer une erreur qui aurait été facile à éviter pendant la préparation.',
 [('Le nom du réservant diffère de celui du voyageur.','Clarifier les rôles et l’identité à accueillir','Supposer qu’une erreur est certaine','Une personne peut réserver pour une autre.'),('L’adresse comporte deux communes possibles.','Faire préciser l’adresse avant de partir','Choisir celle que le conducteur préfère','Une ambiguïté doit être levée avant d’engager le trajet.'),('Le nombre de bagages dépasse la capacité prévue.','Vérifier une solution adaptée','Les poser sans maintien dans l’habitacle','La capacité bagages participe à la faisabilité.'),('L’horaire d’arrivée demandé est incompatible avec le trajet estimé.','Clarifier et proposer une organisation réaliste','Promettre de compenser par la vitesse','La mission doit être préparée avec des hypothèses cohérentes.')]),
'H.02':('Comparer les itinéraires sur plusieurs critères',
 'L’itinéraire se choisit avec la destination exacte, les restrictions, la sécurité, le temps, le coût et les conditions de circulation. Le plus court en kilomètres n’est pas toujours le plus rapide ni le plus adapté. Une route interdite doit être éliminée avant toute comparaison économique. Les alternatives doivent rester compréhensibles pour le client.',
 'Ajoutez le temps d’approche, l’installation et une marge lorsque l’horaire d’arrivée est important. La durée de navigation reste une estimation. Les tableaux de cette formation décrivent des réseaux fictifs : ils servent à exercer le raisonnement sans conseiller un trajet réel ou garantir un temps de parcours.',
 [('Le trajet le plus court comporte une restriction incompatible avec le véhicule.','L’exclure des options possibles','Le choisir parce qu’il coûte moins cher','L’autorisation est un préalable à la comparaison.'),('Deux trajets sont autorisés, mais l’un comporte un péage non inclus.','Expliquer l’option et les conditions au client','Cacher le péage jusqu’à l’arrivée','Le choix doit être transparent.'),('Un itinéraire est plus long mais laisse davantage de marge dans les conditions du dossier.','Le comparer sur le temps et la fiabilité, pas seulement les kilomètres','Le rejeter automatiquement','Plusieurs critères peuvent modifier le choix.'),('Une fermeture survient après le départ.','Réévaluer le parcours et informer le client en sécurité','Ignorer la fermeture pour garder le plan initial','Un plan se met à jour avec la situation réelle.')]),
'H.03':('Installer le poste avant d’accueillir la route',
 'Réglez la position, le siège, l’appui-tête et les rétroviseurs pour conserver le contrôle et la visibilité. Installez les équipements de navigation de façon compatible avec le champ de vision et l’usage autorisé. Les objets libres doivent être rangés. Une préparation insuffisante crée des manipulations inutiles pendant le déplacement.',
 'Faites les réglages avant le mouvement et vérifiez les commandes que vous utiliserez. Le changement de véhicule mérite une familiarisation à l’arrêt. Si un réglage doit être repris en cours de mission, choisissez une possibilité sûre de vous arrêter plutôt que d’effectuer une manipulation complexe dans la circulation.',
 [('Le véhicule de remplacement dispose de commandes différentes.','Les repérer à l’arrêt avant le départ','Les découvrir pendant une intersection','La familiarisation réduit les distractions.'),('Le support de téléphone masque une partie de la route.','Revoir son installation','Le conserver pour mieux voir l’écran','L’équipement ne doit pas compromettre la visibilité.'),('Le siège impose une position inconfortable et un contrôle limité.','Régler le poste avant de partir','Attendre le milieu du trajet','Le poste participe au contrôle du véhicule.'),('Un câble gêne une commande.','Le ranger de manière sûre','Le déplacer avec le pied en roulant','L’environnement du conducteur doit rester dégagé.')]),
'H.04':('Accueillir avec discrétion et méthode',
 'Présentez-vous, confirmez la personne et la destination avec discrétion, puis accompagnez l’installation. Le bon client ne se reconnaît pas à une simple ressemblance avec un prénom annoncé dans la foule. Une information croisée de réservation réduit le risque d’erreur sans divulguer inutilement des données.',
 'Proposez votre aide pour les bagages et les besoins particuliers sans imposer de geste. Annoncez les informations utiles du trajet et vérifiez le confort avant le mouvement. Une relation professionnelle est courtoise mais respecte le souhait de calme et l’espace du passager.',
 [('Deux personnes portent le même prénom au point de rendez-vous.','Vérifier discrètement une information de réservation','Embarquer la première sans vérifier','La confirmation doit permettre d’éviter une erreur de personne.'),('Le passager ne souhaite pas discuter.','Respecter ce choix tout en donnant les informations utiles','Entretenir une conversation obligatoire','Le service s’adapte au besoin du client.'),('Une valise paraît lourde.','Proposer de l’aide et agir avec accord et prudence','L’arracher des mains du client','L’aide doit être consentie et sûre.'),('La destination annoncée par le client diffère du bon.','Clarifier avant le départ','Choisir sans l’informer','La contradiction doit être résolue avant la réalisation.')]),
'H.05':('Garder une attention disponible pendant la mission',
 'Une mission combine conduite et service, mais ces tâches ne demandent pas la même priorité à chaque instant. Une intersection, une manœuvre ou une situation dégradée peut exiger toute votre attention. Vous pouvez reporter une recherche ou une explication longue à une phase sûre.',
 'Le client doit comprendre que la préparation réduit les manipulations. Un changement en cours de trajet se traite par une reformulation puis une adaptation sûre. Une réponse professionnelle peut être : je confirme la nouvelle adresse dès que je peux m’arrêter dans un endroit autorisé.',
 [('Le client donne une nouvelle adresse pendant une manœuvre.','Terminer en sécurité puis confirmer et traiter la demande','Saisir l’adresse immédiatement','La séquence de conduite exige d’abord l’attention.'),('Le passager demande une longue explication touristique dans un passage difficile.','Reporter poliment l’explication','Se retourner pour montrer un monument','Le service doit préserver l’attention disponible.'),('Le chauffeur manque une rue.','Poursuivre jusqu’à une correction autorisée','Couper une trajectoire pour récupérer la rue','Une erreur de navigation ne doit pas produire un risque.'),('La navigation annonce une nouvelle option.','Vérifier sa cohérence avec la signalisation','Suivre aveuglément l’écran','L’observation reste indispensable.')]),
'H.06':('Préparer une dépose autorisée et accessible',
 'Repérez une zone de dépose qui respecte les règles et permet au passager de descendre sans exposition évitable. Un point au plus près d’une porte n’est pas toujours le plus sûr. Anticipez les piétons, cyclistes, véhicules et l’ouverture des portières. Une manœuvre se prépare avec une observation complète et une allure adaptée.',
 'Avant la descente, confirmez le lieu et indiquez le côté ou le chemin pertinent si cela aide. Organisez la récupération des bagages sans gêner la circulation. Le client peut demander une autre dépose ; vous devez alors trouver une solution autorisée, pas improviser un arrêt dangereux.',
 [('La porte demandée donne sur un emplacement interdit à l’arrêt.','Proposer la dépose autorisée la plus adaptée','S’arrêter exactement là quelles que soient les règles','Le service ne justifie pas une dépose dangereuse ou interdite.'),('Un cycliste approche du côté de la portière.','Attendre et prévenir le passager avant l’ouverture','Ouvrir pour faire ralentir le cycliste','L’ouverture doit être préparée en tenant compte des autres usagers.'),('Un passager cherche son bagage pendant que le véhicule bouge encore.','Attendre l’immobilisation sûre','Ouvrir le coffre en roulant','La descente et les bagages se traitent à l’arrêt.'),('La première zone de dépose est devenue inaccessible.','Rechercher un autre lieu autorisé et expliquer','Bloquer la circulation sans nécessité','La solution doit s’adapter à l’état réel des lieux.')]),
'H.07':('Apporter une information touristique fiable',
 'Une information utile peut porter sur un quartier, un repère, une correspondance ou une activité. Distinguez les faits stables et les informations qui changent : horaires, prix, disponibilité et accès. Une recommandation personnelle doit être présentée comme telle. En cas d’incertitude, proposez une vérification auprès d’une source appropriée.',
 'La conduite reste prioritaire pendant les phases exigeantes. Ne montrez pas un lieu en détournant durablement le regard et ne recherchez pas une information sur un appareil en roulant. Le client apprécie une réponse claire sur vos limites davantage qu’une certitude inventée.',
 [('Vous ignorez l’horaire d’un musée aujourd’hui.','Proposer de vérifier une source officielle à l’arrêt','Inventer un horaire vraisemblable','Une information variable doit être vérifiée.'),('Vous recommandez un restaurant apprécié personnellement.','Présenter cela comme un avis et vérifier la disponibilité si nécessaire','Garantir une table sans réservation','Un avis n’est pas une garantie de disponibilité.'),('Le passager demande une recherche pendant un carrefour complexe.','Reporter la recherche à une phase sûre','Lire le site en traversant le carrefour','L’attention de conduite prime.'),('Le quartier porte deux noms proches.','Confirmer le lieu exact avec le client','Choisir au hasard','La précision évite une information ou une dépose erronée.')]),
'H.08':('Gérer un imprévu avec une solution réaliste',
 'Un imprévu appelle trois réponses : préserver la sécurité, évaluer les conséquences et informer. Distinguez ce qui est certain, ce qui reste à confirmer et les options réellement disponibles. Un retard, une panne ou un changement de destination ne doit pas déclencher une promesse impossible à tenir.',
 'La solution peut impliquer l’exploitant ou un autre prestataire conforme. Confirmez les responsabilités et les informations transmises pour que le passager sache qui arrive, où et dans quelles conditions. Conservez les traces utiles du changement. Une solution annoncée n’est pas encore une solution disponible tant qu’elle n’est pas confirmée.',
 [('La route ferme et un rendez-vous devient incertain.','Informer avec une estimation actualisée et rechercher les options','Garantir l’arrivée initiale sans base','Le client doit pouvoir décider à partir d’une information fiable.'),('Un véhicule alternatif est seulement envisagé.','Le présenter comme une option à confirmer','L’annoncer comme déjà réservé','Il faut distinguer hypothèse et confirmation.'),('Le passager accepte une modification.','Confirmer le nouveau service et ses conditions','Effacer toute trace de l’échange','La confirmation évite un nouveau malentendu.'),('Le problème dépasse votre capacité de décision.','Mobiliser le bon interlocuteur','Prendre un engagement financier sans habilitation','La solution doit rester dans le périmètre de responsabilité.')]),
'H.09':('Expliquer le montant et le règlement à l’arrêt',
 'La facturation de la mission doit rester cohérente avec le service et les modifications acceptées. Expliquez clairement le montant, les éventuels postes supplémentaires et le mode de règlement. Le traitement du paiement demande une situation sûre ; il ne doit pas détourner la conduite.',
 'Vérifiez la confirmation d’un paiement avant d’en demander un autre. Une facture et un reçu ont des fonctions différentes. Si une erreur est confirmée, appliquez une correction traçable. Le client doit comprendre la prochaine étape lorsqu’un document doit être envoyé par le canal convenu.',
 [('Le paiement par carte affiche un statut incertain.','Vérifier avant toute nouvelle tentative','Demander immédiatement deux nouveaux paiements','Une vérification évite un double débit.'),('Le client conteste un supplément non annoncé.','Vérifier les conditions convenues et traiter l’écart','Le présenter comme obligatoire sans vérifier','Le montant doit correspondre à la prestation acceptée.'),('Le chauffeur veut manipuler le terminal en conduisant.','Reporter le paiement à l’arrêt en sécurité','Le faire sur les genoux en roulant','Le paiement ne doit pas perturber le contrôle du véhicule.'),('Une facture doit être corrigée.','Utiliser la procédure traçable de l’entreprise','La faire disparaître sans trace','Une correction doit rester explicable et documentée.')]),
'H.10':('Clore la mission et préparer la suivante',
 'La fin de prestation comporte la dépose, les bagages, le paiement et les documents, puis une vérification rapide de l’habitacle. Un objet oublié doit être traité avec un rapprochement de la bonne course et une remise sécurisée. Les informations du passager ne doivent pas être diffusées pour retrouver leur propriétaire.',
 'Le chauffeur examine ensuite l’état du véhicule, l’énergie, le planning et les conditions de la prochaine mission. Le temps de remise en état et de déplacement doit être pris en compte. Sans nouvelle réservation justifiée, les règles de retour ou de stationnement applicables au VTC restent à respecter.',
 [('Un téléphone est découvert après la dépose.','Vérifier la mission concernée et organiser une remise sécurisée','Publier les données de l’appareil en ligne','La restitution doit préserver les données et le bon destinataire.'),('Le prochain client arrive dans cinq minutes mais l’habitacle nécessite une remise en état.','Évaluer et traiter la situation avant de promettre le départ','Masquer le défaut','Le planning doit intégrer la préparation réelle.'),('Aucune mission suivante n’est réservée.','Respecter les règles de retour ou de stationnement','Attendre en emplacement taxi pour trouver un client','La fin de course ne permet pas la maraude.'),('Le client a plusieurs bagages similaires.','Vérifier avec lui la restitution complète','Fermer le coffre avant qu’il contrôle','Le contrôle de fin réduit les oublis et contestations.')]),
'H.11':('Comprendre ce que la pratique évalue',
 'La préparation du parcours, la sécurité et la souplesse de conduite, la relation client et la facturation sont des compétences complémentaires. La conduite pèse fortement dans l’évaluation et un événement éliminatoire ne se compense pas par un bon accueil. Les simulations numériques aident à raisonner, mais ne remplacent pas l’entraînement en circulation avec un formateur.',
 'Pour vous préparer, transformez les critères en comportements observables : lire le dossier, proposer un itinéraire autorisé, effectuer les contrôles, communiquer sans se distraire et expliquer le montant. Après une séance réelle, un retour ciblé sur une difficulté est plus utile qu’un simple « c’était bien » ou « c’était mauvais ». Les quiz de ce module ne certifient pas votre capacité à conduire.',
 [('Le candidat compte sur un excellent accueil pour compenser une conduite dangereuse.','Il doit corriger la conduite ; les qualités commerciales ne compensent pas tout','L’accueil annule automatiquement toute erreur','Les compétences ne sont pas interchangeables face à un risque éliminatoire.'),('Un stagiaire réussit les décisions en ligne.','Il doit encore s’entraîner en circulation avec un formateur','Il a automatiquement réussi l’épreuve officielle','Le numérique prépare le raisonnement mais n’évalue pas toute la conduite réelle.'),('Le formateur signale un contrôle visuel insuffisant.','Prévoir un entraînement ciblé et un nouveau retour','Ignorer ce point au profit du vocabulaire commercial','La remédiation doit correspondre à l’erreur observée.'),('Le candidat connaît le quartier mais néglige la mission fournie.','Revenir au dossier et aux critères demandés','Remplacer la destination par son trajet préféré','La prestation évaluée répond à une mission précise.')]),
'H.12':('Progresser par erreurs identifiées',
 'Une erreur devient utile lorsqu’elle est décrite précisément : quelle information a été manquée, quel raisonnement a conduit au choix et quelle vérification l’aurait évitée ? La bonne réponse apprise par cœur ne suffit pas si vous ne savez pas la transférer à une situation voisine. Reprenez donc une variante après avoir compris la correction.',
 'Organisez des révisions espacées entre lecture, décisions, calculs et simulations. Les bilans du parcours conservent les premières erreurs et donnent la priorité aux notions concernées. Cela ne remplace pas le retour d’un formateur sur la conduite réelle. Le temps nécessaire varie selon votre expérience, votre maîtrise de la langue et les reprises utiles.',
 [('Vous avez répondu juste après plusieurs essais mais ne comprenez pas pourquoi.','Relire le raisonnement puis résoudre une variante','Considérer que la compétence est nécessairement maîtrisée','La réussite par essais ne garantit pas le transfert.'),('La même confusion de calcul revient.','Identifier la base et reprendre des exercices ciblés','Relire uniquement le titre du module','La révision doit viser le mécanisme à l’origine de l’erreur.'),('Un bilan indique des erreurs sur les documents.','Commencer la révision par ces contrôles','Ignorer le bilan et répéter seulement les questions faciles','L’adaptation sert à travailler les besoins repérés.'),('Vous réussissez une simulation d’itinéraire sur écran.','Vérifier le transfert en préparation et en conduite encadrée','En déduire que tout trajet réel sera maîtrisé','Le réel ajoute l’environnement, les gestes et la pression de conduite.')]),
}

def clock(minutes):return f'{minutes//60:02d} h {minutes%60:02d}'

def route_set(ref,offset):
    result=[]
    for v in range(4):
        appointment=10*60+v*30;install=10;drive=30+offset+v*5;margin=15
        depart=appointment-drive-install-margin;km=25+v*5+offset;tolled=drive-10;cost=5+v
        context=f'Mission fictive {v+1}. Rendez-vous à {clock(appointment)}. Il faut prévoir {install} min d’installation et {margin} min de marge avant le rendez-vous. Les durées de ce tableau sont des hypothèses de calcul, pas des temps routiers réels.'
        routes=[{'name':'Itinéraire A · autorisé','details':f'{km} km · {drive} min · sans péage'},
                {'name':'Itinéraire B · autorisé','details':f'{km+8} km · {tolled} min · péage {cost} €'},
                {'name':'Itinéraire C · fermé','details':f'{km-5} km · {drive-15} min théoriques · accès interdit dans ce dossier'}]
        result.append(q(ref,context,'Quelle option doit être exclue avant de comparer les coûts et les délais ?','L’itinéraire C fermé','L’itinéraire A sans péage','L’itinéraire B avec péage','Une route fermée n’est pas une option utilisable, même si son temps théorique est plus court.',map=routes,stage='Itinéraire · faisabilité'))
        result.append(q(ref,context,'À quelle heure faut-il commencer l’installation si l’on choisit A et conserve toute la marge ?',clock(depart),clock(appointment-drive),clock(depart-20),f'{clock(appointment)} − {drive} min de trajet − {install} min d’installation − {margin} min de marge = {clock(depart)}.',map=routes,stage='Itinéraire · rétroplanning'))
        result.append(numbers(ref,context,'Quel gain de temps théorique B apporte-t-il par rapport à A ?',10,drive,tolled,f'{drive} − {tolled} = 10 minutes. Ce gain doit être comparé au péage et confirmé selon les conditions.',unit=' min',map=routes,stage='Itinéraire · comparaison'))
        result.append(q(ref,context+f' Le client refuse tout péage et accepte l’heure de départ calculée.','Quel itinéraire satisfait cette contrainte dans le tableau ?','A','B','C','A est autorisé et sans péage. C est fermé ; B ne respecte pas le choix de coût du client.',map=routes,stage='Itinéraire · choix confirmé'))
    return result

def build():
    topics={};practices={}
    for ref,(title,p1,p2,rows) in DATA.items():
        steps=['Repérer les faits et les contraintes du dossier.','Identifier le risque ou la limite à respecter.','Choisir une action sûre et autorisée.','Vérifier le résultat et informer les personnes concernées.']
        topics[ref]=topic(title,[p1,p2],rows[0][0]+' Le raisonnement conduit à '+rows[0][1].lower()+'. '+rows[0][3],steps,
          'Une pression horaire, une demande du client ou une aide technique ne supprime pas la vérification de sécurité.')
        practices[ref]=[]
        for i,(context,good,bad,why) in enumerate(rows):
            practices[ref].append(q(ref,context,'Quelle décision choisissez-vous ?',good,bad,'Reporter toute décision sans traiter le problème',why,
              stage=f'Décision {i+1} · situation professionnelle'))
        practices[ref].append(sorting(ref,'Repérez les décisions qui répondent au problème indiqué.','Chaque ligne reprend une situation avec une proposition. Évaluez l’action dans ce contexte précis.',
          ['Action adaptée au dossier','Action à corriger'],[(c+' → '+(good if i%2==0 else bad),0 if i%2==0 else 1) for i,(c,good,bad,why) in enumerate(rows)],
          'Les décisions adaptées traitent le risque identifié. La contrainte commerciale ne dispense pas de la sécurité. '+ ' '.join(r[3] for r in rows)))
        practices[ref].append(order(ref,'Retrouvez l’ordre de la méthode d’analyse avant l’action.',steps))
    for i,ref in enumerate(['H.01','H.02','H.05','H.06','H.08','H.10','H.12','C.02','C.05','C.07','C.10','C.11']):
        practices[ref].extend(route_set(ref,i%4))
    for n,speed in enumerate([36,54,72,90,108,126]):
        second=1+n%2;distance=speed/3.6*second
        context=f'Modèle de calcul uniquement : vitesse constante {speed} km/h et intervalle {second} seconde(s). Il ne s’agit pas d’une distance d’arrêt garantie ni d’une recommandation d’allure.'
        practices['C.03'].append(numbers('C.03',context,'Quelle distance est parcourue pendant cet intervalle ?',distance,speed*second,distance+10,
          f'Conversion : {speed} ÷ 3,6 = {speed/3.6:.1f} m/s. Distance = {speed/3.6:.1f} × {second} = {distance:.1f} m.',unit=' m'))
        practices['C.03'].append(q('C.03',context,'Ce résultat donne-t-il à lui seul la distance d’arrêt réelle ?','Non, le freinage et les conditions doivent aussi être pris en compte','Oui, quel que soit l’état de la route','Oui, si le client porte sa ceinture','Le déplacement pendant un intervalle n’est pas toute la distance d’arrêt.'))
    for ref in ['C.01','C.06','C.12','H.03','H.04','H.09','H.11']:
        for v in range(4):
            rows=[('Capacité : 4 passagers autorisés ; groupe de '+str(3+v)+' voyageurs',0 if v<=1 else 1),
                  ('Bagages : rangement sûr confirmé',0),('Équipement : défaut gênant la visibilité non traité',1),
                  ('Navigation : destination vérifiée à l’arrêt',0),('Poste de conduite : objet gênant une commande',1),
                  ('Prise en charge : lieu autorisé confirmé',0)]
            practices[ref].append(sorting(ref,f'Contrôle avant mission · dossier {v+1}','Classez chaque ligne du dossier fictif. « À traiter » signifie qu’une solution doit être trouvée avant de considérer cette ligne prête.',
                ['Élément prêt selon les faits','Élément à traiter'],rows,'La capacité, la visibilité, les commandes et le rangement doivent permettre une mission sûre. Les éléments déjà vérifiés ne dispensent pas de traiter les anomalies restantes.'))
    return topics,practices
