"""Original fictional dialogues for listening, comprehension and transfer."""
from .common import question as q, sorting, order, topic

LESSONS=[
 ('E.01','Accueillir, vérifier, rassurer','Good morning / good afternoon / good evening se choisissent selon le moment. Good night sert habituellement à prendre congé pour la nuit. Pour se présenter, I am devient I’m ; pour vérifier l’identité, on inverse avec Are you…? La courtoisie ne demande pas de phrases complexes. Une phrase courte, une pause et une confirmation sont souvent plus claires.','N’annoncez pas à voix haute toutes les données de la course. Présentez-vous, vérifiez le nom avec discrétion, puis confirmez la destination. Si la personne ne correspond pas, ne lui communiquez pas les informations d’un autre passager. Demandez de répéter avec Could you repeat that, please? La voix forte ne remplace pas une reformulation.',['driver|chauffeur','welcome|bienvenue','booking|réservation','outside|à l’extérieur','first name|prénom','surname|nom de famille']),
 ('E.02','Faire préciser la réservation','Les mots who, where, when, what et how many orientent la réponse. Where concerne le lieu, when le moment et how many une quantité dénombrable. Do you have a booking? utilise do devant un verbe ordinaire. Après does, le verbe reste à sa base : Does your colleague need a receipt?','Le point de prise en charge et la destination sont deux informations différentes. Répétez le nombre de passagers et l’adresse utile, puis demandez confirmation avec Is that right? Un nom d’hôtel peut correspondre à plusieurs établissements. La vérification porte donc aussi sur la rue ou la commune.',['passenger|passager','destination|destination','address|adresse','pick-up|prise en charge','departure|départ','arrival|arrivée']),
 ('E.03','Écouter les nombres sans deviner','Thirteen et thirty, fourteen et forty, fifteen et fifty se ressemblent pour un débutant. L’erreur sur un montant ou un horaire peut avoir plus de conséquences qu’une petite faute de grammaire. Répétez le nombre, demandez une confirmation et précisez morning ou evening lorsque le contexte est ambigu.','Half past seven signifie 7 h 30. A quarter past seven signifie 7 h 15. A quarter to eight signifie 7 h 45. La formulation numérique seven thirty reste simple et correcte. Pour une date, le mois écrit en lettres évite certaines ambiguïtés. At précède une heure ; on précède un jour dans les exemples usuels de rendez-vous.',['thirteen|treize','thirty|trente','fifteen|quinze','fifty|cinquante','half past|et demie','a quarter to|moins le quart']),
 ('E.04','Donner un rendez-vous facile à retrouver','Next to signifie à côté de, opposite en face de et between entre deux éléments. Distinguez entrance, exit, floor et level. Un lieu de rendez-vous utile combine un repère visible et une instruction courte. Left et right dépendent du point de vue : précisez le mouvement depuis une sortie connue.','Confirmez que le client se trouve au même terminal ou à la même sortie que vous. Si le téléphone coupe, une consigne déjà claire facilite la rencontre. Ne demandez pas au client de traverser une zone interdite ; proposez le chemin piéton autorisé et, si nécessaire, un autre point sûr.',['next to|à côté de','opposite|en face de','between|entre','entrance|entrée','exit|sortie','ground floor|rez-de-chaussée']),
 ('E.05','Proposer de l’aide sans l’imposer','May I help you with your luggage? demande l’autorisation d’aider. Luggage est habituellement indénombrable : on ne dit pas three luggages dans ces phrases. Pour compter, utilisez three bags ou three pieces of luggage. Heavy, fragile et foldable décrivent des contraintes différentes.','Demandez au passager comment manipuler un objet particulier. L’expression Please keep your medicine with you distingue ce qui peut rester accessible de ce qui est rangé dans le coffre. Une aide à la mobilité n’est pas un bagage ordinaire ; la manipulation exige l’accord et les précautions adaptées.',['luggage|bagages','suitcase|valise','boot|coffre','fragile|fragile','heavy|lourd','foldable|pliable']),
 ('E.06','Expliquer confort et sécurité','Would you like…? propose une option. Could you… please? formule une demande polie. Fasten your seat belt concerne la ceinture ; air conditioning concerne la climatisation. Dire Please let me know if… invite le client à signaler un besoin sans détourner continuellement l’attention du conducteur.','Une demande de confort ne doit pas compromettre la conduite. Le conducteur peut confirmer qu’il ajuste un réglage lorsqu’il pourra le faire en sécurité. Une réponse comme I’ll stop in a safe place first indique la priorité au bon moment, sans agressivité.',['seat belt|ceinture de sécurité','air conditioning|climatisation','warmer|plus chaud','cooler|plus frais','quiet|calme','safe place|endroit sûr']),
 ('E.07','Présenter un trajet et un choix','The journey takes about thirty minutes donne une estimation. About évite de présenter une durée incertaine comme une garantie. Toll road signifie route à péage ; traffic décrit la circulation. We can take… propose une possibilité, tandis que we must… exprime une obligation.','Expliquez le compromis entre durée, coût et conditions de circulation. Le client peut choisir une option dans le cadre de la prestation, mais ne peut pas vous demander d’ignorer une interdiction. Si la route est fermée, dites The road is closed et proposez une alternative autorisée.',['journey|trajet','toll road|route à péage','traffic|circulation','roadworks|travaux routiers','closed|fermé','alternative|solution de remplacement']),
 ('E.08','Annoncer ce qui est inclus dans le prix','The fare is… annonce un montant. It includes… indique ce qui est compris. Waiting time is not included doit être expliqué avant que le client découvre un supplément. Distinguez quote, fare, fee et tip : devis, prix de la course, frais et pourboire.','Si un changement affecte le prix, expliquez-le et obtenez l’accord avant d’engager la prestation modifiée. Une phrase simple comme The extra stop costs ten euros. Is that acceptable? permet la confirmation. Le ton doit rester informatif et transparent.',['fare|prix de la course','quote|devis','included|inclus','extra charge|supplément','waiting time|temps d’attente','tip|pourboire']),
 ('E.09','Annoncer un retard et convenir d’une modification','I’m running ten minutes late annonce un retard. The flight has been delayed concerne le vol. Distinguez un fait confirmé et une estimation avec expected ou about. Une excuse doit être suivie d’une information utile : nouvel horaire, point de rendez-vous ou prochaine mise à jour.','Lorsqu’une personne demande de changer le lieu, reformulez la nouvelle adresse et ses conséquences. Ne devinez pas si plusieurs lieux ont un nom proche. Le futur avec will sert à annoncer l’action prévue : I’ll call you when I arrive. Évitez une promesse impossible à tenir.',['delayed|retardé','on time|à l’heure','expected|prévu ou attendu','update|mise à jour','cancelled|annulé','reschedule|reprogrammer']),
 ('E.10','Faire payer et remettre le bon document','Would you like a receipt? propose un reçu. Invoice et receipt ne sont pas interchangeables : la facture décrit l’opération et le reçu atteste un paiement. By card ou in cash expriment le mode de règlement. Payment has been received indique une réception confirmée.','Si le terminal n’affiche pas une confirmation claire, vérifiez le statut avant de demander un second paiement. Évitez de traiter une simple tentative comme un encaissement confirmé. Pour une facture, confirmez les informations nécessaires sans demander de données supplémentaires inutiles.',['receipt|reçu','invoice|facture','by card|par carte','in cash|en espèces','payment|paiement','change|monnaie à rendre']),
 ('E.11','Gérer un problème avec des phrases maîtrisées','I’m sorry about the inconvenience reconnaît une difficulté sans inventer sa cause. Could you explain what happened? demande des faits. I’ll check with my office indique le recours à un interlocuteur. Ne promettez pas un remboursement que vous ne pouvez pas décider.','En cas de danger, la sécurité prime sur la recherche d’une phrase parfaite. I’ll stop in a safe place précise l’action. Pour un objet oublié, vérifiez la course et organisez la suite par un canal adapté. Préserver les données du client reste nécessaire même lorsqu’il est mécontent.',['problem|problème','lost item|objet perdu','damage|dommage','refund|remboursement','check|vérifier','inconvenience|désagrément']),
 ('E.12','Informer sur la ville sans détourner la conduite','You can visit… propose une visite ; it’s near… situe un lieu. Opening hours et booking required concernent des informations qui peuvent changer. Si vous ne savez pas, dites I’m not sure. I can check when we stop. Une information incertaine doit rester présentée comme telle.','Répondez brièvement lorsque vous conduisez et conservez l’attention nécessaire à la route. Distinguez recommendation et guarantee : recommander un endroit ne permet pas de promettre une disponibilité ou un horaire sans vérification. Les noms et horaires des activités audio sont fictifs.',['museum|musée','harbour|port','old town|vieille ville','opening hours|horaires d’ouverture','near|près de','booking required|réservation nécessaire']),
]

def build():
    topics={};practices={};dialogues=[]
    names=['Brown','Green','Wilson','Taylor'];destinations=['Central Hotel','Riverside Hotel','Garden Hotel','Harbour Hotel']
    for ref,title,p1,p2,vocab in LESSONS:
        topics[ref]=topic(title,[p1,p2],
            'Écoutez d’abord sans ouvrir le texte. Identifiez qui parle, le besoin, le lieu, le nombre ou l’heure. Réécoutez pour confirmer. Ouvrez ensuite le dialogue et sa traduction, puis reprenez à voix haute une phrase utile, si votre environnement le permet. Aucun enregistrement vocal ni texte à envoyer n’est demandé.',
            ['Comprendre le sens général avant de chercher chaque mot.','Repérer les informations qui changent la décision.','Confirmer la compréhension avec une phrase courte.'],
            'Si vous hésitez sur un nombre, une adresse ou un horaire, faites confirmer au lieu de deviner.')
        practices[ref]=[]
        unit=int(ref[2:])
        for v in range(4):
            name=names[v];hotel=destinations[v];pax=v+2;gate=v+2;price=60+10*v;minutes=25+5*v;late=10+5*v
            stage=f'Conversation {v+1} · écoute puis décision'
            if unit==1:
                turns=[f'Good evening. My name is Alex. I am your driver. Are you Ms {name}?',f'Yes, I am. Good evening. Thank you for waiting. It took a little longer to collect my luggage.',f'You are welcome. Your booking is for {hotel}, is that right?',f'Yes, that is right. I have {pax} bags. Could you help me with the largest one, please?','Of course. Your car is just outside. Please keep your passport and any medicine with you.','Thank you. I appreciate your help. I will keep my small bag with me.']
                rows=[('À quel moment l’accueil a-t-il lieu ?','Le soir','Le matin','Au moment de se coucher','Good evening est une salutation du soir ; good night aurait un autre usage.'),('Quelle destination est confirmée ?',hotel,destinations[(v+1)%4],'La gare centrale','Le conducteur confirme explicitement la destination indiquée.'),('Quelle aide est demandée ?','Porter le plus grand bagage','Changer le nom de la réservation','Réserver une chambre','Could you help me with the largest one concerne le plus grand bagage.')]
                translation=f'Alex accueille Mme {name} le soir, vérifie la réservation pour {hotel} et propose de l’aide. La cliente a {pax} bagages et demande de l’aide avec le plus grand. Les documents et médicaments restent avec elle.'
            elif unit==2:
                turns=['Good morning. Do you have a booking with our company?',f'Yes. The booking is under {name}. We are going to {hotel}.',f'Thank you. How many passengers are travelling today?',f'There are {pax} passengers. We also have two large suitcases.','I will check the vehicle capacity. Could you confirm the full address of the hotel, please?',f'Certainly. It is {20+v*10} River Street. There is another hotel with a similar name, so please use this address.']
                rows=[('Combien de passagers sont annoncés ?',str(pax),str(pax+1),str(pax+2),'How many passengers demande le nombre de personnes, pas le nombre de valises.'),('Quelle donnée doit éviter la confusion entre hôtels ?','L’adresse complète','La couleur des valises','La nationalité des voyageurs','Le nom seul peut correspondre à plusieurs établissements.'),('What name is the booking under? sert à demander…','le nom utilisé pour réserver','la rue à emprunter','le prix du petit déjeuner','Booking under a name signifie réservation au nom de cette personne.')]
                translation=f'La réservation est au nom de {name}, pour {pax} passagers et deux grandes valises, vers {hotel}, au {20+v*10} River Street. Le conducteur vérifie l’adresse car plusieurs hôtels ont un nom proche.'
            elif unit==3:
                time=['seven thirty','a quarter past eight','a quarter to nine','half past ten'][v];digital=['7 h 30','8 h 15','8 h 45','10 h 30'][v]
                turns=['Could you confirm the pick-up time for tomorrow, please?',f'Yes. Please collect us at {time} in the morning. Our appointment starts later.',f'Thank you. I will repeat that: {time} in the morning. Is that correct?','Yes, exactly. We need enough time to arrive calmly. There will be two passengers.',f'The agreed fare is {price} euros. Could you confirm that amount as well? ',f'Yes, {price} euros. Thank you for checking both the time and the price.']
                rows=[('Quelle heure faut-il retenir ?',digital,['8 h 30','8 h 45','9 h 15','10 h 15'][v],'19 h 30','L’expression doit être interprétée avec in the morning ; past et to ne donnent pas la même heure.'),('Quel montant est confirmé ?',f'{price} €',f'{price+15} €',f'{price-10} €','Le montant est répété par les deux personnes.'),('Pourquoi le conducteur répète-t-il les informations ?','Pour éviter une erreur sur l’heure et le prix','Pour ajouter un supplément','Pour annuler la réservation','La reformulation permet au client de corriger une incompréhension.')]
                translation=f'La prise en charge est prévue demain matin à {digital}. Le prix convenu est {price} €. Le conducteur répète les informations pour obtenir une confirmation.'
            elif unit==4:
                turns=['Hello, I have arrived at the station, but I cannot see your car.',f'Hello. Please go to exit {gate}, on the ground floor. I am waiting in the authorised pick-up area.','I can see a café and a blue information sign. Am I in the right place?','Yes. The pick-up area is opposite the café, next to the blue sign. Please use the pedestrian crossing.','Thank you. Should I go upstairs or stay on this level?','Please stay on the ground floor. I will be beside the car and I will check your name when you arrive.']
                rows=[('Quelle sortie est indiquée ?',str(gate),str(gate+1),str(gate+2),'Exit désigne la sortie ; le numéro doit être confirmé.'),('Où se trouve le point de prise en charge par rapport au café ?','En face du café','À l’intérieur du café','À l’étage au-dessus du café','Opposite signifie en face de.'),('Quel chemin le client doit-il utiliser ?','Le passage piéton','Une traversée au milieu des voitures','Un accès interdit aux piétons','La consigne conserve un déplacement piéton sûr.')]
                translation=f'Le client doit rejoindre la sortie {gate} au rez-de-chaussée. Le véhicule est dans la zone autorisée en face du café, près du panneau bleu. Il faut utiliser le passage piéton.'
            elif unit==5:
                turns=['May I help you with your luggage?',f'Yes, please. We have {pax} large suitcases and one small bag. The small bag contains medicine.','Please keep the medicine with you. Are there any fragile items in the suitcases?','Yes. One suitcase contains a fragile gift. Please do not put heavy bags on top of it.','Thank you for telling me. I will check that everything can be stored safely before we leave.','That is perfect. Please ask me before folding my walking aid. I can show you how it works.']
                rows=[('Que doit garder le client avec lui ?','Le petit bagage contenant les médicaments','Tous les grands bagages sur ses genoux','Uniquement le ticket de parking','Le conducteur demande de garder les médicaments accessibles.'),('Quel bagage réclame une attention particulière ?','Celui qui contient le cadeau fragile','Un bagage décrit comme vide','Un bagage qui n’appartient pas au client','Fragile gift signifie cadeau fragile.'),('Que faire avant de plier l’aide à la mobilité ?','Demander et suivre les indications du passager','La plier sans prévenir','La laisser sur le trottoir','Le client propose de montrer le fonctionnement ; son accord est nécessaire.')]
                translation=f'Le groupe possède {pax} grandes valises et un petit sac contenant des médicaments. Un cadeau fragile doit être protégé. Le passager demande d’être consulté avant de plier son aide à la mobilité.'
            elif unit==6:
                turns=['Welcome on board. Could you fasten your seat belt, please?','Of course. Could you make the car a little cooler? It is quite warm today.','Certainly. I will adjust the air conditioning when it is safe to do so. Would you prefer a quiet journey?','Yes, please. I need to rest. Please let me know when we are close to the hotel.',f'Of course. The journey should take about {minutes} minutes, depending on traffic.','Thank you. I will keep my seat belt fastened. Please stop in a safe place if you need to check anything.']
                rows=[('Quelle température souhaite le passager ?','Plus fraîche','Plus chaude','Aucune climatisation obligatoire','Cooler signifie plus frais.'),('Quelle ambiance est souhaitée ?','Un trajet calme','Une musique très forte','Une conversation permanente','A quiet journey exprime une préférence pour le calme.'),('Quelle durée est estimée ?',f'Environ {minutes} minutes',f'Exactement {minutes+20} minutes garanties','Toujours moins de cinq minutes','About et depending on traffic indiquent une estimation.')]
                translation=f'Le conducteur rappelle la ceinture, propose d’ajuster la climatisation et respecte le souhait d’un trajet calme. Le temps estimé est d’environ {minutes} minutes selon la circulation.'
            elif unit==7:
                turns=[f'The usual route should take about {minutes} minutes, but there are roadworks today.','Is there another route? We would prefer to avoid arriving too late.',f'Yes. The toll road may save about ten minutes. The toll costs {5+v} euros and is not included in the original fare.','Thank you for explaining. We agree to use the toll road and pay the additional toll.','I will use the authorised route. If traffic changes, I will update you when it is safe to do so.','That is fine. Please do not take any risks to make up time.']
                rows=[('Pourquoi le trajet habituel est-il perturbé ?','Des travaux routiers','Une panne annoncée du véhicule','Un oubli de réservation','Roadworks signifie travaux routiers.'),('Quel coût supplémentaire est annoncé ?',f'{5+v} €',f'{15+v} €','Aucun, tout est inclus','Le péage est annoncé comme non inclus dans le prix initial.'),('Quelle limite rappelle le client ?','Ne pas prendre de risques pour gagner du temps','Dépasser les vitesses pour arriver plus tôt','Téléphoner en conduisant pour obtenir des raccourcis','Le gain de temps ne prime pas sur la sécurité.')]
                translation=f'Des travaux affectent le trajet de {minutes} minutes. Le péage coûte {5+v} € en plus et pourrait faire gagner dix minutes. Le client accepte cette option et demande de préserver la sécurité.'
            elif unit==8:
                turns=[f'The agreed fare for this transfer is {price} euros. It includes the journey to {hotel}.','Does that include waiting time and an extra stop?',f'It includes ten minutes of waiting. An additional stop would cost {10+v*5} euros if we agree to it before changing the journey.','I understand. We would like one extra stop at the pharmacy, please.',f'Let me check the route and confirm the new total: {price+10+v*5} euros, with the extra stop included.','Yes, that is acceptable. Thank you for explaining the price before we leave.']
                rows=[('Quelle attente est incluse ?','Dix minutes','Trente minutes','Une durée illimitée','Le conducteur annonce ten minutes of waiting.'),('Quel nouveau total est accepté ?',f'{price+10+v*5} €',f'{price} €',f'{price+30+v*5} €','Le total inclut le supplément convenu pour l’arrêt à la pharmacie.'),('À quel moment l’accord est-il recherché ?','Avant de modifier la prestation','Seulement après le paiement','Jamais, le conducteur décide seul','The agreement is obtained before changing the journey.')]
                translation=f'Le transfert initial coûte {price} € et inclut dix minutes d’attente. L’arrêt supplémentaire à la pharmacie coûte {10+v*5} € ; le nouveau total convenu est {price+10+v*5} €.'
            elif unit==9:
                turns=[f'Hello, I am sorry, but I am running about {late} minutes late because of an unexpected road closure.','Thank you for letting me know. We are still at the hotel reception.',f'I expect to arrive in about {late} minutes. Would you like me to contact the office to check an alternative vehicle?','Please check with your office. Our appointment is important, and we would like the most reliable option.','I will contact the office from a safe place and update you with a confirmed solution.','Thank you. Please use the same pick-up point unless we agree on a change.']
                rows=[('Quelle cause du retard est donnée ?','Une fermeture de route imprévue','Une facture oubliée','Le mauvais nom du client','Road closure indique une fermeture de route.'),('Quel retard est estimé ?',f'Environ {late} minutes',f'Exactement {late+30} minutes','Aucun retard','About exprime une estimation et non une garantie.'),('Quelle solution doit être vérifiée ?','Un véhicule de remplacement avec le bureau','Un départ sans conducteur','Une annulation décidée sans prévenir','Le client souhaite que le bureau vérifie une alternative fiable.')]
                translation=f'Une fermeture imprévue crée environ {late} minutes de retard. Le client reste à la réception. Le chauffeur doit vérifier un véhicule alternatif avec le bureau et confirmer la solution.'
            elif unit==10:
                turns=[f'The total fare is {price} euros. Would you like to pay by card or in cash?','By card, please. Could I also have a receipt and an invoice for my company?','Of course. Please wait while I check that the payment has been confirmed.','The terminal screen has changed. Should I try the card again?','Not yet. I will check the status first so that you are not charged twice. Then I will arrange the documents.','Thank you. I will give you the company details needed for the invoice through the agreed secure channel.']
                rows=[('Quel moyen de paiement est choisi ?','La carte','Les espèces','Un chèque annoncé','By card signifie par carte.'),('Pourquoi ne pas retenter immédiatement le paiement ?','Pour éviter un double débit avant vérification','Pour doubler volontairement le prix','Parce que toute carte est interdite','Le statut doit être contrôlé avant une nouvelle tentative.'),('Quels documents sont demandés ?','Un reçu et une facture à l’entreprise','Un passeport et un billet de train','Une attestation médicale','Receipt et invoice ont des fonctions différentes.')]
                translation=f'Le passager paie {price} € par carte et demande un reçu ainsi qu’une facture pour son entreprise. Le conducteur vérifie la confirmation avant toute seconde tentative pour éviter un double débit.'
            elif unit==11:
                turns=['Hello, I think I left my phone in your car after the transfer.','I am sorry to hear that. Could you confirm the booking name and the time of the journey?',f'The booking was under {name}. We arrived at {hotel} this morning.','Thank you. I will check the vehicle when I am safely parked and contact the office to arrange the next step.','If you find it, could you leave it with a stranger outside the hotel?','For security reasons, I will arrange a verified handover through the office. I cannot promise a refund or delivery until the details are checked.']
                rows=[('Quel problème est signalé ?','Un téléphone oublié','Une réservation inexistante','Une valise déjà remboursée','Left my phone indique que le client pense avoir oublié son téléphone.'),('Quand le véhicule sera-t-il vérifié ?','Une fois stationné en sécurité','Pendant une manœuvre','En arrêtant brutalement la circulation','The driver will check when safely parked.'),('Comment la remise doit-elle être organisée ?','Avec une vérification par le bureau','À n’importe quel inconnu','En publiant le numéro du téléphone retrouvé','La remise doit être sécurisée et liée au bon client.')]
                translation=f'Un téléphone aurait été oublié après le trajet de {name} vers {hotel}. Le conducteur vérifiera à l’arrêt et organisera une remise vérifiée avec le bureau, sans promesse non confirmée.'
            else:
                landmarks=[('old town','harbour','La vieille ville et le port'),('public garden','market square','Le jardin public et la place du marché'),('castle','riverside walk','Le château et la promenade au bord de la rivière'),('art gallery','historic centre','La galerie d’art et le centre historique')][v]
                turns=['Could you recommend something to visit near our hotel?',f'The {landmarks[0]} and the {landmarks[1]} are popular places to explore. You can walk between them using the pedestrian route.','Is the small museum open this afternoon?','I am not sure about today’s opening hours. I can check an official source when we stop, rather than give you an uncertain time.','Thank you. Do we need to book a restaurant as well?','A booking may be useful, but availability changes. I can help you find the contact details once the car is safely parked.']
                rows=[('Quels lieux sont proposés ?',landmarks[2],'Un aéroport et un parking privé','Une usine fermée et une autoroute',f'Les lieux indiqués sont : {landmarks[2].lower()}.'),('Que dit le chauffeur des horaires du musée ?','Il doit les vérifier','Il garantit l’ouverture toute la nuit','Le musée est certainement fermé','I am not sure exprime une incertitude honnête.'),('Quand propose-t-il de chercher les informations ?','Une fois le véhicule stationné en sécurité','Pendant un virage','Sans regarder la route','Le service touristique reste compatible avec la sécurité de conduite.')]
                translation=f'Le conducteur propose {landmarks[2].lower()}. Il ne connaît pas les horaires du musée ni la disponibilité du restaurant et propose une vérification une fois stationné.'
            did=f'{ref.lower().replace(".","-")}-{v+1}'
            dialogue={'id':did,'ref':ref,'turns':[{'speaker':'Driver' if i%2==0 else 'Passenger','text':text,'voice':'en-GB-RyanNeural' if i%2==0 else 'en-GB-SoniaNeural'} for i,text in enumerate(turns)],'translation':translation}
            # Speaker roles in the request-first conversations are reflected in the transcript.
            if unit in [4,11,12]:
                for i,turn in enumerate(dialogue['turns']):
                    turn['speaker']='Passenger' if i%2==0 else 'Driver'
                    turn['voice']='en-GB-SoniaNeural' if i%2==0 else 'en-GB-RyanNeural'
            dialogues.append(dialogue)
            for prompt,good,b1,b2,why in rows:
                practices[ref].append(q(ref,'Les personnes, lieux, prix et horaires de ce dialogue sont fictifs. Écoutez avant de consulter la transcription.',prompt,good,b1,b2,why,
                  stage=stage,audio=f'media/vtc/v3/audio/{did}.mp3',transcript=[{'speaker':t['speaker'],'text':t['text']} for t in dialogue['turns']],translation=translation))
        words=[line.split('|') for line in vocab]
        for i,(english,french) in enumerate(words):
            practices[ref].append(q(ref,'Retrouvez le sens dans le contexte professionnel de cette leçon.',f'Que signifie « {english} » dans ce contexte ?',french,words[(i+1)%len(words)][1],words[(i+2)%len(words)][1],f'« {english} » signifie ici « {french} ». Relisez la phrase entière pour conserver le bon sens.',stage='Vocabulaire en contexte'))
        practices[ref].append(order(ref,'Vous ne comprenez pas une information essentielle dans une conversation avec le client.',[
          'Signaler poliment que vous n’avez pas compris.','Demander de répéter ou de parler plus lentement.','Reformuler l’information comprise.','Obtenir la confirmation avant d’agir.']))
    return topics,practices,dialogues
