"""Reading, grammar and professional response choices; no free-text field."""
from .common import question as q, sorting, order, topic

INFO=[
('D.01','Lire pour résoudre une question','Une lecture efficace commence par le but : retrouver une heure, comprendre une consigne, expliquer une cause ou identifier une condition. Lisez la question avant de chercher l’information, puis revenez au passage qui la justifie. Le titre donne le thème général, mais ne suffit pas à répondre à une question précise.','Les mots tous, certains, uniquement, avant, après et sauf peuvent changer la portée d’une phrase. Une réponse plausible dans la vie courante peut être fausse si le texte dit autre chose. Dans les activités, choisissez la proposition appuyée par le document, sans ajouter une information extérieure.'),
('D.02','Extraire une information sans la déformer','Séparez les dates, les heures, les lieux et les personnes. Deux versions d’un message peuvent se corriger : repérez la plus récente et ce qu’elle modifie exactement. Un changement d’heure n’implique pas automatiquement un changement d’adresse. La formulation finale doit conserver l’unité et le contexte.','Pour un nombre, vérifiez ce qu’il compte : passagers, bagages, véhicules ou euros. Un total de quatre places peut inclure le conducteur alors que quatre passagers ne l’incluent pas. La recherche d’information doit conserver le sens du nombre, pas seulement ses chiffres.'),
('D.03','Distinguer un fait, un propos et une interprétation','Un fait observable décrit ce qui a été constaté : heure relevée, message reçu, document affiché. Un propos rapporté indique ce qu’une personne dit. Une interprétation propose une explication qui n’est pas nécessairement prouvée. Ces catégories peuvent coexister dans un même récit.','« Le client dit avoir réservé hier » ne prouve pas à lui seul l’heure d’enregistrement. « Le client est de mauvaise foi » est une appréciation. Dans un compte rendu, la précision consiste à attribuer les propos à leur auteur et à ne pas transformer une hypothèse en certitude.'),
('D.04','Retrouver ce que remplacent les pronoms','Les pronoms évitent les répétitions, mais leur référence doit être claire. Il, elle, ils, leur, celui-ci ou celle-ci peuvent renvoyer à des personnes ou à des objets différents selon la phrase. Relisez la phrase précédente et vérifiez le nombre, le genre et le sens de l’action.','Quand plusieurs antécédents sont possibles, une formulation professionnelle gagne à répéter un nom. « Elle la lui transmet » peut devenir difficile à suivre. « La réception transmet la réservation au chauffeur » nomme directement les rôles sans demander au lecteur de deviner.'),
('D.05','Reconnaître la relation entre deux idées','Parce que introduit une cause ; donc une conséquence ; mais une opposition ; afin de un objectif ; pourtant un contraste avec ce qui était attendu. Le connecteur ne sert pas seulement à relier deux phrases : il précise le raisonnement.','Dans une consigne, distinguez aussi une condition et une chronologie. « Si le client confirme » ne signifie pas qu’il a déjà confirmé. « Après confirmation » impose une étape préalable. Repérer ces relations aide à sélectionner la bonne action dans l’ordre prévu.'),
('D.06','Lire les nuances et le degré de certitude','Les verbes et les adverbes modifient l’engagement. Peut indique une possibilité ; doit une obligation dans le contexte ; devrait peut exprimer une prévision ou un conseil. Environ, probablement et sous réserve signalent une marge ou une condition. Ne les remplacez pas par une certitude dans votre réponse.','Une phrase négative mérite une lecture complète : « aucun supplément sauf attente prévue » n’a pas le même sens que « aucun supplément dans tous les cas ». Les mots au moins et au plus fixent des bornes opposées. Dans les exercices, la bonne réponse respecte la portée exacte du texte.'),
('D.07','Choisir le mot utile au métier','Le vocabulaire professionnel gagne à rester simple et précis. Une réservation, un devis, une facture, un reçu, un acompte et un remboursement décrivent des étapes différentes. Un mot voisin n’est pas toujours interchangeable. Recherchez ce que le document ou l’action accomplit réellement.','Un mot peut avoir plusieurs sens selon le contexte. Une « correspondance » peut être une liaison entre transports ou un échange écrit. Pour choisir, lisez les mots voisins et le but de la phrase. Le vocabulaire s’apprend dans une situation, pas uniquement comme une liste isolée.'),
('D.08','Situer une action dans le temps','Le présent décrit souvent une situation actuelle ou une habitude ; le passé composé un événement accompli ; l’imparfait un contexte ou une habitude passée ; le futur une action annoncée. Un message professionnel doit permettre de savoir si l’action est faite, en cours ou prévue.','Le conditionnel peut présenter une hypothèse ou une demande courtoise. Une phrase au futur ne prouve pas que l’action est déjà accomplie. Dans une chronologie de réservation, distinguez « j’ai confirmé », « je confirme » et « je confirmerai après vérification ».'),
('D.09','Repérer les accords et les homophones utiles','Le verbe s’accorde avec son sujet. Dans un groupe nominal, déterminant, nom et adjectif doivent rester cohérents. Les homophones a/à, et/est, son/sont ou ce/se se choisissent selon leur fonction, pas selon leur son. Une substitution mentale peut aider : a peut souvent être remplacé par avait.','Une erreur d’accord ne crée pas toujours une incompréhension, mais une confusion d’heure, de nombre ou de négation peut changer la consigne. Relisez d’abord le sens, puis la forme. Les activités proposent des formulations à sélectionner et à corriger par choix, sans texte à produire.'),
('D.10','Répondre précisément et brièvement','Une réponse courte doit fournir l’information demandée, avec l’unité ou la condition nécessaire. Une question commençant par pourquoi attend une cause ; combien attend une quantité ; quand attend un moment. Reprendre toute l’histoire n’améliore pas une réponse qui oublie l’élément utile.','La plateforme vous fait choisir entre plusieurs formulations. Cet entraînement travaille la compréhension et la précision. Il ne reproduit pas le geste d’écriture des questions à réponse courte de l’examen officiel : il vous aide à reconnaître ce qu’une réponse pertinente doit contenir.'),
('D.11','Choisir un message professionnel compréhensible','Un message au client doit rendre visibles l’objet, l’information utile et l’action attendue. La politesse accompagne une réponse concrète ; elle ne remplace pas l’heure ou le lieu de rendez-vous. Évitez les reproches, les sous-entendus et les phrases longues qui mélangent plusieurs demandes.','En cas de retard ou de modification, distinguez ce qui est confirmé et ce qui reste à vérifier. Proposez une prochaine étape réaliste. Une formule comme « je vous confirme une solution dès validation » n’a pas la même portée que « un véhicule arrive dans cinq minutes » sans confirmation.'),
('D.12','Organiser sa lecture en situation d’évaluation','Commencez par repérer le thème, les interlocuteurs et la chronologie. Pour chaque question, cherchez l’indice dans le texte et éliminez les propositions qui ajoutent, inversent ou exagèrent une information. Les distracteurs peuvent reprendre les mêmes mots tout en modifiant la relation logique.','Conservez du temps pour une relecture des réponses sensibles : dates, négations, conditions et personnes. Si une question vous bloque, utilisez une méthode de retour prévue dans votre entraînement. Le bilan vous indique les notions à revoir afin d’améliorer la méthode, pas seulement le nombre de réponses mémorisées.'),
]

def build():
    topics={};practices={}
    for ref,title,p1,p2 in INFO:
        topics[ref]=topic(title,[p1,p2],
          'Message : « Le départ est maintenu à 8 h. La réception demande seulement de remplacer la sortie principale par la sortie côté jardin. Merci de confirmer ce point au passager. » La modification porte sur le lieu ; l’heure reste 8 h. Une réponse qui décale aussi l’heure ajouterait une information absente.',
          ['Identifier la question et les mots qui la précisent.','Retrouver dans le texte l’information qui justifie la réponse.','Vérifier que la formulation ne change ni la personne, ni la date, ni la condition.'],
          'Une réponse vraisemblable mais non justifiée par le texte peut être incorrecte.')
        practices[ref]=[]
    for n in range(8):
        hour=8+n;count=2+n%3;gate=2+n%4;oldgate=gate+1;price=70+n*5;late=10+n*2
        text=(f'La réception de l’hôtel contacte l’entreprise pour confirmer le transfert du lendemain. Le message initial prévoyait une prise en charge à {hour} h, à la sortie {oldgate}. '
         f'Dans son dernier message, reçu à 17 h, la réception maintient l’heure mais demande au chauffeur de rejoindre la sortie {gate}, côté jardin. Le groupe comprend {count} passagers et deux grandes valises. '
         f'Le prix convenu est {price} euros pour le trajet direct. Un arrêt supplémentaire n’est pas compris et devra être confirmé avec l’entreprise avant toute modification. '
         f'Le chauffeur vérifie le véhicule et estime le trajet à trente minutes dans les conditions annoncées. Il prévoit quinze minutes de marge avant l’heure du rendez-vous à destination. '
         f'Le client indique qu’un train pourrait avoir jusqu’à {late} minutes de retard, sans que ce retard soit encore confirmé. La réception demande d’attendre une information définitive avant de changer l’horaire. '
         'Le conducteur doit donc conserver les conditions confirmées, se tenir prêt à actualiser le dossier et signaler toute difficulté réelle. Il ne doit ni inventer un nouvel horaire ni garantir une arrivée indépendamment de la circulation.')
        doc=[{'title':f'Dossier de lecture {n+1} · transfert hôtelier','text':text}]
        def add(ref,prompt,good,b1,b2,why):practices[ref].append(q(ref,'Lisez le dossier, puis choisissez la réponse justifiée par le texte.',prompt,good,b1,b2,why,documents=doc,stage=f'Lecture {n+1} · informations et nuances'))
        add('D.01','Quel est l’objectif principal du dernier message ?','Modifier le lieu en maintenant l’heure','Annuler toute la mission','Ajouter automatiquement un arrêt','Le message maintient l’heure et change uniquement la sortie de prise en charge.')
        add('D.02','Quel lieu de prise en charge est confirmé en dernier ?',f'Sortie {gate}, côté jardin',f'Sortie {oldgate}',f'Quai {hour}','La version la plus récente modifie précisément le lieu.')
        add('D.02','Combien de passagers sont annoncés ?',str(count),str(count+2),str(count+1),'Le texte distingue les passagers et les deux valises.')
        add('D.03','Quel élément reste une possibilité non confirmée ?',f'Un retard du train pouvant atteindre {late} minutes',f'Le prix de {price} euros',f'Le groupe de {count} passagers','Pourrait exprime une possibilité ; le texte précise que le retard n’est pas confirmé.')
        add('D.06','Comment comprendre « pourrait avoir jusqu’à … minutes de retard » ?','Un retard possible, dont la durée indiquée est une borne dans le message','Un retard certain et exactement égal au nombre donné','Une annulation déjà décidée','Pourrait et jusqu’à ne doivent pas être remplacés par une certitude exacte.')
        add('D.10','À la question « À quelle heure la prise en charge reste-t-elle prévue ? », quelle réponse est la plus précise ?',f'À {hour} h, l’heure ayant été maintenue','Le client pourrait être en retard','Au côté jardin','La question porte sur l’heure, pas sur le lieu ou une hypothèse de retard.')
        add('D.11','Quel message reprend correctement la situation ? ',f'Nous confirmons votre prise en charge à {hour} h, sortie {gate} côté jardin. Nous vous informerons si une modification est confirmée.',f'Votre prise en charge est automatiquement reportée de {late} minutes.',f'Nous garantissons votre arrivée quelles que soient les conditions.','Le message conserve les informations confirmées et distingue un éventuel changement.')
        add('D.12','Quelle modification nécessite un nouvel accord ?','Un arrêt supplémentaire','Le maintien de l’heure initiale','La présence des deux valises déjà annoncées','Le texte prévoit un accord préalable pour un arrêt non compris.')
        add('D.12','Que signifie l’estimation de trente minutes ?','Une durée prévue selon les conditions annoncées','Une garantie absolue indépendante du trafic','Le nombre de minutes d’attente incluses','Le texte limite explicitement la portée de l’estimation.')
    pronouns=[
     ('La réception remet le bon au chauffeur. Celui-ci le vérifie avant de partir.','À qui renvoie « celui-ci » ?','Au chauffeur','À la réception','Au bon','Le pronom masculin désigne ici le chauffeur qui vérifie le document.'),
     ('Le client reçoit la facture. Il la transmet à son service comptable.','Que remplace « la » ?','La facture','Le client','Le service comptable','La est le complément représentant la facture transmise.'),
     ('Les voyageurs attendent le chauffeur. Il leur indique le point de rendez-vous.','À qui renvoie « leur » ?','Aux voyageurs','Au chauffeur seul','Au point de rendez-vous','Le renseignement est donné aux voyageurs.'),
     ('La voiture du chauffeur est prête. Elle se trouve au parking couvert.','Que désigne « elle » ?','La voiture','Le chauffeur','Le parking','Le pronom féminin reprend la voiture.'),
     ('Les deux bagages sont rangés. Ils ne gênent plus le passage.','Que désigne « ils » ?','Les deux bagages','Les deux passagers non mentionnés','Les documents de réservation','Le pronom reprend le groupe nominal qui précède.'),
     ('Le devis et le reçu sont envoyés. Ce dernier confirme le paiement.','Que signifie « ce dernier » ?','Le reçu','Le devis','L’entreprise','Le dernier élément nommé est le reçu.'),
     ('La cliente remercie la conductrice pour son aide. Celle-ci reprend ensuite le volant.','Qui reprend le volant ?','La conductrice','La cliente','Une personne non identifiée','Le sens de l’action et le contexte renvoient à la conductrice.'),
     ('Le bureau appelle les conducteurs et leur transmet la nouvelle adresse.','Qui reçoit la nouvelle adresse ?','Les conducteurs','Le bureau lui-même','Les passants','Le pronom leur désigne les destinataires pluriels nommés.')]
    for context,prompt,g,b1,b2,why in pronouns:practices['D.04'].append(q('D.04',context,prompt,g,b1,b2,why))
    links=[
     ('Le chauffeur part plus tôt parce que des travaux ralentissent le trajet.','Une cause','Une opposition','Une comparaison','Parce que introduit la raison du départ anticipé.'),
     ('La route est fermée, donc nous prenons une autre voie.','Une conséquence','Une hypothèse sans lien','Une description du passé','Donc relie la fermeture à la décision qui en découle.'),
     ('Le trajet est plus court, mais il comporte un péage.','Une opposition ou un contraste','Une identité complète','Un ordre chronologique','Mais oppose deux éléments à prendre en compte.'),
     ('Le chauffeur vérifie l’adresse afin de limiter le risque d’erreur.','Un objectif','Une conséquence déjà réalisée','Une comparaison de prix','Afin de exprime le but de la vérification.'),
     ('Si le client confirme l’arrêt, le devis sera mis à jour.','Une condition','Un arrêt déjà confirmé','Une annulation certaine','Si introduit une condition qui n’est pas présentée comme accomplie.'),
     ('Après confirmation, le bureau envoie le bon au conducteur.','Un ordre chronologique','Une opposition','Une certitude sur une confirmation déjà reçue','Après impose l’antériorité de la confirmation, sans prouver qu’elle a eu lieu.'),
     ('Le chauffeur avait prévu une marge ; pourtant, un incident exceptionnel a créé un retard.','Un contraste avec ce qui était attendu','Une addition sans contraste','Une obligation légale nouvelle','Pourtant souligne que le résultat diffère de l’attente.'),
     ('Le client choisit soit le trajet direct, soit la prestation avec arrêt.','Une alternative','Une addition obligatoire des deux','Une conséquence','Soit… soit présente des options.')]
    for text,g,b1,b2,why in links:practices['D.05'].append(q('D.05',text,'Quelle relation le connecteur exprime-t-il ?',g,b1,b2,why))
    nuances=[
     ('La prise en charge aura lieu au plus tard à 9 h.','9 h constitue l’heure limite annoncée','Elle aura obligatoirement lieu après 9 h','Elle aura toujours exactement lieu à 9 h','Au plus tard fixe une limite supérieure.'),
     ('Prévoyez au moins quinze minutes de marge.','La marge doit être de quinze minutes ou davantage','La marge ne doit jamais dépasser quinze minutes','La marge doit être nulle','Au moins indique un minimum.'),
     ('Le parking est accessible uniquement sur réservation.','La réservation est une condition d’accès','Il est accessible sans condition','Il est toujours fermé','Uniquement restreint les conditions d’accès.'),
     ('Aucun arrêt supplémentaire n’est inclus.','Les arrêts supplémentaires ne font pas partie de l’offre annoncée','Tous les arrêts sont gratuits','Le trajet est annulé','La négation porte sur les arrêts supplémentaires, pas sur toute la prestation.'),
     ('Le véhicule devrait arriver vers 10 h.','Il s’agit d’une prévision approximative','L’arrivée exacte est garantie','Le véhicule est déjà arrivé','Devrait et vers expriment ici une estimation.'),
     ('La modification sera possible sous réserve de disponibilité.','Elle dépend d’une disponibilité à vérifier','Elle est déjà confirmée sans condition','Elle est définitivement impossible','Sous réserve introduit une condition.')]
    for text,g,b1,b2,why in nuances:practices['D.06'].append(q('D.06',text,'Quelle reformulation conserve exactement le sens ?',g,b1,b2,why))
    vocab=[('devis','proposition détaillée de prestation et de prix'),('réservation','commande préalable d’un service'),('facture','document décrivant une opération et le montant dû'),('reçu','document attestant un paiement'),('acompte','paiement partiel prévu avant le règlement du solde'),('solde','montant restant à régler dans ce contexte'),('remboursement','restitution d’une somme'),('échéance','date à laquelle une action ou un paiement doit intervenir'),('réclamation','demande liée à un problème rencontré'),('itinéraire','parcours retenu pour rejoindre une destination'),('approche','déplacement pour rejoindre le point de prise en charge'),('estimation','évaluation qui ne constitue pas nécessairement une valeur certaine')]
    for i,(word,meaning) in enumerate(vocab):practices['D.07'].append(q('D.07','Vocabulaire du dossier professionnel.',f'Quel sens convient à « {word} » ?',meaning,vocab[(i+1)%len(vocab)][1],vocab[(i+3)%len(vocab)][1],f'Dans ce contexte, {word} désigne : {meaning}.'))
    tense=[
      ('Hier, le bureau … la réservation.','a confirmé','confirmera','confirme demain','Hier situe une action passée accomplie : a confirmé.'),
      ('Demain, nous … le nouveau lieu au client.','communiquerons','avons communiqué hier','communiquions autrefois','Demain appelle ici le futur.'),
      ('Chaque matin, le conducteur … son véhicule.','vérifie','vérifier hier','vérifierait hier','Le présent décrit une habitude actuelle.'),
      ('Pendant que le client attendait, le chauffeur … le bon.','consultait','consultera demain','consulter','L’imparfait décrit une action en cours dans le contexte passé.'),
      ('Pourriez-vous … l’adresse complète ?','confirmer','confirmez','confirmé','Après pourriez-vous, l’infinitif confirmer convient.'),
      ('Si la disponibilité est confirmée, nous … le changement.','validerons','avions validé avant-hier','valider','La conséquence future est ici exprimée par validerons.'),
      ('Le paiement a été reçu.','Le règlement est présenté comme accompli','Le règlement est seulement envisagé','Le règlement est impossible','Le passé composé passif décrit une réception accomplie.'),
      ('Je vérifierai le dossier après mon arrivée.','La vérification est annoncée pour plus tard','La vérification est déjà terminée','Aucun dossier ne sera vérifié','Le futur ne signifie pas que la tâche est déjà faite.')]
    for i,(text,g,b1,b2,why) in enumerate(tense):practices['D.08'].append(q('D.08',text,'Choisissez la formulation ou l’interprétation correcte.',g,b1,b2,why))
    spelling=[
      ('Le conducteur … confirmé l’adresse.','a','à','as','A est ici le verbe avoir ; on peut tester avec avait.'),
      ('Le rendez-vous est fixé … huit heures.','à','a','as','À est une préposition qui introduit ici l’heure.'),
      ('Le véhicule … prêt pour le départ.','est','et','es','Est exprime l’état du véhicule.'),
      ('Le chauffeur … le passager vérifient le lieu.','et','est','es','Et relie deux personnes.'),
      ('Les deux factures … disponibles.','sont','son','sons','Sont est le verbe être au pluriel.'),
      ('Le client retrouve … bagage.','son','sont','sons','Son est un déterminant possessif devant bagage.'),
      ('Les réservations sont … .','confirmées','confirmée','confirmés','Réservations est féminin pluriel.'),
      ('Les véhicules sont … .','propres','propre','proprement','L’adjectif s’accorde avec véhicules au pluriel.'),
      ('Les clients … à la réception.','attendent','attend','attends','Le sujet clients est à la troisième personne du pluriel.'),
      ('Nous vous … le nouveau lieu.','confirmons','confirme','confirmez','Le sujet nous appelle confirmons.'),
      ('La conductrice … prépare avant le départ.','se','ce','ses','Se accompagne ici le verbe pronominal se préparer.'),
      ('… document concerne la course de demain.','Ce','Se','Ses','Ce désigne le document au singulier.')]
    for text,g,b1,b2,why in spelling:practices['D.09'].append(q('D.09',text,'Sélectionnez le mot correctement écrit.',g,b1,b2,why))
    facts=[('Le message porte l’heure 17 h 05.',0),('Le client affirme avoir appelé le matin.',1),('Le client cherche certainement à tromper le chauffeur.',2),('La facture affiche un total de 90 €.',0),('La réception dit que le vol est retardé.',1),('Le conducteur est forcément responsable parce qu’il était présent.',2),('Le journal de réservation comporte deux horaires différents.',0),('Le chauffeur pense que l’autre véhicule allait trop vite sans pouvoir l’établir.',2)]
    practices['D.03'].append(sorting('D.03','Classez les éléments du récit.','Le dossier distingue ce qui est observé, ce qui est rapporté par une personne et ce qui est interprété.',
        ['Fait décrit comme observable','Propos attribué à une personne','Interprétation ou supposition'],facts,
        'L’attribution des propos et l’indication de l’incertitude évitent de transformer une hypothèse en fait.'))
    for ref in practices:
        practices[ref].append(order(ref,'Retrouvez la méthode de lecture avant de choisir une réponse.',[
         'Lire la question et identifier l’information recherchée.','Retrouver les passages utiles dans le document.','Comparer les propositions au sens exact du texte.','Vérifier les dates, les personnes et les conditions avant de valider.']))
    return topics,practices
