"""Contextual legal practice. Fictional dossiers, reviewed 6 October 2026."""
from .common import question as q, sorting, order, topic

DATA = {
'A.01':('Qualifier le service à partir des faits',
 'Pour reconnaître un transport, partez du besoin qui a créé le trajet. Le conducteur se déplace-t-il pour son propre compte ou parce qu’un client commande un service ? Qui choisit l’heure et la destination ? Qui rémunère la prestation ? Le nom affiché dans une application n’est pas décisif. Une réservation par téléphone peut concerner un VTC ; elle ne transforme pas le trajet en service public collectif à la demande. La taille du groupe ne suffit pas non plus à déterminer le cadre juridique.',
 'Séparez ensuite la qualification du service et les conditions dans lesquelles il peut être réalisé. Une course peut relever du VTC et rester impossible à accepter si la réservation préalable, le conducteur ou le véhicule ne répond pas aux exigences. Deux vérifications sont donc nécessaires : identifier l’activité puis contrôler son autorisation. Garder cette distinction évite de conclure trop vite qu’un transport devient légal parce qu’on lui a donné le bon nom.',
 'Un particulier allait déjà de Fréjus à Toulon pour une démarche personnelle et partage ses frais. Un professionnel attend à Fréjus que des clients lui commandent Toulon contre un prix commercial. La destination est identique ; la raison du déplacement et son organisation diffèrent.',
 ['Identifier le motif réel du déplacement et le demandeur.','Distinguer partage de frais et rémunération d’un service.','Vérifier le cadre correspondant avant d’accepter.'],
 'Le mot « covoiturage » ne change pas la nature d’un déplacement créé pour transporter des clients payants.',
 [
 ('Un hôtel réserve la veille un transport dédié pour deux clients. Le conducteur n’avait aucun déplacement personnel prévu.','Comment analyser la prestation ?','Un transport professionnel organisé pour les clients','Un covoiturage parce qu’il reste des places','Un transport privé parce que l’hôtel a réservé','Le déplacement est créé pour répondre à la commande. Les places libres ne le transforment pas en covoiturage.'),
 ('Un chauffeur veut vendre des places à des départs et arrêts fixes chaque matin, sans étudier le régime du service.','Quelle vérification manque ?','Le régime applicable à cette organisation du transport','La couleur de la voiture uniquement','L’accord de chaque client suffit à tout autoriser','Une organisation régulière de transport ne se qualifie pas automatiquement de VTC. Les autorisations adaptées doivent être étudiées avant la vente.'),
 ('Trois passagers hèlent un VTC au sortir d’un congrès. Le chauffeur affiche « partage de frais ».','Quelle réponse est correcte ?','Le changement d’étiquette ne remplace pas les conditions du VTC','Une participation en espèces rend le trajet privé','Trois passagers permettent toujours de partir sans réservation','Ce sont les faits qui déterminent l’activité : on ne peut pas masquer une prestation commerciale par une appellation.'),
 ('Une commune organise un service collectif déclenché sur réservation.','Quel raisonnement éviter ?','Conclure que toute réservation est nécessairement une course VTC','Chercher qui organise le service','Lire le contrat et les règles du dispositif','La réservation existe dans plusieurs régimes. Il faut examiner l’organisation et les autorisations.')]),
'A.02':('Séparer les quatre dossiers professionnels',
 'Un indépendant peut cumuler les fonctions de conducteur et d’exploitant, mais les preuves restent distinctes. Le permis et la carte professionnelle se rattachent à une personne. Les formalités d’entreprise et le REVTC se rattachent à l’exploitant. Les caractéristiques techniques et les garanties d’usage concernent le véhicule. La réservation décrit une mission. Une anomalie dans un seul de ces dossiers peut empêcher le départ même si les trois autres sont à jour.',
 'Pour résoudre un problème, choisissez l’interlocuteur qui détient la décision. La plateforme peut corriger une commande ou expliquer sa commission, mais ne délivre pas la carte professionnelle. La CMA organise l’examen ; la préfecture traite le titre professionnel ; l’assureur précise les garanties du contrat. Cette répartition permet de demander une preuve précise et d’éviter les confirmations verbales trop générales.',
 'Nadia a une carte valide et devient salariée d’une société. Elle ne demande pas une nouvelle carte au nom de la société pour cette seule raison ; l’entreprise doit en revanche vérifier sa situation et organiser ses propres obligations d’exploitant.',
 ['Classer la pièce : personne, entreprise, véhicule ou mission.','Identifier l’autorité ou le partenaire compétent.','Vérifier la pièce reçue et son champ d’application.'],
 'Un compte actif sur une plateforme ne vaut pas autorisation administrative générale.',
 [
 ('La plateforme affiche « compte validé », mais le dossier REVTC de la nouvelle entreprise n’est pas finalisé.','Peut-on considérer l’entreprise prête ?','Non, l’inscription de l’exploitant reste à vérifier','Oui, la plateforme remplace le registre','Oui, si le conducteur dispose d’un téléphone','Le contrôle commercial de la plateforme ne remplace pas l’inscription de l’exploitant.'),
 ('Un salarié présente la carte professionnelle de son dirigeant.','Quel est le défaut ?','Le conducteur doit disposer de sa propre carte','La carte est valable pour tous les salariés','Seule la carte de la voiture compte','La carte professionnelle est personnelle ; elle ne se prête pas.'),
 ('Un candidat veut s’inscrire aux épreuves VTC.','Quel interlocuteur est directement concerné ?','La CMA organisatrice de l’examen','Le garagiste chargé de l’entretien','La compagnie d’assurance du client','Il faut distinguer l’organisation de l’examen et les démarches ultérieures de carte ou de registre.'),
 ('Le contrat du véhicule ne précise pas le transport rémunéré de passagers.','À qui demander la confirmation utile ?','À l’assureur, sur la garantie et l’usage concernés','Au client, qui peut renoncer à toute assurance','À la plateforme, dont l’écran suffit','Une garantie doit être vérifiée auprès du professionnel qui couvre le risque.')]),
'A.03':('De la formation au droit d’exercer',
 'Le parcours d’accès comporte plusieurs décisions indépendantes. S’inscrire en formation signifie apprendre. Réussir l’admissibilité signifie avoir franchi la partie théorique. Réussir l’examen complet et obtenir la carte sont encore deux étapes à distinguer. Au moment de commencer l’activité, il faut également que les conditions personnelles restent remplies. Un dossier transmis ne vaut pas décision favorable.',
 'Vérifiez les dates des informations consultées. Depuis le 12 août 2026, la voie nationale fondée sur l’expérience antérieure a été supprimée pour les nouvelles demandes ; les demandes antérieures conservent leurs règles. La reconnaissance de certaines qualifications européennes constitue un autre cadre. Pour une situation particulière, utilisez la procédure officielle correspondant au dossier plutôt que d’appliquer une ancienne vidéo générale.',
 'Samir reçoit son résultat favorable en théorie. Il prévoit sa pratique et les démarches de carte. Il ne commence pas entre-temps à transporter des clients sur la seule base de son relevé de notes.',
 ['Vérifier les conditions personnelles et le régime du dossier.','Franchir les étapes d’examen et obtenir le titre requis.','Contrôler les conditions d’exercice avant la première mission.'],
 'Une attestation de formation, un dossier en cours et une carte professionnelle n’ont pas la même portée.',
 [
 ('Un candidat a réussi uniquement les épreuves théoriques.','Quelle est la suite normale ?','Préparer la pratique et poursuivre les démarches d’accès','Transporter des passagers immédiatement','Utiliser la carte d’un proche jusqu’au résultat','L’admissibilité est une étape, pas l’autorisation de commencer le métier.'),
 ('Une nouvelle demande est préparée en octobre 2026 sur la base d’une vidéo de 2024 vantant l’équivalence par expérience.','Que faire ?','Consulter les règles actualisées applicables à la nouvelle demande','Appliquer automatiquement la vidéo ancienne','Remplacer l’examen par une attestation personnelle','La réforme d’août 2026 impose de vérifier le régime actuel et les éventuelles situations particulières.'),
 ('Un candidat fait établir son aptitude par son médecin habituel sans vérifier son agrément.','Quel contrôle manque ?','L’habilitation du médecin pour ce contrôle','Le nombre de courses prévues','La marque du futur véhicule','Le contrôle doit être effectué par un médecin agréé dans le cadre prévu.'),
 ('Un interlocuteur résume l’honorabilité à « un casier totalement vierge dans tous les cas ».','Quelle formulation retenir ?','Certaines condamnations incompatibles sont recherchées selon les textes','Toute mention quelconque interdit toujours la profession','L’honorabilité n’a jamais à être vérifiée','Le contrôle porte sur le cadre et les condamnations incompatibles prévus, pas sur une formule approximative.')]),
'A.04':('Suivre une échéance jusqu’à son résultat',
 'Une date d’alerte, une date de dépôt et une date d’expiration correspondent à trois informations différentes. L’alerte permet de préparer la démarche ; le dépôt prouve son envoi ; l’expiration décrit la validité du justificatif. Un calendrier utile comporte aussi le titulaire, la procédure engagée, les pièces manquantes et l’état réel de la décision. Deux titres qui expirent à des dates différentes doivent être suivis séparément.',
 'La vérification ne se limite pas au renouvellement périodique. Une suspension de permis, une résiliation d’assurance ou un changement affectant l’aptitude exige une réaction immédiate. La prochaine mission déjà réservée ne crée pas de dérogation. Il faut prévenir l’exploitant, vérifier la situation et organiser une continuité de service conforme si nécessaire.',
 'La carte est encore valable huit mois, tandis que l’avis médical arrive à échéance le mois suivant. L’alerte médicale est prioritaire ; une carte à jour ne prolonge pas la validité de l’aptitude.',
 ['Lire chaque date et chaque restriction séparément.','Préparer la démarche auprès du bon interlocuteur.','Vérifier la décision avant de considérer l’anomalie levée.'],
 'Ne cochez pas « renouvelé » simplement parce qu’un formulaire a été envoyé.',
 [
 ('Carte valable jusqu’en juin 2027 ; avis médical à renouveler le 20 novembre 2026. Nous sommes le 6 octobre 2026.','Quelle démarche anticiper en premier ?','Le renouvellement médical','Attendre juin 2027 pour tout traiter','Supprimer l’échéance médicale du suivi','Les validités sont indépendantes ; l’échéance la plus proche doit être traitée à temps.'),
 ('Une demande de renouvellement vient d’être déposée sans décision reçue.','Quel statut inscrire ?','Déposé, décision à vérifier','Accordé automatiquement','Aucun suivi nécessaire','La preuve de dépôt ne doit pas être confondue avec l’issue de la démarche.'),
 ('Le permis est suspendu avant sa date d’expiration imprimée.','Quelle réaction retenir ?','Suspendre la conduite et traiter la situation','Se fier uniquement à la date imprimée','Conduire si le client accepte','Le droit réel peut cesser avant la date portée sur un document.'),
 ('L’assureur confirme une interruption de couverture du transport rémunéré.','Que faire des courses prévues ?','Organiser une solution conforme avant tout transport','Partir puis régulariser après','Demander au passager de signer une décharge','Une réservation ou une décharge du client ne remplace pas la couverture requise.')]),
'A.05':('Lire une garantie comme un périmètre',
 'Le mot « assuré » est insuffisant. Identifiez la personne ou l’entreprise couverte, le véhicule, l’activité déclarée, la période et les garanties. L’assurance automobile de circulation et la responsabilité civile professionnelle répondent à des objets différents. Une attestation personnelle pour usage privé ne prouve pas automatiquement la couverture d’un transport de passagers contre rémunération.',
 'En cas de dommage, séparez la mise en sécurité, le recueil des faits et le traitement contractuel. Conservez les éléments utiles sans transformer une première impression en aveu juridique définitif. Vérifiez les délais et la procédure de déclaration de votre contrat. Le montant d’une franchise, une exclusion ou le plafond d’indemnisation se lit dans les documents applicables ; il ne se devine pas à partir d’une publicité.',
 'Un bagage est endommagé au chargement. Le conducteur sécurise la situation, identifie la course et les faits, recueille les justificatifs utiles et prévient l’interlocuteur prévu par l’entreprise pour vérifier les garanties.',
 ['Identifier le risque et le contrat qui peut le couvrir.','Vérifier l’usage déclaré, les bénéficiaires et la validité.','Conserver les faits et suivre la procédure de déclaration.'],
 'Ne promettez pas une indemnisation précise avant l’examen du dossier et des garanties.',
 [
 ('Une voiture de remplacement n’apparaît pas dans les éléments de couverture disponibles.','Quelle action est prioritaire ?','Vérifier sa couverture pour la mission avant le départ','Copier le numéro de l’ancienne voiture','Considérer que tout véhicule loué est couvert pour tout usage','Le remplacement doit être cohérent avec les garanties et les formalités applicables.'),
 ('Un client réclame le remboursement intégral d’un objet sans fournir d’élément sur les faits.','Quelle réponse choisir ?','Recueillir les faits et ouvrir le traitement de la réclamation','Reconnaître immédiatement toutes les responsabilités','Refuser toute discussion sans examen','Le traitement repose sur des faits, des preuves et les garanties, pas sur une réaction automatique.'),
 ('Le conducteur possède uniquement une attestation automobile pour usage privé.','Quelle vérification reste nécessaire ?','La couverture de l’usage professionnel rémunéré','Le nombre de sièges chauffants','La note du conducteur dans l’application','L’activité réelle doit être déclarée et couverte.'),
 ('Une franchise est prévue au contrat.','Que signifie-t-elle dans le cadre de l’exercice ?','Une part du dommage peut rester à charge selon le contrat','L’assurance rembourse toujours tout sans limite','Le conducteur n’a plus d’obligation de déclaration','Les modalités exactes se lisent dans le contrat ; la franchise n’efface pas les autres conditions.')]),
'A.06':('Décider sur des critères de service et de sécurité',
 'Une décision professionnelle doit pouvoir s’expliquer par des faits pertinents : capacité du véhicule, équipements disponibles, comportement dangereux ou conditions réelles de la prestation. Les suppositions liées à l’origine, au handicap, à la religion ou à un autre critère protégé ne constituent pas une méthode de sélection des clients. Le conducteur évalue le besoin et recherche une solution adaptée sans imposer de justification intime inutile.',
 'Un risque réel doit être décrit précisément. « Le passager porte un objet qui ne peut pas être arrimé » n’est pas la même chose que « les gens comme lui posent problème ». Documenter les faits permet de traiter une difficulté sans généralisation. Si une prestation est matériellement impossible, expliquez la contrainte concrète et envisagez une solution appropriée avec le client ou l’exploitant.',
 'Une personne demande de l’aide pour ranger une aide à la mobilité. Le conducteur pose une question pratique sur le rangement et l’installation ; il ne demande pas au client de raconter son diagnostic médical.',
 ['Identifier le besoin concret du client.','Évaluer la contrainte objective sans supposition personnelle.','Expliquer et chercher une solution adaptée.'],
 'Une préférence personnelle n’est pas un motif professionnel de traitement défavorable.',
 [
 ('Un chauffeur veut refuser une réservation à cause du nom de famille du client.','Quelle décision convient ?','Évaluer la prestation sans utiliser ce critère','Demander au client de changer de nom dans l’application','Appliquer un supplément lié au nom','Le nom supposé révéler une origine ne justifie pas un traitement défavorable.'),
 ('Cinq passagers se présentent pour quatre places passagers disponibles.','Quel motif expliquer ?','La capacité autorisée du véhicule','L’apparence des passagers','Le fait qu’ils voyagent en groupe','La capacité est une contrainte objective ; aucune place ne doit être improvisée.'),
 ('Un client manifeste un comportement violent et menaçant.','Sur quoi fonder la décision ?','Les faits observés et le risque immédiat','Sa nationalité supposée','Sa tenue vestimentaire uniquement','Le danger concret appelle une mise en sécurité et, si nécessaire, une alerte.'),
 ('Un partenaire demande d’écarter une catégorie de clients selon leur religion.','Quelle réponse retenir ?','Refuser cette consigne discriminatoire','L’appliquer discrètement','La facturer comme service premium','Une demande commerciale ne justifie pas une discrimination.')]),
'A.07':('Reconnaître, protéger et signaler',
 'Les propos sexistes, les demandes sexuelles insistantes et les contacts imposés ne relèvent pas d’un simple désaccord commercial. Le conducteur doit préserver la sécurité de la conduite et des personnes. L’objectif immédiat n’est pas de qualifier définitivement chaque fait comme un juriste, mais de reconnaître une situation inacceptable, mettre fin au risque dans la mesure du possible et mobiliser l’aide adaptée.',
 'Distinguez l’urgence d’un accompagnement ultérieur. Une agression en cours ou un danger immédiat nécessite une alerte adaptée ; une demande d’écoute ou d’orientation suit un autre circuit. Ne diffusez pas publiquement les données de la victime ou les messages reçus. Conservez seulement les éléments utiles pour le signalement, l’entreprise ou les autorités compétentes.',
 'Un passager menace de publier un mauvais avis si la conductrice accepte de le revoir dans un cadre intime. Elle pose une limite, préserve sa sécurité, garde les messages utiles et utilise les canaux de signalement ; elle ne négocie pas son consentement contre une note.',
 ['Préserver la sécurité immédiate.','Poser une limite et demander l’aide appropriée.','Conserver les éléments utiles et orienter le signalement.'],
 'La notation commerciale ne doit jamais servir à imposer un comportement sexuel.',
 [
 ('Un passager touche le conducteur sans son accord pendant le trajet.','Quelle priorité retenir ?','Préserver la conduite et rejoindre une situation sûre pour obtenir de l’aide','Continuer sans rien faire pour conserver la note','Répondre par une manœuvre brusque','La sécurité immédiate guide la réaction ; une conduite dangereuse créerait un risque supplémentaire.'),
 ('Une cliente rapporte une agression et souhaite être aidée.','Quelle attitude adopter ?','Écouter sans la culpabiliser et proposer une aide adaptée','Lui demander pourquoi elle était seule','Publier son récit avec son identité','L’accompagnement respecte la personne, la confidentialité et son besoin de protection.'),
 ('Des messages insistants continuent après une course.','Que faire des preuves ?','Conserver les éléments utiles sans diffusion publique','Les publier avec le numéro de téléphone','Tout transférer à des amis sans nécessité','La conservation utile au signalement se distingue d’une diffusion injustifiée.'),
 ('Une agression est en cours devant le véhicule.','Quel recours répond à l’urgence ?','Le 17 ou le 112','Une réponse à l’avis client la semaine suivante','Le seul classement du dossier commercial','Un danger immédiat nécessite une alerte urgente adaptée, pas seulement un traitement administratif.')]),
'A.08':('Transmettre une alerte exploitable',
 'La première question est celle de votre sécurité et de celle des autres. N’entrez pas dans une zone dangereuse et ne créez pas un second accident. Décrivez ensuite ce que vous voyez : lieu précis, nature des faits, nombre de personnes, dangers encore présents et état apparent des victimes. Signalez ce que vous ignorez au lieu d’inventer un diagnostic.',
 'L’opérateur peut poser des questions et donner des consignes. Restez disponible, répondez clairement et ne raccrochez pas de votre propre initiative si l’échange n’est pas terminé. Une localisation exploitable comporte un sens de circulation, une sortie, un repère ou un numéro lorsque cela aide les secours. La localisation d’une application complète vos informations, elle ne remplace pas votre observation.',
 'Sur une voie rapide, le conducteur indique le sens de circulation, le repère visible et la nature de l’événement depuis une position sûre. Il ne traverse pas la chaussée pour rechercher une meilleure photo.',
 ['Se protéger et repérer les dangers persistants.','Alerter avec une localisation et des faits observables.','Suivre les consignes et rester joignable.'],
 'Prendre des images ne passe pas avant la protection ou l’alerte.',
 [
 ('Un accident est visible à proximité d’un virage sans visibilité.','Quelle première décision est adaptée ?','Éviter de se mettre en danger et rechercher une position sûre','S’arrêter immédiatement sur la trajectoire des véhicules','Courir sur la chaussée pour filmer','Il faut éviter le suraccident avant d’entreprendre une aide.'),
 ('Vous appelez après un incident sur une voie à deux sens.','Quelle précision aide le plus ?','La localisation et le sens de circulation','La couleur du téléphone utilisé','Votre avis sur la responsabilité de chacun','Les secours ont besoin de trouver les personnes et d’anticiper l’accès.'),
 ('Vous ne savez pas si une personne est blessée.','Comment le dire ?','Je ne peux pas le confirmer ; voici ce que j’observe','Elle n’a certainement rien','Elle est forcément gravement blessée','Il faut distinguer l’observation d’une conclusion non vérifiée.'),
 ('L’opérateur vous demande de rester en ligne.','Quelle conduite tenir ?','Répondre et suivre ses consignes','Raccrocher pour appeler plusieurs amis','S’éloigner sans donner de moyen de rappel','L’échange permet d’adapter la réponse et de transmettre les consignes utiles.')]),
'A.09':('Adapter le service avec le passager',
 'Le handicap ne décrit pas à lui seul le besoin d’une personne. Demandez quelle aide est utile et attendez l’accord avant de toucher une personne ou son matériel. Un fauteuil, une canne ou un chien d’assistance ne sont pas des bagages ordinaires. La sécurité de leur installation et le respect de l’autonomie doivent être examinés avec le passager.',
 'Adaptez aussi la communication : annoncez ce que vous faites, décrivez un obstacle, parlez face à la personne lorsque cela facilite l’échange, vérifiez la compréhension sans infantiliser. Si votre véhicule ne permet réellement pas la prestation demandée, exposez la contrainte matérielle et recherchez une solution appropriée. Ne promettez pas une accessibilité que le véhicule n’offre pas.',
 'Une cliente malvoyante voyage avec son chien d’assistance. Le conducteur l’accueille, lui demande comment l’accompagner et organise une installation sûre dans l’habitacle. Il ne place pas le chien dans le coffre.',
 ['Demander le besoin et le consentement à l’aide.','Préparer une installation sûre et adaptée.','Vérifier le confort et l’autonomie de la personne.'],
 'Aider sans demander peut déséquilibrer la personne ou endommager son matériel.',
 [
 ('Un passager se déplace avec une canne et avance lentement.','Quelle première phrase convient ?','Souhaitez-vous une aide particulière pour rejoindre la voiture ?','Je vous porte sans vous demander','Expliquez-moi d’abord votre maladie','La demande porte sur une aide utile, sans imposer un geste ni collecter une information médicale inutile.'),
 ('Une cliente monte avec un chien d’assistance.','Quel choix est adapté ?','Organiser sa présence dans l’habitacle conformément aux règles','Le mettre obligatoirement dans le coffre','Exiger un supplément uniquement pour le chien','Le chien d’assistance accompagne sa bénéficiaire ; son accueil doit respecter les règles applicables.'),
 ('Le véhicule ne permet pas le transport sécurisé d’un fauteuil occupé.','Comment traiter la demande ?','Expliquer la limite matérielle et rechercher un véhicule adapté','Improviser une fixation','Refuser toutes les personnes handicapées à l’avenir','Une contrainte de véhicule se traite par une solution adaptée, pas par une exclusion générale.'),
 ('Un client entend difficilement votre explication.','Quelle adaptation proposer ?','Parler clairement face à lui et vérifier la compréhension','Crier sans reformuler','S’adresser uniquement à son accompagnant','L’échange doit rester adressé à la personne concernée et adapté à son besoin.')]),
'A.10':('Utiliser les données pour la bonne raison',
 'Une réservation nécessite certaines informations pour exécuter le service et permettre les vérifications prévues. Cela n’autorise pas tous les usages ultérieurs. Avant de collecter ou partager une donnée, identifiez la finalité, le besoin réel et le destinataire. Un collègue qui assure un remplacement peut avoir besoin des détails de la mission ; un groupe de discussion général n’en a pas nécessairement besoin.',
 'La durée de conservation dépend de la catégorie de document et de sa finalité. Les obligations comptables, la gestion d’un litige et la prospection commerciale ne se confondent pas. Une demande d’effacement doit donc être traitée avec discernement : supprimer les données devenues inutiles, expliquer les éléments qui doivent être conservés et sécuriser leur accès. Ne collectez pas un diagnostic médical lorsque seule une aide à l’installation est nécessaire.',
 'Pour préparer un accueil adapté, le conducteur note « prévoir du temps pour l’installation et demander l’aide souhaitée ». Il évite d’inscrire des détails médicaux qui ne servent pas à la prestation.',
 ['Définir la finalité et la donnée réellement nécessaire.','Limiter le partage aux personnes habilitées.','Appliquer une conservation adaptée et sécurisée.'],
 'Recevoir un numéro pour une course n’autorise pas à l’utiliser librement pour une autre finalité.',
 [
 ('Un collègue remplace le conducteur pour une mission précise.','Que transmettre ?','Les informations nécessaires à cette mission par un canal adapté','Tout l’historique privé du client','La liste complète des clients de l’année','Le remplacement justifie un partage limité au besoin opérationnel.'),
 ('Un chauffeur veut publier la capture d’une réservation pour se moquer d’un client.','Quel choix retenir ?','Ne pas diffuser les données de réservation','Publier en masquant seulement le prix','Diffuser si le groupe est privé','Le caractère privé d’un groupe ne rend pas le partage nécessaire ou licite.'),
 ('Le client indique avoir besoin de temps pour monter.','Quelle donnée est utile ?','Le besoin d’assistance pour la prestation','Son dossier médical complet','Le nom de tous ses médecins','La minimisation limite la collecte au besoin du service.'),
 ('Un client demande l’effacement de ses coordonnées. Des factures doivent encore être conservées.','Quelle méthode adopter ?','Examiner séparément les finalités et les obligations de conservation','Effacer tous les documents sans analyse','Refuser toute demande de manière définitive','Les données opérationnelles inutiles et les pièces soumises à conservation ne suivent pas forcément le même traitement.')]),
'A.11':('Présenter des preuves cohérentes lors d’un contrôle',
 'Un contrôle se prépare par un classement simple et des documents lisibles. Sachez retrouver les pièces concernant le conducteur, l’exploitant, le véhicule et la réservation. Les noms, immatriculations et dates doivent correspondre à la mission contrôlée. Un document exact mais inaccessible sur un téléphone déchargé ne permet pas de répondre aussi efficacement qu’un dossier organisé.',
 'Pendant le contrôle, restez factuel. Si une pièce manque ou si une information est contestée, expliquez la situation sans fabriquer de document, antidater une réservation ou modifier un justificatif. Notez ensuite ce qui doit être régularisé et l’interlocuteur à contacter. La contestation d’une mesure suit la procédure appropriée ; elle ne se remplace pas par une discussion agressive au bord de la route.',
 'Le chauffeur affiche le justificatif de la course en cours. Il vérifie la date de réservation et le lieu de prise en charge avant le service, ce qui évite de présenter par erreur le dossier du client précédent.',
 ['Préparer les pièces exactes de la mission.','Présenter les éléments demandés et répondre sur les faits.','Traiter les observations et conserver les traces utiles.'],
 'Ne modifiez pas une preuve pour la faire correspondre après coup à une situation.',
 [
 ('Le téléphone ne permet plus d’afficher le bon de réservation.','Quelle préparation aurait réduit ce risque ?','Prévoir un accès fiable au justificatif papier ou électronique','Se souvenir seulement du prénom du client','Compter sur le logo de l’application','La réservation doit être prouvable ; l’accès au document se prépare.'),
 ('Le justificatif présenté concerne une autre course.','Quelle réponse est adaptée ?','Rechercher le justificatif réel sans modifier ses dates','Changer le nom et l’heure sur la copie','Affirmer que tous les bons sont interchangeables','La pièce doit correspondre aux faits de la mission contrôlée.'),
 ('Un agent signale une incohérence d’immatriculation.','Que faire ?','Vérifier les pièces et expliquer factuellement le remplacement éventuel','Inventer une panne survenue la veille','Effacer la réservation','Une explication vérifiable et les pièces du véhicule réel sont nécessaires.'),
 ('Le chauffeur conteste une observation.','Quel comportement retenir ?','Rester courtois et utiliser la voie de recours adaptée','Refuser toute coopération par principe','Menacer de publier les informations de l’agent','La contestation se traite dans le cadre prévu, sans aggraver la situation.')]),
'A.12':('Distinguer dommage, contrat et infraction',
 'Un même événement peut avoir plusieurs conséquences. Le client peut invoquer une prestation mal exécutée ; l’assureur peut examiner un dommage ; une autorité peut rechercher une infraction. Ces questions ne s’effacent pas mutuellement. Rembourser un client ne fait pas nécessairement disparaître une éventuelle infraction, et une absence de sanction ne prouve pas qu’aucun problème contractuel n’existe.',
 'Pour analyser la situation, construisez une chronologie : ce qui était convenu, ce qui s’est produit, ce qui peut être établi et les mesures prises. Séparez les faits observables de l’appréciation de la faute. Cette méthode facilite la réponse à l’entreprise, au client, à l’assureur ou aux autorités. Le conducteur ne doit pas promettre un résultat juridique qu’il ne maîtrise pas.',
 'Un retard entraîne la réclamation d’un client. L’entreprise examine le contrat, les informations disponibles et la réaction du chauffeur. Elle distingue ce litige d’une éventuelle infraction routière commise pendant le trajet.',
 ['Décrire les faits et le service convenu.','Identifier les responsabilités et interlocuteurs possibles.','Traiter chaque volet avec les preuves et procédures adaptées.'],
 'Un geste commercial ne tranche pas à lui seul toutes les responsabilités.',
 [
 ('Un client accepte un remboursement après un incident qui pourrait aussi être une infraction.','Que peut-on conclure ?','Le volet commercial ne règle pas nécessairement le volet pénal','Toutes les poursuites deviennent impossibles','Le chauffeur peut effacer toutes les preuves','Les responsabilités civiles, contractuelles et pénales répondent à des questions différentes.'),
 ('Un client accuse le conducteur d’avoir abîmé un bagage.','Quel premier travail est utile ?','Établir les faits et la chronologie','Désigner immédiatement un coupable sans preuve','Supprimer les échanges pour éviter un conflit','Un dossier factuel permet d’examiner la réclamation et les garanties.'),
 ('L’entreprise promet un transfert à 8 h mais confirme par erreur 9 h au chauffeur.','Quelle analyse faut-il mener ?','Identifier les engagements et les échanges avant d’attribuer la responsabilité','Accuser automatiquement le passager','Considérer qu’aucun contrat n’existe','La chronologie et les preuves montrent l’origine et les conséquences de l’écart.'),
 ('Le conducteur est certain de son impression mais n’a pas observé le début de l’incident.','Comment présenter son témoignage ?','Distinguer ce qu’il a vu et ce qu’il suppose','Combler les détails manquants pour rendre le récit cohérent','Affirmer avoir tout vu','La précision inclut les limites de ce qui a réellement été observé.')]),
}

G_DATA = [
('G.01','Le registre de l’exploitant','Une entreprise créée au guichet unique et un conducteur titulaire de la carte remplissent deux volets du dossier, mais l’inscription de l’exploitant au REVTC reste une démarche distincte. Contrôlez l’état réel de l’inscription et les informations déclarées. Une capture de demande envoyée ne vaut pas forcément inscription finalisée. Le numéro doit correspondre à l’exploitant qui assure la mission.','L’entreprise Delta Mobilité possède un SIREN mais son dossier REVTC est encore incomplet. Elle résout les pièces manquantes avant de considérer son organisation prête.',[
('La carte personnelle est valide mais l’entreprise n’a pas terminé son inscription.','Quelle pièce ne remplace pas le REVTC ?','La carte personnelle du conducteur','L’inscription effective de l’exploitant','Le dossier de l’exploitant à jour','Les obligations personnelles et celles de l’entreprise sont distinctes.'),
('Un exploitant change une donnée déclarée importante.','Quel suivi mettre en œuvre ?','Vérifier les modalités de mise à jour du registre','Attendre sans vérifier jusqu’à la fermeture de l’entreprise','Modifier seulement le profil commercial','Les données réglementaires doivent rester cohérentes avec la situation réelle.'),
('Un intermédiaire communique le numéro REVTC d’une autre société.','Peut-il servir de preuve pour votre entreprise ?','Non, il doit correspondre à l’exploitant concerné','Oui, tous les numéros sont équivalents','Oui, si les sociétés ont le même véhicule','Un identifiant ne se prête pas et doit correspondre à l’entreprise qui exploite.'),
('Le dossier apparaît en attente de complément.','Comment le classer ?','À compléter et suivre','Définitivement validé','Sans conséquence pour la préparation','L’état administratif réel prévaut sur le fait d’avoir initié une démarche.')]),
('G.02','Justifier la situation financière du véhicule','La capacité financière répond à des règles liées à la situation de l’exploitant et des véhicules. Il faut identifier le titre de disposition du véhicule et les justificatifs demandés par le registre. La propriété ou une location répondant aux conditions prévues peuvent modifier les pièces exigées ; il ne faut pas déduire une dispense d’un simple accord oral. Les conditions exactes se vérifient sur la procédure officielle au moment du dossier.','Pour un nouveau véhicule, le gestionnaire rassemble le contrat de location et ses dates, puis vérifie la règle applicable au lieu de reprendre les pièces d’une autre voiture.',[
('L’exploitant ajoute une voiture en location très courte.','Quelle vérification est utile ?','La règle de capacité financière applicable à cette situation','La seule couleur de la carrosserie','Le fait que le conducteur préfère ce modèle','La situation de disposition du véhicule détermine les justificatifs à examiner.'),
('Un contrat mentionne une durée mais l’avenant la modifie.','Quel document retenir ?','L’ensemble contractuel à jour','Uniquement la première page ancienne','Une estimation orale de la durée','Il faut établir la situation réelle au moyen des pièces cohérentes.'),
('La plateforme accepte la voiture dans son application.','Cela dispense-t-il des vérifications du registre ?','Non','Oui, automatiquement','Oui, si la voiture est neuve','Une validation commerciale n’efface pas les obligations administratives.'),
('Un justificatif est au nom d’une autre société.','Quel problème apparaît ?','Le titulaire ne correspond pas à l’exploitant du dossier','Aucun, toutes les sociétés sont équivalentes','Le prix du trajet change automatiquement','Les justificatifs doivent se rapporter à la bonne entité.')]),
('G.03','Vérifier les caractéristiques avant l’achat','Un véhicule agréable ou accepté par une application n’est pas automatiquement éligible au régime VTC. Le nombre de places, les portes, les dimensions, la puissance, l’âge et les éventuelles exceptions doivent être examinés dans leur cadre applicable. Il faut identifier précisément la motorisation et la catégorie, puis utiliser les documents techniques fiables. Une formule commerciale comme « écologique » ne prouve pas l’existence d’une dérogation.','Avant de verser un acompte, le futur exploitant rapproche le certificat d’immatriculation, les caractéristiques du modèle exact et les règles applicables au véhicule.',[
('Une annonce dit « idéal VTC » sans fiche technique.','Que faire avant de s’engager ?','Vérifier les caractéristiques et la catégorie exacte','Se fier seulement au titre de l’annonce','Supposer que tout véhicule neuf est éligible','Une annonce commerciale n’est pas une preuve de conformité.'),
('La voiture comporte cinq places au total, conducteur compris.','Combien de passagers au maximum peut-elle accueillir sur cette base ?','Quatre','Cinq','Six si un trajet est court','Le conducteur occupe l’une des places autorisées.'),
('Le vendeur invoque une exception liée à la motorisation.','Quelle démarche est adaptée ?','Vérifier la catégorie réelle et le texte applicable','Accepter toute voiture portant un autocollant vert','Ignorer la fiche technique','Une exception doit correspondre précisément au véhicule et aux conditions du texte.'),
('Deux versions d’un même modèle ont des caractéristiques différentes.','La conformité de l’une suffit-elle pour l’autre ?','Non, il faut vérifier la version effectivement utilisée','Oui, le nom commercial suffit','Oui, si les sièges se ressemblent','Le contrôle porte sur les caractéristiques du véhicule réel.')]),
('G.04','Rendre l’identification conforme et lisible','La signalétique réglementaire et la carte professionnelle n’ont pas le même objet. L’une identifie le véhicule dans son cadre d’exploitation ; l’autre concerne le conducteur. Les emplacements, la lisibilité et les pièces prévues doivent être vérifiés. Un logo de plateforme, un autocollant publicitaire ou un document imprimé sans titre valable ne remplace pas la signalétique exigée.','Avant le service, le chauffeur contrôle les emplacements et l’état des éléments d’identification, puis traite une dégradation ou une incohérence avant de compter sur leur apparence.',[
('Le véhicule porte un grand logo de plateforme mais pas l’élément réglementaire attendu.','Que conclure ?','Le logo commercial ne remplace pas la signalétique réglementaire','Le logo suffit s’il est lisible','Une voiture de luxe est dispensée de tout repère','Il faut distinguer publicité et identification réglementaire.'),
('Une carte appartient au collègue absent.','Peut-elle être exposée comme celle du conducteur du jour ?','Non','Oui, si le même employeur est mentionné','Oui, pour un remplacement court','L’identification professionnelle est personnelle.'),
('Un élément de signalétique est devenu illisible.','Quelle action convient ?','Vérifier la procédure et le remettre en conformité','Le masquer davantage','Ajouter seulement un logo publicitaire','L’identification doit remplir sa fonction et respecter les modalités applicables.'),
('Le véhicule est remplacé.','Quel contrôle refaire ?','La conformité des documents et de la signalétique du véhicule réel','Aucun, les documents suivent toujours le conducteur','Seulement le niveau de musique','Les justificatifs doivent correspondre au véhicule effectivement utilisé.')]),
('G.05','Contrôler le justificatif de réservation','La réservation doit être réelle et préalable. Depuis l’entrée en vigueur de l’arrêté du 6 août 2025, le justificatif comporte notamment l’identité et les coordonnées de l’exploitant, son numéro REVTC, son numéro unique d’identification, les informations du client, la date et l’heure de réservation, celles de la prise en charge et le lieu de prise en charge. Si les données du client prévues ne figurent pas, le conducteur doit pouvoir fournir sans délai à l’agent les moyens de le contacter.','Le contrôle d’un bon consiste à lire les informations et à vérifier leur cohérence avec la mission. Une belle mise en page ne répare pas une réservation absente ou un horaire antidaté.',[
('Un bon comporte l’heure de prise en charge mais aucune date ni heure de réservation.','Quel point manque ?','La trace datée de la réservation préalable','La couleur des bagages','Le menu choisi à destination','Il faut distinguer le moment de la commande et celui du transport.'),
('Le client réserve à 13 h 10 pour une prise en charge à 14 h.','Quel constat est possible sur la chronologie ?','La réservation indiquée précède la prise en charge','Elle intervient après le départ','Elle prouve à elle seule toute la conformité du véhicule','La chronologie est cohérente sur ce point, sans dispenser des autres vérifications.'),
('Le chauffeur modifie l’heure du bon après une prise en charge spontanée.','Quel est le problème ?','Le document ne peut pas fabriquer une réservation préalable réelle','Toute réservation peut être antidatée','Le client peut autoriser l’antidatage','La preuve doit refléter les faits.'),
('Les informations de contact du client ne figurent pas sur le justificatif présenté.','Que doit pouvoir faire le conducteur dans le cadre prévu ?','Fournir sans délai à l’agent les moyens de contacter le client','Affirmer qu’aucun contact n’est jamais nécessaire','Inventer un numéro pour compléter','L’arrêté prévoit cette possibilité de contact lorsque les informations concernées ne figurent pas sur le support.')]),
('G.06','Distinguer une commande d’une sollicitation dans la rue','Le VTC travaille dans le cadre de la réservation préalable. La disponibilité d’un véhicule ne permet pas de se comporter comme un taxi en maraude. Un client qui hèle le véhicule ne crée pas, à lui seul, la preuve d’une réservation antérieure. Il faut analyser le déroulement réel, sans organiser une fausse formalité destinée à déguiser la situation.','À la sortie d’une gare, le conducteur rejoint la mission réservée et respecte le lieu autorisé. Il ne sollicite pas les voyageurs qui passent pour remplir les places restantes.',[
('Un passant fait signe à un VTC libre.','Quelle conduite est correcte ?','Respecter les règles de réservation et ne pas partir comme en maraude','Partir puis créer une réservation rétroactive','Utiliser un faux bon déjà préparé','La prestation doit respecter la réservation préalable réelle.'),
('Un chauffeur attend sur la voie publique en proposant ses services aux passants.','Quel comportement doit-il corriger ?','La recherche de clients en maraude','La tenue de son agenda','La vérification d’une commande existante','L’attente et la sollicitation doivent respecter les règles propres au VTC.'),
('Une course a été réservée à l’avance par téléphone et correctement justifiée.','L’absence d’application suffit-elle à la rendre irrégulière ?','Non, la réservation peut utiliser un autre canal','Oui, seule une application privée autorise une course','Oui, sauf paiement en espèces','Le canal de commande n’est pas en lui-même le critère décisif.'),
('Le chauffeur dispose d’une réservation pour une personne mais prend un autre passant à sa place.','Que vérifier ?','La réalité de la nouvelle prestation et ses conditions','Rien, un bon vaut pour tous les clients','Seulement le nombre de valises','Le justificatif doit correspondre à la mission réellement réalisée.')]),
('G.07','Préparer l’accueil en gare et à l’aéroport','La réservation ne donne pas accès à tous les espaces. Les zones de prise en charge, parkings et conditions locales s’ajoutent aux règles nationales du métier. Repérez le terminal ou la sortie, le point convenu et les solutions en cas de retard. Un lieu réservé à une autre catégorie de véhicules ne devient pas accessible parce que votre client est pressé.','Une arrivée de train retardée conduit le chauffeur à adapter son organisation et informer le client. Il vérifie le lieu d’attente autorisé au lieu de rester indéfiniment dans une zone interdite.',[
('Le client propose une prise en charge sur une voie réservée aux bus.','Quelle réponse choisir ?','Proposer un lieu autorisé et accessible','S’y rendre parce que le client l’a demandé','Masquer la signalétique du véhicule','La demande du client ne supprime pas les règles de circulation et d’accès.'),
('Le terminal change après la réservation.','Que faire ?','Confirmer le nouveau point précis et adapter le trajet','Attendre au lieu initial sans prévenir','Deviner la sortie au hasard','La coordination repose sur une localisation partagée et compréhensible.'),
('Le vol a du retard et la zone d’arrêt ne permet pas une longue attente.','Quelle solution rechercher ?','Un stationnement autorisé et une information du client','Rester sur la zone interdite autant que nécessaire','Attendre en double file','L’organisation doit préserver l’accès et la sécurité.'),
('Un autre chauffeur affirme qu’un parking est autorisé à tous.','Comment vérifier ?','Consulter les règles locales et la signalisation effective','Se fier exclusivement à l’habitude rapportée','Suivre systématiquement la voiture devant','Les conditions locales doivent être vérifiées directement.')]),
('G.08','Organiser l’après-course','Après la prestation, l’organisation dépend de l’existence d’une nouvelle réservation ou d’un contrat justifiable. En leur absence, il faut respecter les obligations de retour vers la base ou un lieu de stationnement autorisé hors chaussée. La fin d’une course ne devient pas un droit d’attendre n’importe où en recherchant un nouveau passager.','Le chauffeur dépose son client et vérifie son planning. Une mission suivante est confirmée : il organise son approche dans le respect des lieux. Sans mission justifiée, il applique la règle de retour ou de stationnement adaptée.',[
('La course est terminée et aucune suivante n’est réservée.','Quelle organisation convient ?','Rejoindre la base ou un stationnement autorisé hors chaussée selon les règles','Attendre sur un emplacement taxi pour attirer un client','Circuler lentement pour être hélé','La fin de course ne permet pas la maraude.'),
('Une nouvelle réservation est confirmée et justifiable.','Que préparer ?','Son approche et son lieu d’attente autorisé','Un faux bon pour une mission hypothétique','Une attente sur n’importe quelle voie','Une réservation réelle se combine avec les règles locales.'),
('Le chauffeur reçoit seulement une promesse vague de rappel.','Peut-il la traiter comme une réservation confirmée ?','Non, il doit vérifier la réalité de l’engagement','Oui, toute conversation suffit','Oui, si le client semblait intéressé','Une intention incertaine n’a pas la même portée qu’une mission réservée.'),
('Le client demande au chauffeur de rester disponible dans un contrat défini.','Quel contrôle effectuer ?','Les conditions réelles de mise à disposition et de stationnement','Aucun contrôle une fois le client descendu','Seulement le nom de l’hôtel','Il faut pouvoir justifier le service et respecter les lieux.')]),
('G.09','Convenir du service avant l’exécution','Le prix et le contenu doivent être compréhensibles avant l’engagement : trajet, nombre de passagers, bagages, attente, péages, supplément éventuel et conditions de modification. Une course au forfait et une prestation dont le prix dépend de paramètres n’ont pas la même explication. Le client doit comprendre les conditions retenues ; l’exercice pédagogique ne fixe aucun tarif légal ou recommandé.','Une demande d’arrêt supplémentaire pendant le trajet conduit le conducteur à préciser ses conséquences et obtenir l’accord du client, sans annoncer après coup un montant inattendu.',[
('Un devis dit seulement « transfert 90 € » et une attente importante est prévisible.','Que clarifier ?','Ce qui est inclus et les conditions d’attente','Le signe astrologique du client','Uniquement la couleur des sièges','Le périmètre du prix doit permettre un accord éclairé.'),
('Le client ajoute une étape non prévue.','Quelle démarche choisir ?','Expliquer les conséquences et convenir de la modification','Facturer un supplément caché à l’arrivée','Accepter toutes les modifications sans vérifier la faisabilité','Une modification s’examine avant de créer un nouvel engagement.'),
('Une plateforme affiche le prix de la course.','Que reste-t-il à vérifier ?','Le service couvert et les conditions applicables','Rien, le chiffre règle tout','Seulement la note du passager','Un prix n’explique pas à lui seul la prestation et les exceptions.'),
('Un péage n’est pas inclus selon le devis accepté.','Comment éviter la surprise ?','L’expliquer clairement avant le trajet et confirmer l’option','Le cacher jusqu’au paiement','Le présenter comme une amende','La transparence des conditions permet au client de comprendre le montant.')]),
('G.10','Remplacer sans rompre la conformité','Le remplacement d’un conducteur ou d’un véhicule doit déclencher les vérifications propres à la nouvelle situation. Un conducteur remplaçant doit remplir ses conditions personnelles. Une voiture remplaçante doit répondre aux exigences techniques, documentaires et d’assurance applicables. Les informations opérationnelles transmises au client et au partenaire doivent rester cohérentes.','Une panne impose un remplacement. L’exploitant vérifie les pièces du conducteur et du véhicule disponibles, confirme la solution au client et conserve la trace des changements utiles.',[
('Un ami disponible propose de conduire sans carte VTC.','Peut-il remplacer le chauffeur pour transporter les clients ?','Non','Oui, s’il a déjà conduit une berline','Oui, si la course dure moins de dix minutes','La disponibilité ne remplace pas les conditions personnelles du métier.'),
('Une voiture de location doit remplacer la voiture habituelle.','Quelle vérification est requise ?','L’éligibilité, les assurances et les formalités du véhicule réel','Seulement la climatisation','Aucune, toute location autorise le VTC','La location commerciale et la conformité à l’activité sont deux questions différentes.'),
('Le client attend une plaque différente de celle du véhicule remplaçant.','Que faire ?','L’informer du changement par un canal sûr','Lui demander de monter sans explication','Modifier son nom pour correspondre au bon','L’information réduit le risque d’erreur et doit rester cohérente avec les pièces.'),
('Le remplaçant demande le dossier médical complet du passager.','Que transmettre ?','Uniquement les besoins pratiques nécessaires à la mission','Tout document disponible par précaution','La liste de ses consultations','Le remplacement n’autorise pas une collecte ou un partage excessif.')]),
('G.11','Suivre le véhicule pendant toute son exploitation','La conformité se maintient dans le temps. L’entretien, le contrôle technique applicable, les garanties et l’état des équipements doivent être suivis avec leurs propres échéances. Une fiche de suivi comporte la date, le kilométrage, l’action, le prestataire et le justificatif. Un voyant ou un défaut constaté peut justifier une action avant la prochaine échéance planifiée.','Une anomalie de freinage apparaît alors que le contrôle périodique est encore valable. Le chauffeur ne considère pas cette validité comme une autorisation de continuer malgré le défaut.',[
('Un défaut de freinage apparaît avant l’échéance du contrôle technique.','Quelle priorité retenir ?','Faire traiter le défaut et ne pas engager une mission dangereuse','Attendre le prochain contrôle prévu','Augmenter la musique pour ne plus entendre le bruit','Un justificatif valide ne neutralise pas une anomalie actuelle.'),
('Une facture d’entretien indique un autre véhicule.','Comment la classer ?','Comme pièce à vérifier avant de l’attribuer au dossier','Comme preuve suffisante pour toute la flotte','La modifier à la main sans contrôle','Les preuves d’entretien doivent se rapporter au véhicule concerné.'),
('Le conducteur suit uniquement les kilomètres facturés.','Quel suivi manque pour l’entretien ?','Le kilométrage total réellement parcouru','Les seules évaluations des clients','Le nombre d’applications installées','Approches et retours à vide participent à l’usure du véhicule.'),
('Un équipement de sécurité est endommagé.','Quelle décision prendre ?','Vérifier et corriger avant d’utiliser le véhicule dans une situation incompatible','Le cacher aux passagers','Considérer que l’assurance remplace la réparation','Prévenir le risque et réparer sont distincts de l’indemnisation éventuelle.')]),
('G.12','Mettre à jour une règle avec sa date et sa source','Une veille utile commence par une question précise : quelle règle, pour quel véhicule, quelle personne et quelle date ? Privilégiez la version en vigueur du texte et les démarches officielles. Une modification publiée peut prévoir une entrée en vigueur ultérieure ou des dispositions transitoires. Conservez la source et la date de vérification pour pouvoir expliquer votre décision.','L’équipe rencontre une ancienne fiche de réservation. Elle vérifie le texte actualisé et corrige les modèles futurs sans fabriquer de nouvelles dates pour les missions passées.',[
('Deux articles en ligne donnent des règles différentes.','Quelle première vérification faire ?','Les dates, les sources et les situations auxquelles ils s’appliquent','Choisir celui dont le titre est le plus court','Suivre toujours le premier résultat','Une divergence peut venir d’une ancienne version ou d’un périmètre différent.'),
('Un texte publié prévoit une entrée en vigueur différée.','Quelle date commande l’application ?','La date d’entrée en vigueur prévue pour la situation','Toujours le jour où vous découvrez le texte','La date du commentaire d’un internaute','Publication et application ne se confondent pas nécessairement.'),
('Une plateforme modifie ses conditions commerciales.','Cela modifie-t-il automatiquement la loi ?','Non, il faut distinguer contrat et règle légale','Oui, pour tous les VTC en France','Oui, si plusieurs applications l’acceptent','Un contrat commercial ne remplace pas le droit applicable.'),
('Une équipe veut pouvoir retrouver la base d’une décision.','Que conserver dans la veille ?','La source, la date, le périmètre et la conséquence pratique','Uniquement une rumeur résumée','Le nom du premier collègue qui l’a entendue','Une trace structurée permet une mise à jour fiable et explicable.')]),
]

def build():
    topics={}; practices={}
    for ref,(title,p1,p2,example,method,pitfall,rows) in DATA.items():
        topics[ref]=topic(title,[p1,p2],example,method,pitfall)
        practices[ref]=[q(ref,*row) for row in rows]
    for ref,title,teach,example,rows in G_DATA:
        method=['Identifier la personne, le véhicule et la mission concernés.','Rapprocher les justificatifs de la situation réelle et de la règle applicable.','Traiter l’écart, puis vérifier la conformité avant le départ.']
        topics[ref]=topic(title,[teach,'Le bon réflexe consiste à vérifier les informations qui peuvent changer : dates, titulaire, usage, véhicule et état du dossier. Une confirmation commerciale, une habitude locale ou l’accord du passager ne remplace pas une exigence applicable. Gardez une trace des contrôles utiles et un calendrier d’actualisation. En cas de doute réel, cherchez la réponse auprès de la source compétente avant de vous engager.'],example,method,'Ne transformez pas une supposition ou une ancienne pièce en preuve de conformité actuelle.')
        practices[ref]=[q(ref,*row) for row in rows]
    return topics,practices
