"""Authored visual summaries and additional module case studies (v2)."""
BOARDS = {
'01': ('Les quatre limites d’une mission', [('Activité','Ce que l’autorisation et la mission permettent réellement.'),('Lieu','Le site, ses zones et les éventuelles conditions particulières.'),('Moyens','Les équipements, compétences et procédures disponibles.'),('Relais','Le responsable, les secours et les autorités selon le besoin.')]),
'02': ('Une action, plusieurs responsabilités', [('Pénale','Une infraction peut donner lieu à une sanction prévue par la loi.'),('Civile','Un dommage peut engager une obligation de réparation.'),('Disciplinaire','Un manquement peut relever de l’employeur ou du cadre professionnel.'),('Justification','L’ordre reçu et le résultat ne suffisent pas : examiner les faits et les conditions légales.')]),
'03': ('Article 73 : raisonner avant de contraindre', [('Faits','Qu’ai-je réellement vu ? À quel moment ? Avec quelles limites ?'),('Conditions','Crime flagrant ou délit flagrant puni d’emprisonnement : vérifier le cadre.'),('Nécessité','Adapter les moyens et réévaluer la contrainte ; préserver la dignité.'),('OPJ','Organiser sans retard injustifié le relais vers l’officier de police judiciaire.')]),
'04': ('Le parcours d’une donnée', [('Collecter','Seulement ce qui est nécessaire à une finalité définie.'),('Consulter','Réserver l’accès aux personnes habilitées et au besoin professionnel.'),('Transmettre','Vérifier destinataire, périmètre et canal autorisé.'),('Conserver','Respecter la durée prévue et tracer les exceptions encadrées.')]),
'05': ('Une même exigence, un accueil adapté', [('Règle commune','Utiliser des critères licites et objectifs.'),('Besoin réel','Demander quelle aide est utile sans intrusion dans la vie privée.'),('Adaptation','Rendre le message et le cheminement accessibles.'),('Dignité','Expliquer, protéger la confidentialité et proposer le recours prévu.')]),
'06': ('La boussole déontologique', [('Licéité','Une consigne ne permet pas de dépasser la loi.'),('Impartialité','Pas de faveur personnelle, de cadeau intéressé ou de discrimination.'),('Confidentialité','Pas d’usage privé des informations ou moyens du site.'),('Fiabilité','Décrire fidèlement, reconnaître les erreurs et organiser leur correction.')]),
'07': ('Faire redescendre la tension', [('Se placer','Garder une distance adaptée et une possibilité de retrait.'),('Écouter','Poser une question simple, laisser répondre et reformuler.'),('Expliquer','Une règle claire, une demande concrète et une option tenable.'),('Relayer','Demander un appui avant de dépasser ses moyens ; réévaluer le danger.')]),
'08': ('Une alerte que l’on peut utiliser', [('Qui et où ?','Identité de l’émetteur, site, zone et accès précis.'),('Quoi ?','Faits observés, heure, personnes et danger actuel.'),('Quelles mesures ?','Protection déjà engagée et contraintes connues.'),('Quel besoin ?','Renfort ou secours attendu, puis confirmation de la réception.')]),
'09': ('Construire une décision défendable', [('Observer','Séparer les faits des hypothèses et identifier les inconnues.'),('Comparer','Relier la règle aux options et à leurs conséquences.'),('Décider','Choisir une mesure suffisante, licite et proportionnée.'),('Réévaluer','Vérifier l’effet, ajuster, transmettre et tracer.')]),
'10': ('Repérer une exposition', [('Source','Quel équipement, produit, mouvement ou environnement peut blesser ?'),('Personnes','Qui peut être exposé : public, salariés, prestataires, agent ?'),('Protection','Éviter l’exposition et utiliser les protections prévues.'),('Traitement','Alerter le responsable compétent et vérifier la prise en charge.')]),
'11': ('Électricité : les limites qui protègent', [('Observer à distance','Un équipement silencieux peut rester sous tension.'),('Éviter le contact','Ne pas toucher, bricoler ou s’approcher pour confirmer une hypothèse.'),('Vérifier son cadre','Formation, titre d’habilitation et opération autorisée sont distincts.'),('Faire intervenir','Protéger les abords et alerter le relais technique ou les secours.')]),
'12': ('Menace : décider selon les possibilités', [('S’échapper','Si un itinéraire permet de quitter le danger sans exposition supplémentaire.'),('Se cacher','Si la fuite est impossible, rechercher une protection et rester discret.'),('Alerter','Depuis une situation protégée, transmettre des faits et suivre les instructions.'),('Dernier recours','Si fuir ou se cacher est impossible et que la vie est menacée, les consignes publiques évoquent la résistance.')]),
'13': ('Une trace que l’on peut relire', [('Attribuer','Auteur identifié et origine des informations.'),('Dater','Heure des faits distinguée de l’heure de saisie.'),('Décrire','Lieu, faits, actions, destinataires et état du suivi.'),('Rectifier','Un complément traçable, sans effacement dissimulé.')]),
'14': ('Face à une infraction présumée', [('Constater','Décrire ce qui est vu et ce qui est rapporté, sans verdict.'),('Protéger','Limiter l’exposition et prendre en compte les urgences.'),('Vérifier le cadre','Distinguer règle d’accès, soupçon, flagrance et défense.'),('Transmettre','Préserver les éléments, relayer aux autorités et rendre compte.')]),
'15': ('Les quatre équilibres de l’événement', [('Accès','Billets, droits, contrôles licites et traitement des refus.'),('Flux','Entrées, sorties, files, densité et dégagements.'),('Public','Accessibilité, personnes vulnérables, information et secours.'),('Coordination','Zones, radios, responsables, relève et retour d’expérience.')]),
}

# New cases supplement the existing 62 dossier situations.
CASES = {
'01': ('Une livraison hors périmètre','Le quai prévu est fermé. Un prestataire demande à l’agent du hall de l’accompagner dans un bâtiment voisin, tandis qu’un groupe attend à l’accueil. Le chef de poste ne répond pas au premier appel.','Identifiez la demande hors mission, le risque d’abandon du poste et le relais de remplacement.','Maintenir l’accueil, vérifier la consigne de livraison et utiliser le circuit de remplacement. Ne pas improviser une extension de mission. Tracer la demande et la solution validée.'),
'02': ('La menace cesse, la décision change','Une personne repousse violemment un visiteur. Après l’alerte, elle recule, pose l’objet qu’elle tenait et cesse l’agression. Un collègue veut continuer une contrainte pour lui donner une leçon.','Comparez la situation au début et à la fin. Quelle nécessité a changé ?','Protéger les personnes et faire cesser tout excès. La réaction doit être réévaluée quand l’atteinte cesse ; la punition ne relève pas de l’agent. Vérifier le besoin de secours et transmettre la chronologie.'),
'03': ('Un témoignage trop rapide','Une caissière signale un vol. Elle a vu un article placé dans un sac mais n’a pas observé le passage en caisse. Le portique ne sonne pas. La personne accepte de discuter à proximité de l’accueil.','Séparez les faits connus, le point manquant et les actions possibles sans contrainte injustifiée.','Le récit partiel ne permet pas d’inventer le non-paiement. Vérifier les éléments disponibles dans le cadre du site, sans interrogatoire coercitif. Si les conditions légales d’une appréhension ne sont pas établies, ne pas les présumer.'),
'04': ('La bonne pièce jointe, le mauvais destinataire','Un agent prépare un rapport pour le responsable sécurité. La capture jointe montre aussi une fiche médicale ouverte sur un autre écran. Le logiciel suggère une liste de diffusion générale.','Quels contrôles effectuer avant d’envoyer ? Que faire si le message est déjà parti ?','Retirer les données non nécessaires et vérifier le destinataire autorisé. Si l’envoi a eu lieu, signaler rapidement l’incident au responsable selon la procédure, sans multiplier les copies ni improviser une notification externe.'),
'05': ('Une règle expliquée autrement','Un visiteur malentendant ne réagit pas à une consigne orale. La file s’allonge et un collègue propose de le refuser pour manque de coopération. Le visiteur montre qu’il peut lire une instruction écrite.','Distinguez refus et difficulté de compréhension. Proposez une adaptation concrète.','Présenter la consigne par écrit et vérifier sa compréhension. Maintenir les critères d’accès tout en adaptant le moyen de communication. Ne pas attribuer une intention hostile à une difficulté sensorielle.'),
'06': ('Le service rendu en échange','Un habitué propose des invitations gratuites à l’équipe pour que son matériel entre sans vérification. Il insiste sur ses bonnes relations avec le client et demande de ne pas inscrire l’échange.','Quels indices révèlent un conflit avec les obligations professionnelles ?','L’avantage vise une exception et l’absence de trace. Refuser, appliquer la procédure et signaler la proposition par le relais prévu. Une relation personnelle ne remplace pas une autorisation.'),
'07': ('Trois voix à l’accueil','Une personne attend depuis longtemps. Deux agents lui donnent des instructions différentes et un responsable intervient à voix forte. La personne se rapproche et répète qu’on se moque d’elle.','Réorganisez l’espace, les interlocuteurs et le message en trois actions.','Préserver la distance, désigner un interlocuteur principal et reconnaître l’attente. Donner une consigne cohérente et une option réelle. Le collègue assure l’appui sans surenchère ; demander un renfort si le risque augmente.'),
'08': ('La mauvaise entrée','Un agent demande de l’aide à « l’entrée du parking ». Le site possède deux parkings distants. Le renfort part vers le mauvais bâtiment ; pendant ce temps, la zone réellement concernée reste encombrée.','Réécrivez l’alerte et sa confirmation de réception.','Donner le bâtiment, le repère de porte, l’accès utilisable, les faits et le besoin. Le destinataire reformule la localisation. Rectifier immédiatement la première orientation et tracer l’heure de correction.'),
'09': ('Deux options, deux risques','Un cheminement est obstrué. Le détour le plus court traverse une zone de livraison active ; un autre passage est plus long mais protégé. Le public se presse et réclame l’option rapide.','Comparez les deux options, puis expliquez votre décision en quatre phrases.','Le gain de temps doit être comparé à l’exposition aux véhicules. Organiser le parcours protégé dans le cadre des consignes, expliquer le motif, demander le traitement de l’obstacle et réévaluer après correction.'),
'10': ('L’intervention qui change de zone','Une entreprise vient réparer un équipement. Elle déplace son chantier près d’un accès piéton sans prévenir la coordination. Des outils et un câble traversent le passage.','Dressez un tableau : danger, personnes exposées, mesure provisoire, responsable.','Signaler le changement de coactivité, prévenir l’exposition et faire valider l’adaptation du chantier. Ne pas déplacer un équipement inconnu. Vérifier que l’accès rétabli est réellement utilisable avant de clore l’anomalie.'),
'11': ('Un réarmement de trop','Un équipement déclenche plusieurs fois. Un responsable demande à l’APS d’ouvrir le tableau et de maintenir le disjoncteur en position. L’agent n’a pas l’habilitation correspondant à une intervention électrique.','Expliquez le refus de l’acte technique et proposez une continuité sûre.','Ne pas neutraliser la protection ni ouvrir pour réparer. Signaler les déclenchements et faire intervenir le service compétent. Protéger les abords si nécessaire et appliquer la procédure de continuité du site.'),
'12': ('Une consigne sans date','Deux affiches Vigipirate coexistent au poste. Un courriel non vérifié annonce de nouveaux contrôles dès le lendemain. Le responsable souhaite un briefing fiable pour les équipes.','Quelles sources vérifier ? Qu’est-ce qui doit figurer dans le briefing ?','Vérifier la source officielle actuelle et la déclinaison locale validée. Préciser date, périmètre, actions, limites et contacts. Un message non authentifié ou un niveau d’alerte ne crée pas de pouvoirs supplémentaires.'),
'13': ('La panne puis le doublon','Le réseau coupe à 23 h 50. L’agent note deux incidents sur le support de continuité prévu. À 00 h 20, le logiciel revient et le collègue a déjà saisi l’un des événements avec une heure approximative.','Préparez la reprise sans doublon et une correction traçable.','Comparer les événements avant intégration, conserver l’heure réelle et préciser l’heure de saisie. Relier le complément à l’entrée existante et expliquer la rectification. Sécuriser les supports temporaires selon la procédure.'),
'14': ('Les faits contredisent le premier signalement','Un commerçant accuse un client. Une vérification autorisée montre ensuite que l’article a été réglé à une autre caisse. Le client est toujours immobilisé à l’accueil et demande à repartir.','Quelles décisions doivent changer immédiatement ? Quel compte rendu conserver ?','Cesser la contrainte injustifiée et actualiser sans délai le relais. Décrire la première information, la vérification et la correction. Ne pas conserver une accusation devenue infondée ni effacer l’erreur de l’historique.'),
'15': ('La file rejoint la voie de secours','À l’ouverture, une file ralentit au contrôle. Une barrière déplacée dirige des personnes vers l’accès secours. Une famille avec poussette ne peut plus rejoindre le cheminement adapté.','Proposez une réponse coordonnée sur les flux, l’accessibilité et l’information.','Alerter la coordination, préserver l’accès secours et faire adapter le dispositif prévu. Orienter la famille par le cheminement accessible. Donner une information cohérente au public et vérifier l’effet des mesures sur la densité.'),
}
