"""Authored document studies. All names, extracts and figures are fictional.
They are exercise evidence, not operational rules or legal quotations.
"""

def doc(title, text, *rows):
    return dict(title=title, text=text, rows=[list(row) for row in rows])


def q(prompt, good, bad1, bad2, why):
    return dict(prompt=prompt, correct=good, wrong=[bad1, bad2], explanation=why)


def cards(prompt, options, rows, explanation, kind='sort'):
    return dict(prompt=prompt, kind=kind,
                options=[dict(id=str(i), text=t) for i,t in enumerate(options)],
                rows=[dict(id='r'+str(i), text=t, answer=str(a)) for i,(t,a) in enumerate(rows)],
                explanation=explanation)


CASEFILES = {
'01': dict(section='01-04', title="Contrôler un planning d'affectation", brief="Le responsable prépare trois postes pour demain. Comparez le planning, les justificatifs disponibles et la demande du client. Identifiez ce qui peut être préparé et ce qui exige une vérification avant affectation.", documents=[
 doc('Planning proposé', 'Les trois lignes sont des propositions à contrôler, pas des affectations validées.', ('Lina', 'Accueil sécurité du site A ; justificatifs d’exercice et préparation au poste vérifiés par le responsable.'), ('Noé', 'Ronde du site B ; seul un diplôme est joint, situation administrative non vérifiée.'), ('Sam', 'Poste du site C puis tournée du quartier sur demande téléphonique du client.')),
 doc('Fiche de périmètre', 'Le poste C concerne les locaux et accès identifiés au plan du site.', ('Voie publique', 'Aucun justificatif relatif à une mission sur la voie publique ne figure dans ce dossier.'), ('Modification', 'Toute extension doit être examinée par le responsable avant intégration au planning.')),
 doc('Message du client', '« Ajoutez la tournée du quartier et annoncez-vous comme police du site pour être mieux écoutés. »', ('Statut', 'Demande reçue ; compatibilité non validée.'))], questions=[
 q('Quelle ligne manque d’une vérification personnelle essentielle ?', 'Celle de Noé : le diplôme ne suffit pas à vérifier le droit actuel d’exercer.', 'Celle de Lina, parce qu’un accueil ne peut jamais être une mission de sécurité.', 'Aucune : un planning suffit à autoriser l’exercice.', 'Le planning organise le travail ; il ne remplace pas les justificatifs du droit d’exercer.'),
 q('Pourquoi la tournée du quartier doit-elle être examinée ?', 'Elle étend le périmètre et nécessite de vérifier le cadre et les autorisations applicables.', 'Toute demande téléphonique du client vaut autorisation sur la voie publique.', 'Une tournée est toujours autorisée si elle dure moins d’une heure.', 'La durée ou le voisinage ne remplacent pas la vérification du cadre de la mission.'),
 q('Quelle présentation corrige le message du client ?', '« Agent de sécurité du site C » avec une demande liée à la mission réelle.', '« Police du site C » si le client valide la formule.', 'Un grade de police choisi par le chef de poste.', 'La présentation ne doit pas créer de confusion avec la puissance publique.')], classification=cards('Classez les éléments du dossier.', ['Vérifié dans le dossier', 'À vérifier avant affectation', 'Formulation à écarter'], [('Justificatifs de Lina contrôlés',0), ('Situation administrative de Noé',1), ('Extension sur la voie publique',1), ('Annonce « police du site »',2)], 'Un élément vérifié, une condition manquante et une formulation trompeuse demandent trois réponses distinctes.')),
'02': dict(section='02-03', title='Comparer deux chronologies de défense', brief="Deux récits décrivent une altercation à un accueil. Ils diffèrent sur le moment où une action a eu lieu. Comparez-les sans décider vous-même de la qualification judiciaire.", documents=[
 doc('Éléments concordants', 'Les deux récits situent une tentative de coup puis un retrait.', ('14 h 06', 'Une personne tente de frapper une salariée.'), ('14 h 07', 'La personne recule et s’éloigne ; aucune nouvelle attaque n’est décrite.')),
 doc('Récit A', 'L’agent décrit une action de protection pendant la tentative de coup, puis l’arrêt de cette action lorsque la personne s’éloigne.', ('À préciser', 'Moyens employés, danger perçu et possibilités au moment de l’action.')),
 doc('Récit B', 'Un témoin décrit une poursuite suivie d’un coup à 14 h 09.', ('Propos rapporté', '« Il fallait lui apprendre à respecter le personnel. »'), ('Limite', 'La contradiction entre les récits reste à examiner.'))], questions=[
 q('Quelle différence est déterminante entre A et B ?', 'Le lien temporel entre l’action et l’attaque, ainsi que son objectif.', 'Le nombre de phrases dans chaque récit.', 'Le fait que le témoin soit arrivé avant la fin de la vacation.', 'Une action pour protéger face à une attaque et une action punitive après le retrait ne s’analysent pas de la même façon.'),
 q('Que peut-on conclure du récit A seul ?', 'Il faut encore examiner nécessité, proportion et circonstances ; le titre « protection » ne suffit pas.', 'Toute action appelée protection est automatiquement justifiée.', 'Aucune action de protection n’est possible dans un accueil.', 'Le récit donne des repères mais ne tranche pas toutes les conditions juridiques.'),
 q('Comment traiter la contradiction ?', 'Conserver les deux sources et rechercher les éléments permettant de préciser la chronologie.', 'Fusionner les récits pour supprimer le désaccord.', 'Supprimer le témoin qui met l’agent en difficulté.', 'La fiabilité du dossier exige de conserver les sources et les incertitudes.')], classification=cards('Rattachez chaque question à son objet principal.', ['Pénal', 'Civil', 'Disciplinaire'], [('Une infraction a-t-elle été commise ?',0), ('Quel dommage doit être réparé ?',1), ('Les obligations professionnelles ont-elles été respectées ?',2)], 'Ces cadres peuvent coexister ; les associer ne préjuge pas de leur issue.', kind='matching')),
'03': dict(section='03-02', title='Un portique, un témoin et un justificatif', brief="À la sortie d’un magasin, trois informations arrivent au poste. Votre travail consiste à apprécier leur portée avant toute décision fondée sur l’article 73.", documents=[
 doc('Signal technique', 'Le portique sonne au passage simultané de deux clients.', ('Limite du signal', 'Le système ne désigne ni une personne ni la cause exacte de l’alarme.')),
 doc('Déclaration du vendeur', '« J’ai vu une personne prendre un article en rayon ; je n’ai pas suivi son passage en caisse. »', ('Source', 'Déclaration du vendeur reçue au poste.')),
 doc('Justificatif présenté', 'Un client présente un ticket comportant un article de même référence.', ('Vérification restante', 'Correspondance avec l’objet concerné et circonstances du signal, selon la procédure autorisée.'))], questions=[
 q('Le portique établit-il seul un vol flagrant par l’un des clients ?', 'Non : il fournit un signal à vérifier, sans établir à lui seul ces conditions.', 'Oui, dès que deux personnes passent ensemble.', 'Oui, sauf si le client proteste.', 'Il faut examiner les faits, leur source et le cadre juridique ; le signal ne remplace pas cette analyse.'),
 q('Quelle limite contient le témoignage ?', 'Le vendeur n’a pas observé la suite du parcours ni le passage en caisse.', 'Il n’a aucune valeur parce qu’il est oral.', 'Il prouve que personne n’a payé.', 'Une observation partielle reste utile si sa portée est décrite exactement.'),
 q('Quelle suite respecte le rôle du poste ?', 'Vérifier selon la procédure et alerter si les faits le justifient, sans imposer un aveu.', 'Retenir tout le groupe jusqu’à ce que quelqu’un avoue.', 'Encaisser une amende privée pour éviter un appel.', 'La vérification et le relais ne doivent pas devenir une enquête coercitive ou une sanction privée.')], classification=cards('Classez les affirmations selon leur portée.', ['Établi par les pièces', 'À vérifier', 'Conclusion non étayée'], [('Le portique a sonné',0), ('Le vendeur n’a pas suivi le passage en caisse',0), ('Correspondance du ticket avec l’objet',1), ('Les deux clients sont auteurs d’un vol',2)], 'Décrire les limites empêche de transformer des indices incomplets en certitudes.')),
'04': dict(section='04-01', title='Préparer une transmission de données utile', brief="Un incident d’accès doit être suivi par le responsable habilité. Comparez le besoin annoncé et les informations d’un projet d’export.", documents=[
 doc('Demande validée', 'Le responsable du site doit connaître l’événement AC-24, le point d’accès et la mesure encore attendue.', ('Destinataire', 'Responsable habilité via le canal professionnel prévu.'), ('Besoin', 'Organiser la vérification de l’autorisation d’accès.')),
 doc('Projet d’export', 'Le fichier rassemble davantage d’informations que le seul événement.', ('Ligne 1', 'AC-24 ; entrée B ; autorisation à confirmer.'), ('Ligne 2', 'Liste complète des visiteurs du mois.'), ('Ligne 3', 'Commentaire sans lien sur la vie familiale du visiteur.')),
 doc('Message de transfert proposé', '« Je vous envoie tout depuis mon adresse personnelle ; vous trierez ensuite. »', ('Point de contrôle', 'Le destinataire et le canal doivent correspondre au circuit autorisé.'))], questions=[
 q('Quelle ligne répond directement au besoin décrit ?', 'La ligne AC-24 avec l’accès et l’action attendue.', 'La liste complète du mois, par précaution.', 'Le commentaire familial, pour mieux connaître la personne.', 'La sélection part du besoin professionnel défini, pas de tout ce qui est disponible.'),
 q('Quel problème pose le canal proposé ?', 'L’adresse personnelle sort du circuit professionnel prévu pour cette transmission.', 'Un canal n’a aucune importance si le destinataire connaît l’agent.', 'Tout document peut être envoyé à tout responsable.', 'Le destinataire autorisé et le canal sécurisé sont deux vérifications distinctes.'),
 q('Que faire de la demande si le destinataire change ?', 'Vérifier ses droits et son besoin avant de réutiliser le même export.', 'Transmettre automatiquement puisqu’un premier destinataire était autorisé.', 'Publier le fichier pour que chacun puisse y accéder.', 'Une autorisation de communication ne se propage pas à tous les destinataires.')], classification=cards('Triez les éléments du projet.', ['Utile au besoin décrit', 'Excédentaire ou sans lien', 'Circuit à corriger'], [('Référence AC-24 et mesure attendue',0), ('Tous les visiteurs du mois',1), ('Commentaire sur la vie familiale',1), ('Envoi depuis une adresse personnelle',2)], 'La minimisation concerne le contenu ; la confidentialité concerne aussi le circuit de communication.')),
'05': dict(section='05-03', title='Relire une règle d’accueil', brief="Un accueil d’entreprise privée prépare une affiche. Vérifiez les motifs de contrôle et les formulations proposées sans attribuer à tous les visiteurs le même statut juridique.", documents=[
 doc('Règle d’accès validée pour le cas', 'Les visiteurs doivent avoir un rendez-vous confirmé ou obtenir la validation de l’accueil.', ('Accessibilité', 'Un cheminement adapté est disponible sur demande ; la vérification d’autorisation reste la même.')),
 doc('Brouillon d’affiche', '« Les personnes d’une origine supposée particulière seront systématiquement refusées. Tout visiteur doit adopter les opinions de l’entreprise. »', ('Statut', 'Brouillon non validé à corriger.')),
 doc('Trois demandes', 'A : rendez-vous confirmé et besoin d’un cheminement adapté. B : absence de rendez-vous, demande de vérification. C : rendez-vous confirmé, opinion critique exprimée sans menace ni trouble.', ('Cadre', 'Aucune autre condition d’accès n’est indiquée dans cet exercice.'))], questions=[
 q('Quel motif du brouillon doit être écarté ?', 'Le refus fondé sur l’origine supposée.', 'La vérification du rendez-vous.', 'L’organisation d’un cheminement adapté.', 'Le critère d’accès doit être objectif et compatible avec les droits des personnes.'),
 q('Comment traiter la demande B ?', 'Utiliser la vérification auprès de l’accueil prévue pour les visiteurs sans rendez-vous confirmé.', 'Refuser selon l’apparence du visiteur.', 'Laisser entrer sans vérification pour éviter toute différence de traitement.', 'L’égalité n’empêche pas d’appliquer une condition d’accès objective et la procédure de régularisation prévue.'),
 q('La demande C autorise-t-elle une sanction personnelle de l’opinion ?', 'Non : les actes et les règles applicables doivent guider l’évaluation de sécurité.', 'Oui, l’agent doit faire approuver les opinions de l’entreprise.', 'Oui, toute critique constitue une menace.', 'Une opinion critique sans autre fait ne se transforme pas en menace par désaccord du poste.')], classification=cards('Associez chaque situation à la démarche appropriée.', ['Vérifier l’autorisation manquante', 'Organiser l’accessibilité', 'Écarter le critère discriminatoire'], [('Rendez-vous non confirmé',0), ('Besoin d’un cheminement adapté',1), ('Refus en raison de l’origine supposée',2)], 'Les démarches répondent à des besoins différents ; l’adaptation de l’accueil ne supprime pas la règle d’accès.', kind='matching')),
'06': dict(section='06-04', title='Contrôler les demandes adressées au poste', brief="Quatre messages sont arrivés au poste. Repérez les demandes compatibles avec le service et celles qui doivent être refusées ou clarifiées.", documents=[
 doc('Demandes reçues', 'Les messages sont reproduits comme pièces du cas.', ('Fournisseur', '« Un bon cadeau si vous évitez notre contrôle habituel. »'), ('Ancien collègue', '« Envoie une photo du registre sur mon téléphone personnel. »')),
 doc('Message de la hiérarchie', '« Un contrôle officiel est annoncé. Conservez les documents et prévenez le responsable à l’arrivée des intervenants. »', ('Procédure', 'Vérification de la qualité des intervenants puis coopération selon le cadre du contrôle.')),
 doc('Note anonyme', '« Supprimez les entrées gênantes avant la visite. »', ('Statut', 'Auteur et validation inconnus.'))], questions=[
 q('Quel élément rend le cadeau problématique ?', 'Il est proposé en contrepartie d’une dérogation au contrôle.', 'Il n’est pas emballé.', 'Il n’est problématique que s’il dépasse une somme annoncée par le fournisseur.', 'Le lien avec la décision de sécurité constitue ici la pression à identifier.'),
 q('Quelle réponse à l’ancien collègue convient ?', 'Refuser la transmission informelle du registre.', 'Envoyer la photo puisqu’il a déjà travaillé sur le site.', 'Remplacer les noms par des initiales puis envoyer sans contrôle.', 'Un ancien accès professionnel ne crée pas un droit permanent aux informations du poste.'),
 q('Quelle conduite adopter avant le contrôle ?', 'Conserver les documents et suivre la procédure de vérification et de coopération.', 'Appliquer la note anonyme pour présenter un registre sans anomalie.', 'Réécrire les entrées sous le compte du responsable.', 'La coopération exige des données fidèles ; une correction régulière doit rester traçable.')], classification=cards('Orientez chaque demande.', ['Procédure professionnelle à suivre', 'Demande à refuser et signaler selon procédure'], [('Prévenir le responsable du contrôle',0), ('Cadeau contre un passe-droit',1), ('Photo du registre sur téléphone personnel',1), ('Suppression d’entrées gênantes',1)], 'Une demande se juge sur son objet et son cadre, pas seulement sur la relation avec son auteur.')),
'07': dict(section='07-05', title='Analyser un dialogue d’accueil', brief="Lisez les deux versions d’un échange. Repérez les formulations qui font avancer la vérification et celles qui renforcent la tension.", documents=[
 doc('Contexte', 'Le visiteur a une confirmation de rendez-vous ; son nom n’apparaît pas sur la liste du poste.', ('Environnement', 'Une file attend derrière lui. Un bureau latéral est disponible pour la vérification.')),
 doc('Version A', 'Visiteur : « Je vais être en retard. » Agent : « Vous avez une confirmation mais votre nom ne figure pas ici. Quel service vous attend ? Nous allons le joindre. »', ('Suite', 'L’agent annonce une étape précise sans garantir l’accès avant vérification.')),
 doc('Version B', 'Agent : « Vous êtes toujours compliqués. Si vous continuez, vous n’entrerez jamais. »', ('Suite', 'Deux collègues interviennent simultanément et entourent le visiteur.'))], questions=[
 q('Quel élément de A aide à comprendre le problème ?', 'La reformulation de l’écart entre confirmation et liste.', 'La promesse d’un accès sans contrôle, qui n’apparaît pas dans A.', 'Un jugement sur la personnalité du visiteur.', 'La reformulation vérifie le problème avant de chercher une solution.'),
 q('Quel effet peut avoir l’arrivée simultanée des collègues dans B ?', 'Accroître la pression et rendre l’échange confus.', 'Garantir automatiquement une désescalade.', 'Rendre inutile toute explication.', 'Le nombre d’interlocuteurs et la posture influencent la tension ; un appui doit rester organisé.'),
 q('Quelle adaptation de l’accueil est pertinente ici ?', 'Proposer le point de vérification latéral prévu et garder un interlocuteur principal.', 'Bloquer la file jusqu’à l’obtention d’excuses.', 'Accorder l’accès pour éviter toute attente.', 'L’organisation permet de traiter la demande sans abandonner la règle ni exposer inutilement la personne.')], classification=cards('Classez les formulations.', ['Clarifie le problème', 'Promet au-delà de ce qui est vérifié', 'Alimente la tension'], [('« Quel service vous attend ? »',0), ('« Je vous garantis l’entrée sans confirmation. »',1), ('« Vous êtes toujours compliqués. »',2), ('« Voici la vérification que nous allons faire. »',0)], 'Une bonne formulation est concrète, vérifiable et respectueuse.')),
'08': dict(section='08-01', title='Choisir la bonne version d’une consigne', brief="Le poste dispose de trois documents concernant une entrée en travaux. Déterminez lesquels régissent la situation sans supposer que la note la plus récente est forcément validée.", documents=[
 doc('Procédure générale V4', 'Contrôle habituel à l’entrée A.', ('Validité', 'Document validé ; applicable hors des exceptions validées.'), ('Public', 'Visiteurs et prestataires.')),
 doc('Consigne chantier C2', 'Les prestataires du chantier utilisent l’entrée B de 7 h à 12 h pendant la semaine indiquée.', ('Validation', 'Responsable du site identifié ; période incluant le jour de l’exercice.'), ('Limite', 'Les visiteurs restent à l’entrée A.')),
 doc('Projet C3', 'Tous les publics passent par B toute la journée.', ('Date', 'Plus récente que C2.'), ('Statut', 'Projet en attente de validation.'))], questions=[
 q('Un visiteur arrive à 10 h. Quelle entrée est prévue ?', 'L’entrée A, car l’exception C2 concerne les prestataires du chantier.', 'B, parce que le chantier existe.', 'B, parce que C3 est plus récent.', 'La catégorie de public fait partie du champ d’application.'),
 q('Un prestataire du chantier arrive à 11 h. Quel document décrit l’exception applicable ?', 'C2, dans son créneau et son périmètre.', 'C3 malgré l’absence de validation.', 'Aucun : toute exception annule la procédure générale.', 'Une exception validée peut modifier une partie de la procédure sans l’abroger pour les autres cas.'),
 q('Que faire avant d’appliquer C3 ?', 'Obtenir sa validation et confirmer son entrée en application par le circuit prévu.', 'L’appliquer immédiatement car il est plus récent.', 'Supprimer C2 pour éviter d’avoir deux fichiers.', 'Une date récente ne transforme pas un projet en instruction applicable.')], classification=cards('Associez chaque contrôle à la question qu’il résout.', ['Qui a validé ?', 'Pour qui et où ?', 'Quand s’applique-t-elle ?'], [('Autorité de validation',0), ('Périmètre et public concernés',1), ('Période et créneau horaire',2)], 'Ces trois contrôles se complètent ; aucun ne remplace les autres.', kind='matching')),
'09': dict(section='09-03', title='Relire une justification de décision', brief="Un projet de compte rendu justifie une mesure prise dans l’urgence. Contrôlez si les faits et les informations y sont présentés au bon moment.", documents=[
 doc('Chronologie disponible', 'Les horaires sont confirmés par les pièces du cas.', ('16 h 02', 'Une personne avance vers un salarié en le menaçant.'), ('16 h 03', 'Le salarié est mis à l’abri et un appui est demandé.'), ('16 h 05', 'La personne s’éloigne ; aucune nouvelle menace n’est observée.'), ('16 h 20', 'Un tiers rapporte un ancien conflit.')),
 doc('Projet de justification', '« Dès 16 h 02, je savais que cette personne avait un conflit ancien. Toutes les mesures restaient donc nécessaires après 16 h 05. »', ('Statut', 'Projet à examiner, non validé.')),
 doc('Question du responsable', '« Quelles informations connaissiez-vous lors de chaque choix ? Qu’est-ce qui justifiait la poursuite ou l’arrêt des mesures ? »')], questions=[
 q('Quelle information est replacée à tort dans le passé ?', 'Le conflit ancien, appris à 16 h 20.', 'La menace observée à 16 h 02.', 'La mise à l’abri de 16 h 03.', 'Une information tardive doit conserver son heure d’obtention.'),
 q('Quel effet a l’évolution de 16 h 05 ?', 'Elle impose de réévaluer la nécessité des mesures selon le nouveau contexte.', 'Elle n’a aucune incidence sur une action déjà commencée.', 'Elle prouve que la menace de 16 h 02 n’a jamais existé.', 'Une évolution change l’analyse actuelle sans effacer les faits antérieurs.'),
 q('Quel complément rendrait la justification plus utile ?', 'Les moyens disponibles et les raisons du choix au moment considéré.', 'Un jugement définitif sur la personnalité de l’auteur.', 'Une conclusion judiciaire rédigée par l’agent.', 'Expliquer une décision demande ses conditions concrètes, sans remplacer l’autorité compétente.')], classification=cards('Classez les éléments.', ['Connu lors de la première décision', 'Évolution à réévaluer', 'Information apprise ensuite'], [('Menace observée à 16 h 02',0), ('Départ à 16 h 05',1), ('Conflit ancien rapporté à 16 h 20',2)], 'La chronologie des connaissances fait partie de la justification.')),
'10': dict(section='10-07', title='Préparer l’accès d’une entreprise extérieure', brief="Un prestataire arrive dans un site industriel. Croisez le bon d’intervention, les contraintes de zone et la situation réellement observée. Il s’agit d’un exercice de contrôle d’accès et d’alerte, sans manipulation technique.", documents=[
 doc('Intervention autorisée pour le cas', 'Remplacement d’un équipement dans la zone Z, de 10 h à 12 h, avec coordination par le référent maintenance.', ('Conditions', 'Cheminement piéton séparé ; matériel vérifié compatible avec les contraintes de la zone.')),
 doc('Constat à l’accueil à 9 h 20', 'Le prestataire se présente en avance.', ('Circulation', 'Une livraison utilise le cheminement prévu.'), ('Matériel', 'Un appareil différent de la liste est apporté ; sa compatibilité n’est pas documentée.')),
 doc('Consigne de zone Z', 'L’accès à cette zone soumise à des contraintes ATEX nécessite la confirmation des conditions par le référent désigné.', ('Instruction du cas', 'Ne pas tester un équipement dans la zone pour déterminer sa compatibilité.'))], questions=[
 q('Le badge du prestataire suffit-il à autoriser l’intervention maintenant ?', 'Non : le créneau, la coactivité et le matériel doivent être vérifiés avec le référent.', 'Oui : le badge autorise toutes les opérations.', 'Oui : l’arrivée en avance supprime le risque de coactivité.', 'Les conditions réelles diffèrent de l’organisation autorisée ; le poste doit faire traiter ces écarts.'),
 q('Quelle anomalie concerne la protection collective ?', 'Le cheminement piéton n’est plus séparé du flux de livraison.', 'Le prestataire est arrivé avec son dossier.', 'Le référent maintenance est désigné.', 'La séparation des circulations est une mesure de prévention ; sa dégradation doit être signalée.'),
 q('Que faire de l’appareil non documenté ?', 'Faire vérifier sa compatibilité avant accès, selon la consigne.', 'L’allumer dans la zone pour le tester.', 'L’accepter parce qu’il est neuf.', 'L’état apparent et le fonctionnement ne prouvent pas l’adéquation au risque de la zone.')], classification=cards('Rattachez les informations à leur objet.', ['Organisation et coactivité', 'Protection collective', 'Adéquation du matériel'], [('Créneau et coordination avec le référent',0), ('Séparation du passage piéton',1), ('Compatibilité de l’appareil avec la zone',2)], 'Le contrôle croise plusieurs dimensions ; résoudre l’une ne valide pas automatiquement les autres.', kind='matching')),
'11': dict(section='11-02', title='Lire une demande d’intervention électrique', brief="Une anomalie est signalée. Examinez ce que le poste sait, les limites de l’agent et la demande du client avant de choisir les actions de protection et de relais.", documents=[
 doc('Signalement', 'Un coffret produit un bruit inhabituel ; une odeur anormale est perçue à proximité.', ('Situation', 'Un passage visiteurs longe la zone ; personne n’est blessé à ce stade.')),
 doc('Fiche de poste pour le cas', 'L’agent doit signaler l’anomalie et empêcher l’accès selon la procédure.', ('Limite', 'Aucune opération électrique sur ce coffret n’est confiée à cet agent.'), ('Relais', 'Responsable technique désigné dans l’annuaire du site.')),
 doc('Demande du client', '« Ouvrez le coffret, puis réarmez plusieurs fois : cela évitera une interruption. »', ('Point de contrôle', 'Le défaut et l’état de sécurité ne sont pas établis.'))], questions=[
 q('Quelle action entre dans le rôle indiqué ?', 'Écarter les personnes de la zone selon la consigne et alerter le relais technique.', 'Ouvrir le coffret pour chercher la panne.', 'Réarmer plusieurs fois pour confirmer le défaut.', 'La protection et le signalement sont prévus ; la réparation ne fait pas partie des opérations confiées.'),
 q('L’absence de blessé permet-elle de déclarer la zone sûre ?', 'Non : les signes observés justifient l’évaluation et les mesures prévues.', 'Oui : un danger n’existe qu’après un accident.', 'Oui si le client souhaite poursuivre l’activité.', 'La prévention intervient avant le dommage ; la demande du client ne supprime pas le danger.'),
 q('Quelle information aide le relais technique ?', 'Le lieu exact, les signes observés et les mesures de protection mises en place.', 'Un diagnostic de panne inventé par l’agent.', 'Seulement la conclusion « problème réglé ».', 'Un signalement précis permet au relais de préparer son intervention sans être trompé par une expertise supposée.')], classification=cards('Classez les actions proposées.', ['Protection et alerte prévues', 'Opération non confiée dans ce cas'], [('Empêcher l’exposition des visiteurs',0), ('Contacter le responsable technique',0), ('Ouvrir le coffret',1), ('Réarmer plusieurs fois',1)], 'La fiche de poste et la compétence doivent correspondre à l’opération envisagée.')),
'12': dict(section='12-07', title='Distinguer signalement, rumeur et consigne', brief="À l’accueil d’un événement, plusieurs informations circulent. Votre mission est d’en apprécier la source et d’appliquer le circuit de signalement prévu, sans qualification ou expertise improvisée.", documents=[
 doc('Observation au poste', 'Un accès réservé a fait l’objet de plusieurs tentatives d’ouverture après un refus expliqué.', ('Source', 'Observation directe de l’agent à 17 h 10.'), ('Limite', 'L’intention de la personne n’est pas connue.')),
 doc('Capture reçue', 'Un message anonyme affirme qu’une attaque a commencé ailleurs sur le site.', ('Source', 'Transfert sur un téléphone personnel ; aucun fait de la capture n’est confirmé au poste.')),
 doc('Consigne validée du dispositif', 'Signaler rapidement les faits préoccupants au responsable par le canal prévu ; appliquer les mesures de protection décidées.', ('Communication', 'Ne pas diffuser aux visiteurs une rumeur comme une information confirmée.'), ('Actualisation', 'Utiliser les consignes officielles et du site en vigueur.'))], questions=[
 q('Quelle information est directement observée ?', 'Les tentatives d’ouverture de l’accès réservé.', 'L’attaque annoncée par la capture.', 'Une intention terroriste certaine.', 'La source et la portée de l’observation doivent rester explicites.'),
 q('Faut-il attendre de connaître l’intention avant de signaler ?', 'Non : transmettre les faits préoccupants et leurs limites selon la procédure.', 'Oui : aucun signalement n’est possible sans qualification certaine.', 'Oui : la capture anonyme constitue déjà une alerte officielle.', 'Un signalement peut être utile sans certitude sur l’intention ou la qualification.'),
 q('Que faire de la capture ?', 'La signaler comme information non confirmée au relais prévu, sans la présenter comme un ordre.', 'La diffuser comme une confirmation d’attaque.', 'Modifier seul tout le dispositif sur cette seule base.', 'Le relais doit connaître l’information qui circule et son absence de confirmation pour décider des vérifications.')], classification=cards('Classez les éléments.', ['Fait observé', 'Information non confirmée', 'Consigne validée'], [('Tentatives d’ouverture décrites par l’agent',0), ('Attaque annoncée dans la capture anonyme',1), ('Canal de signalement fixé au briefing',2), ('Intention supposée de la personne',1)], 'La source aide à choisir comment utiliser l’information ; elle ne doit pas être effacée lors du relais.')),
'14': dict(section='14-07', title='Comparer les pièces avant un relais à l’OPJ', brief="Un dossier de dégradation rassemble une observation, deux déclarations et une photographie. Contrôlez ce que chaque pièce permet réellement de transmettre.", documents=[
 doc('Observation de l’agent', 'À 20 h 12, une vitre est brisée. L’agent n’a pas vu le geste.', ('Mesure', 'Le passage a été protégé et le relais prévu alerté.')),
 doc('Déclarations', 'Les témoins ont été entendus séparément dans les limites du rôle du poste.', ('Témoin A', '« J’ai entendu un choc ; je regardais ailleurs. »'), ('Témoin B', '« J’ai vu une personne s’éloigner, sans voir la vitre se briser. »')),
 doc('Photographie autorisée du dommage', 'L’image montre la vitre brisée ; aucun auteur n’y apparaît.', ('Brouillon de légende', '« Preuve que la personne vue par B a commis la dégradation. »'))], questions=[
 q('Quelle légende respecte la portée de la photo ?', '« Vitre brisée constatée à 20 h 12 ; auteur non observé sur cette image. »', '« Auteur identifié par la photographie. »', '« Absence de dommage faute d’auteur visible. »', 'La photographie documente un dommage, pas un geste ou une identité qu’elle ne montre pas.'),
 q('Que faire des deux déclarations ?', 'Conserver leur contenu et leur source, sans leur faire dire qu’un auteur a été vu agir.', 'Les fusionner en une observation directe de l’agent.', 'Demander aux témoins de choisir une même version.', 'Le dossier doit rendre lisible la portée limitée de chaque témoignage.'),
 q('Quel élément complète utilement le relais ?', 'Les mesures prises pour protéger le passage et les informations encore manquantes.', 'Une conclusion de culpabilité prononcée par le poste.', 'La suppression de toute incertitude dans le récit.', 'Le relais doit comprendre les actions et les limites du dossier pour poursuivre son travail.')], classification=cards('Classez ces formulations.', ['Établi par les pièces', 'Déclaration rapportée', 'Déduction non établie'], [('Vitre brisée observée à 20 h 12',0), ('Un choc entendu selon A',1), ('La personne vue par B est nécessairement l’auteur',2), ('Passage protégé par l’agent',0)], 'La qualification de la source évite d’amplifier la portée d’un renseignement.')),
'15': dict(section='15-07', title='Préparer l’ouverture d’un événement', brief="Avant l’ouverture, croisez la matrice d’accès, le point de situation et les consignes de flux. Chaque décision doit traiter le bon problème sans créer un autre obstacle.", documents=[
 doc('Matrice d’accès du cas', 'Les accréditations sont limitées aux zones indiquées.', ('Public', 'Entrée P puis espace public.'), ('Presse', 'Entrée M puis zone presse ; pas d’accès aux coulisses.'), ('Secours', 'Accès S réservé, cheminement à maintenir libre.')),
 doc('Point de situation', 'Trois écarts sont signalés dix minutes avant l’ouverture.', ('Entrée P', 'La file empiète sur le cheminement vers une issue.'), ('Accès S', 'Un véhicule de livraison stationne sur le cheminement réservé.'), ('Entrée M', 'Un photographe demande les coulisses avec un badge presse.')),
 doc('Consignes de coordination', 'Informer le responsable du dispositif des obstacles ; utiliser le circuit secondaire pour les litiges de billet.', ('Billetterie', 'Un message « déjà utilisé » doit être vérifié par le relais billetterie.'), ('Modification des flux', 'Coordination requise avant changement de cheminement.'))], questions=[
 q('Quel problème exige de rétablir la fonction de l’accès S ?', 'Le véhicule de livraison obstrue le cheminement réservé aux secours.', 'La présence d’un photographe à M.', 'Le fait que le public utilise P conformément au plan.', 'Un véhicule accrédité ne reçoit pas pour autant le droit d’obstruer un accès réservé.'),
 q('Que permet le badge presse dans ce dossier ?', 'L’accès à la zone presse indiquée, pas aux coulisses.', 'L’accès à toutes les zones avec un appareil photo.', 'L’accès à S pour éviter la file.', 'Les droits se lisent dans la matrice, pas dans la notoriété ou l’équipement du porteur.'),
 q('Comment traiter un billet « déjà utilisé » ?', 'L’orienter vers le contrôle secondaire prévu pour vérification.', 'Déclarer immédiatement une fraude certaine.', 'Bloquer l’issue pour garder le visiteur près du contrôle.', 'Le signal de billetterie demande une vérification et ne doit pas créer un risque de circulation.')], classification=cards('Associez chaque écart à son premier relais fonctionnel.', ['Responsable des flux', 'Relais accès secours / dispositif', 'Relais accréditation', 'Relais billetterie'], [('File empiétant sur une issue',0), ('Livraison obstruant S',1), ('Demande presse vers coulisses',2), ('Billet signalé déjà utilisé',3)], 'Les relais proposés correspondent à l’organisation fictive de l’exercice ; sur site, suivre l’annuaire et les rôles du dispositif.', kind='matching')),
}

JOURNALS = {
'08-03': dict(title='Main courante 1 · distinguer les heures et les sources', brief='Composez une entrée fidèle au signalement et au contrôle. Le but est de ne pas transformer une heure approximative rapportée en observation personnelle.', documents=[
 doc('Signalement reçu à 10 h 19', 'Une salariée déclare : « J’ai vu la porte B ouverte vers 10 h 14. »', ('Source', 'Déclaration de la salariée, pas observation de l’agent.')),
 doc('Contrôle et saisie', 'L’agent constate la porte B ouverte à 10 h 22 et protège l’accès selon la consigne.', ('Saisie', '10 h 28'), ('Suivi', 'Maintenance avisée à 10 h 24 ; remise en état non confirmée.'))], questions=[
 q('Heures à conserver', 'Observation rapportée : vers 10 h 14 ; signalement : 10 h 19 ; contrôle : 10 h 22 ; saisie : 10 h 28.', 'Tout l’événement a lieu à 10 h 28.', 'L’agent a observé personnellement la porte à 10 h 14 précises.', 'Chaque heure conserve sa fonction et le caractère approximatif donné par la source.'),
 q('Origine du premier constat', 'Selon la salariée, la porte B était ouverte vers 10 h 14.', 'L’agent a vu la porte ouverte à 10 h 14.', 'La porte était ouverte depuis le début de la journée.', 'La déclaration ne doit pas devenir une observation directe ni une durée inventée.'),
 q('Fait vérifié par l’agent', 'Porte B constatée ouverte à 10 h 22.', 'Intrusion volontaire certaine par la porte B.', 'Porte fermée à 10 h 22.', 'Le constat porte sur l’état de la porte, pas sur une intention ou une cause non établie.'),
 q('Actions effectuées', 'Accès protégé selon la consigne ; maintenance avisée à 10 h 24.', 'Réparation achevée avant la saisie.', 'Aucune action entreprise.', 'Le document décrit les actions réelles, sans confondre demande et résultat.'),
 q('État du suivi', 'Remise en état non confirmée au moment de la saisie.', 'Dossier clos parce que la maintenance est prévenue.', 'Aucune suite utile à transmettre.', 'La suite doit rester ouverte tant que le résultat n’est pas confirmé.')]),
'08-05': dict(title='Main courante 2 · transmettre un suivi à la relève', brief='Préparez l’entrée qui permettra à l’équipe suivante de reprendre un incident non résolu. Le but est de rendre visibles la mesure provisoire, l’interlocuteur et la prochaine vérification.', documents=[
 doc('Incident BR-18', 'À 18 h 40, la barrière d’accès D ne répond plus à la commande.', ('Mesure', 'À 18 h 42, le flux est orienté vers E selon la consigne du responsable.'), ('Relais', 'Maintenance contactée à 18 h 43 ; intervention annoncée, horaire non confirmé.')),
 doc('Situation à la relève', 'À 19 h, aucune confirmation de réparation n’a été reçue.', ('Instruction du responsable', 'Maintenir le dispositif provisoire et demander un point à la maintenance à 19 h 15 si aucune nouvelle n’est reçue.'), ('Saisie', '18 h 58 ; transmission à l’équipe entrante à 19 h.'))], questions=[
 q('Référence et constat', 'BR-18 : barrière D sans réponse depuis le constat de 18 h 40.', 'Toutes les barrières du site sont hors service.', 'BR-18 : barrière D réparée.', 'La trace reste limitée à l’équipement et au constat du dossier.'),
 q('Mesure provisoire', 'Flux orienté vers E à 18 h 42 selon la consigne du responsable.', 'Accès D rouvert automatiquement à la relève.', 'Tous les accès fermés sans consigne.', 'La relève doit connaître le dispositif en vigueur et son origine.'),
 q('État de l’intervention', 'Maintenance contactée à 18 h 43 ; intervention annoncée, réparation non confirmée.', 'Réparation confirmée dès l’appel.', 'Aucun interlocuteur contacté.', 'Une intervention annoncée ne vaut pas une réparation réalisée.'),
 q('Prochaine action', 'Demander un point à la maintenance à 19 h 15 si aucune nouvelle, selon la consigne transmise.', 'Clore à 19 h 15 sans nouvelle.', 'Attendre la prochaine journée sans relance.', 'L’action à reprendre est associée à une condition et un horaire précis.'),
 q('Transmission', 'Entrée saisie à 18 h 58 ; suivi BR-18 transmis à l’équipe entrante à 19 h.', 'L’incident est apparu à 19 h au changement d’équipe.', 'La relève efface les actions de l’équipe précédente.', 'Le changement d’équipe ne modifie ni l’heure des faits ni l’historique des actions.')]),
'13-01': dict(title='Main courante 3 · rectifier une entrée sans effacer son histoire', brief='Composez une rectification de l’entrée MC-1476. Le but est de relier la correction au bon événement et de préserver la chronologie de la saisie.', documents=[
 doc('Entrée validée MC-1476', 'À 14 h 12, l’agent a saisi : « Contrôle de la porte C à 14 h 05 ; porte fermée. »', ('Erreur découverte', 'À 14 h 25, la fiche de ronde confirme que le contrôle concernait la porte B.')),
 doc('Procédure de correction du cas', 'Ajouter une rectification liée à l’entrée initiale, avec auteur, date de correction et motif.', ('Droits', 'Utiliser son compte personnel autorisé.'), ('Limite', 'Ne pas effacer l’entrée initiale ni modifier l’heure du contrôle pour masquer l’erreur.'))], questions=[
 q('Entrée concernée', 'Rectification liée à MC-1476.', 'Nouvel incident sans lien avec MC-1476.', 'Suppression de MC-1476.', 'Le lien permet au lecteur de retrouver la donnée corrigée et son historique.'),
 q('Fait rectifié', 'Le contrôle de 14 h 05 concernait la porte B, constatée fermée, et non la porte C.', 'Le contrôle a eu lieu à 14 h 25 sur la porte C.', 'Toutes les portes étaient fermées à 14 h 05.', 'La correction porte sur le lieu erroné, pas sur les autres éléments non remis en cause.'),
 q('Motif et source', 'Erreur de lieu identifiée à 14 h 25 par comparaison avec la fiche de ronde.', 'Modification sans motif pour harmoniser les dossiers.', 'Erreur attribuée au collègue sans élément.', 'La source et le motif rendent la rectification compréhensible.'),
 q('Traçabilité de la correction', 'Correction datée au moment de sa réalisation, sous le compte de son auteur ; entrée initiale conservée.', 'Correction antidatée à 14 h 05.', 'Correction sous un compte partagé pour éviter d’identifier l’auteur.', 'L’heure du fait et celle de la correction remplissent des fonctions différentes.')]),
'13-02': dict(title='Main courante 4 · reprendre après une panne sans créer de doublon', brief='Préparez la reprise du suivi après une indisponibilité. Le but est de rapprocher les supports et de conserver les heures réelles sans créer deux incidents pour un seul événement.', documents=[
 doc('Support de secours P-04', 'Application indisponible de 9 h à 9 h 35.', ('Événement à 9 h 12', 'Interphone B sans réponse ; prestataire orienté vers l’accueil A selon la consigne.'), ('Action à 9 h 18', 'Service technique avisé ; résolution non confirmée.')),
 doc('Contrôle après reprise', 'À 9 h 40, l’agent retrouve MC-210, créé à 9 h 37 par son collègue pour le même événement P-04.', ('Déjà présent', 'Constat de 9 h 12 et orientation vers A.'), ('Manquant', 'Appel au service technique de 9 h 18 et état du suivi.')),
 doc('Procédure du cas', 'Vérifier les références et compléter l’entrée existante si nécessaire ; identifier le support d’origine et la reprise.', ('Support temporaire', 'Le conserver et le transmettre selon le circuit prévu, sans destruction improvisée.'))], questions=[
 q('Référence à utiliser', 'Complément à MC-210, rapproché du support P-04.', 'Nouvel incident indépendant pour P-04.', 'Suppression de MC-210 et du support P-04.', 'Le rapprochement des références évite de compter deux fois le même événement.'),
 q('Information à compléter', 'Service technique avisé à 9 h 18 ; résolution non confirmée.', 'Interphone réparé à 9 h 35 parce que l’application fonctionne.', 'Nouvel incident d’interphone à 9 h 40.', 'La reprise de l’application ne prouve pas la résolution du défaut d’interphone.'),
 q('Horaires et origine', 'Complément saisi après reprise, d’après P-04 ; heures des faits conservées : 9 h 12 et 9 h 18.', 'Toutes les actions sont antidatées comme saisies en ligne à 9 h 12.', 'L’heure du fait est remplacée par 9 h 40.', 'La trace distingue faits, support de secours et reprise informatique.'),
 q('Suite documentaire', 'Support P-04 traité selon le circuit de conservation prévu ; suivi technique restant ouvert.', 'Support détruit immédiatement pour supprimer tout doublon visible.', 'Dossier clos automatiquement lors du retour de l’application.', 'La prévention des doublons porte sur le dossier ; elle ne justifie pas une destruction arbitraire des sources.')]),
}
